<?php

/* ChilkatVersion.php -- the Chilkat version this package was generated for.
 * Generated by ChilkatApi/GenCkPhp.cs for Chilkat v11.6.1 -- do not edit.
 * Reference documentation: https://www.chilkatsoft.com/refdoc/ */

final class ChilkatVersion
{
	/** The Chilkat release the proxy classes match; bin/chilkat-install installs this version of the extension. */
	const VERSION = '11.6.1';
}
