<?php

/* chilkat.php -- static helpers used by every Chilkat proxy class.
 * Generated by ChilkatApi/GenCkPhp.cs for Chilkat v11.6.1 -- do not edit.
 * Reference documentation: https://www.chilkatsoft.com/refdoc/ */

abstract class chilkat {
	static function _ck_nullptr_error_set($_ck_nullptr_error) {
		_ck_nullptr_error_set($_ck_nullptr_error);
	}

	static function _ck_nullptr_error_get() {
		return _ck_nullptr_error_get();
	}

	static function _ck_type_error_msg_set($_ck_type_error_msg) {
		_ck_type_error_msg_set($_ck_type_error_msg);
	}

	static function _ck_type_error_msg_get() {
		return _ck_type_error_msg_get();
	}

	static function _ckReturnByteData($z,$s,$l) {
		_ckReturnByteData($z,$s,$l);
	}

	// Wraps a resource returned by the extension in its proxy class (resource type _p_CkXxx -> class CkXxx).
	static function _obj($r,$c) {
		if (!is_resource($r)) return $r;
		$t=substr(get_resource_type($r),3);
		if (class_exists($t)) return new $t($r);
		return new $c($r);
	}
}
