<?php

/* CkAuthAzureSAS.php -- Chilkat PHP extension proxy class CkAuthAzureSAS.
 * Generated by ChilkatApi/GenCkPhp.cs for Chilkat v11.6.1 -- do not edit.
 * Reference documentation: https://www.chilkatsoft.com/refdoc/ */

/**
 * Create Azure Shared Access Signature tokens for signed Azure Storage requests.
 *
 * Chilkat.AuthAzureSAS creates Azure Shared Access Signature authentication tokens. It defines the SAS string-to-sign, supplies the Azure Storage account access key used to compute the signature, and controls which parameters are included in the generated SAS token query string. The resulting token can be used with Chilkat.Rest, Chilkat.Http, or other request-building code that needs time-limited, permission-scoped access to Azure Storage resources.
 *
 * @see https://www.chilkatsoft.com/refdoc/phpCkAuthAzureSASRef.html
 */
class CkAuthAzureSAS {
	public $_cPtr=null;
	protected $_pData=array();

	function __set($var,$value) {
		if ($var === 'thisown') return swig_chilkat_alter_newobject($this->_cPtr,$value);
		$this->_pData[$var] = $value;
	}

	function __get($var) {
		if ($var === 'thisown') return swig_chilkat_get_newobject($this->_cPtr);
		return $this->_pData[$var];
	}

	function __isset($var) {
		if ($var === 'thisown') return true;
		return array_key_exists($var, $this->_pData);
	}

	function __construct($res=null) {
		if (is_resource($res) && get_resource_type($res) === '_p_CkAuthAzureSAS') {
			$this->_cPtr=$res;
			return;
		}
		$this->_cPtr=new_CkAuthAzureSAS();
	}

	/**
	 * When true, strings passed to and returned from the object are UTF-8. When false (the default), they are ANSI (the locale's 8-bit character encoding).
	 * @see https://www.chilkatsoft.com/refdoc/phpCkAuthAzureSASRef.html
	 * @return bool
	 */
	function get_Utf8() {
		return CkAuthAzureSAS_get_Utf8($this->_cPtr);
	}

	/**
	 * When true, strings passed to and returned from the object are UTF-8. When false (the default), they are ANSI (the locale's 8-bit character encoding).
	 * @see https://www.chilkatsoft.com/refdoc/phpCkAuthAzureSASRef.html
	 * @param bool $b
	 */
	function put_Utf8($b) {
		CkAuthAzureSAS_put_Utf8($this->_cPtr,$b);
	}

	/**
	 * This is the signing key (access key) that must be kept private.   It is a base64 string such as abdTvCZFFoWUyre6erlNN+IOb9qhXgDsyhrxmZvpmxqFDwpl9oD0X9Fy0hIQa6L5UohznRLmkCtUYySO4Y2eaw==
	 * @see https://www.chilkatsoft.com/refdoc/phpCkAuthAzureSASRef.html#AccessKey
	 * @param CkString $str
	 */
	function get_AccessKey($str) {
		CkAuthAzureSAS_get_AccessKey($this->_cPtr,$str);
	}

	/**
	 * This is the signing key (access key) that must be kept private.   It is a base64 string such as abdTvCZFFoWUyre6erlNN+IOb9qhXgDsyhrxmZvpmxqFDwpl9oD0X9Fy0hIQa6L5UohznRLmkCtUYySO4Y2eaw==
	 * @see https://www.chilkatsoft.com/refdoc/phpCkAuthAzureSASRef.html#AccessKey
	 * @return ?string
	 */
	function accessKey() {
		return CkAuthAzureSAS_accessKey($this->_cPtr);
	}

	/**
	 * This is the signing key (access key) that must be kept private.   It is a base64 string such as abdTvCZFFoWUyre6erlNN+IOb9qhXgDsyhrxmZvpmxqFDwpl9oD0X9Fy0hIQa6L5UohznRLmkCtUYySO4Y2eaw==
	 * @see https://www.chilkatsoft.com/refdoc/phpCkAuthAzureSASRef.html#AccessKey
	 * @param ?string $newVal
	 */
	function put_AccessKey($newVal) {
		CkAuthAzureSAS_put_AccessKey($this->_cPtr,$newVal);
	}

	/**
	 * If set to a file path, this property logs the LastErrorText of each Chilkat method or property call to the specified file. This logging helps identify the context and history of Chilkat calls leading up to any crash or hang, aiding in debugging.  Enabling the VerboseLogging property provides more detailed information.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkAuthAzureSASRef.html#DebugLogFilePath
	 * @param CkString $str
	 */
	function get_DebugLogFilePath($str) {
		CkAuthAzureSAS_get_DebugLogFilePath($this->_cPtr,$str);
	}

	/**
	 * If set to a file path, this property logs the LastErrorText of each Chilkat method or property call to the specified file. This logging helps identify the context and history of Chilkat calls leading up to any crash or hang, aiding in debugging.  Enabling the VerboseLogging property provides more detailed information.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkAuthAzureSASRef.html#DebugLogFilePath
	 * @return ?string
	 */
	function debugLogFilePath() {
		return CkAuthAzureSAS_debugLogFilePath($this->_cPtr);
	}

	/**
	 * If set to a file path, this property logs the LastErrorText of each Chilkat method or property call to the specified file. This logging helps identify the context and history of Chilkat calls leading up to any crash or hang, aiding in debugging.  Enabling the VerboseLogging property provides more detailed information.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkAuthAzureSASRef.html#DebugLogFilePath
	 * @param ?string $newVal
	 */
	function put_DebugLogFilePath($newVal) {
		CkAuthAzureSAS_put_DebugLogFilePath($this->_cPtr,$newVal);
	}

	/**
	 * Provides HTML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkAuthAzureSASRef.html#LastErrorHtml
	 * @param CkString $str
	 */
	function get_LastErrorHtml($str) {
		CkAuthAzureSAS_get_LastErrorHtml($this->_cPtr,$str);
	}

	/**
	 * Provides HTML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkAuthAzureSASRef.html#LastErrorHtml
	 * @return ?string
	 */
	function lastErrorHtml() {
		return CkAuthAzureSAS_lastErrorHtml($this->_cPtr);
	}

	/**
	 * Provides plain text information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkAuthAzureSASRef.html#LastErrorText
	 * @param CkString $str
	 */
	function get_LastErrorText($str) {
		CkAuthAzureSAS_get_LastErrorText($this->_cPtr,$str);
	}

	/**
	 * Provides plain text information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkAuthAzureSASRef.html#LastErrorText
	 * @return ?string
	 */
	function lastErrorText() {
		return CkAuthAzureSAS_lastErrorText($this->_cPtr);
	}

	/**
	 * Provides XML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkAuthAzureSASRef.html#LastErrorXml
	 * @param CkString $str
	 */
	function get_LastErrorXml($str) {
		CkAuthAzureSAS_get_LastErrorXml($this->_cPtr,$str);
	}

	/**
	 * Provides XML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkAuthAzureSASRef.html#LastErrorXml
	 * @return ?string
	 */
	function lastErrorXml() {
		return CkAuthAzureSAS_lastErrorXml($this->_cPtr);
	}

	/**
	 * Indicates the success or failure of the most recent method call: _TRUE_ means success, _FALSE_ means failure. This property remains unchanged by property setters or getters.  This method is present to address challenges in checking for null or Nothing returns in certain programming languages.  Note: This property does not apply to methods that return integer values or to boolean-returning methods where the boolean does not indicate success or failure.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkAuthAzureSASRef.html#LastMethodSuccess
	 * @return bool
	 */
	function get_LastMethodSuccess() {
		return CkAuthAzureSAS_get_LastMethodSuccess($this->_cPtr);
	}

	/**
	 * Indicates the success or failure of the most recent method call: _TRUE_ means success, _FALSE_ means failure. This property remains unchanged by property setters or getters.  This method is present to address challenges in checking for null or Nothing returns in certain programming languages.  Note: This property does not apply to methods that return integer values or to boolean-returning methods where the boolean does not indicate success or failure.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkAuthAzureSASRef.html#LastMethodSuccess
	 * @param bool $newVal
	 */
	function put_LastMethodSuccess($newVal) {
		CkAuthAzureSAS_put_LastMethodSuccess($this->_cPtr,$newVal);
	}

	/**
	 * Defines the format of the string to sign. The format is specified as a comma-separated list of names. For example:
	 * @see https://www.chilkatsoft.com/refdoc/phpCkAuthAzureSASRef.html#StringToSign
	 * @param CkString $str
	 */
	function get_StringToSign($str) {
		CkAuthAzureSAS_get_StringToSign($this->_cPtr,$str);
	}

	/**
	 * Defines the format of the string to sign. The format is specified as a comma-separated list of names. For example:
	 * @see https://www.chilkatsoft.com/refdoc/phpCkAuthAzureSASRef.html#StringToSign
	 * @return ?string
	 */
	function stringToSign() {
		return CkAuthAzureSAS_stringToSign($this->_cPtr);
	}

	/**
	 * Defines the format of the string to sign. The format is specified as a comma-separated list of names. For example:
	 * @see https://www.chilkatsoft.com/refdoc/phpCkAuthAzureSASRef.html#StringToSign
	 * @param ?string $newVal
	 */
	function put_StringToSign($newVal) {
		CkAuthAzureSAS_put_StringToSign($this->_cPtr,$newVal);
	}

	/**
	 * If set to _TRUE_, then the contents of LastErrorText (or LastErrorXml, or LastErrorHtml) may contain more verbose information. The default value is _FALSE_.  Verbose logging should only be used for debugging.  The potentially large quantity of logged information may adversely affect peformance.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkAuthAzureSASRef.html#VerboseLogging
	 * @return bool
	 */
	function get_VerboseLogging() {
		return CkAuthAzureSAS_get_VerboseLogging($this->_cPtr);
	}

	/**
	 * If set to _TRUE_, then the contents of LastErrorText (or LastErrorXml, or LastErrorHtml) may contain more verbose information. The default value is _FALSE_.  Verbose logging should only be used for debugging.  The potentially large quantity of logged information may adversely affect peformance.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkAuthAzureSASRef.html#VerboseLogging
	 * @param bool $newVal
	 */
	function put_VerboseLogging($newVal) {
		CkAuthAzureSAS_put_VerboseLogging($this->_cPtr,$newVal);
	}

	/**
	 * Version of the component/library, such as "10.1.0"
	 * @see https://www.chilkatsoft.com/refdoc/phpCkAuthAzureSASRef.html#Version
	 * @param CkString $str
	 */
	function get_Version($str) {
		CkAuthAzureSAS_get_Version($this->_cPtr,$str);
	}

	/**
	 * Version of the component/library, such as "10.1.0"
	 * @see https://www.chilkatsoft.com/refdoc/phpCkAuthAzureSASRef.html#Version
	 * @return ?string
	 */
	function version() {
		return CkAuthAzureSAS_version($this->_cPtr);
	}

	/**
	 * Clears all params set by the methods SetNonTokenParam and SetTokenParam.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkAuthAzureSASRef.html#Clear
	 */
	function Clear() {
		CkAuthAzureSAS_Clear($this->_cPtr);
	}

	/**
	 * Generates and returns the SAS token based on the defined StringToSign and params.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkAuthAzureSASRef.html#GenerateToken
	 * @return ?string
	 */
	function generateToken() {
		return CkAuthAzureSAS_generateToken($this->_cPtr);
	}

	/**
	 * Adds a non-token parameter name/value.  This is a value that is included in the string to sign, but is NOT included in the token query params.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkAuthAzureSASRef.html#SetNonTokenParam
	 * @param ?string $name
	 * @param ?string $value
	 * @return bool
	 */
	function SetNonTokenParam($name,$value) {
		return CkAuthAzureSAS_SetNonTokenParam($this->_cPtr,$name,$value);
	}

	/**
	 * Adds a token parameter name/value.  This is a value that is included in the string to sign, and is also included in the token query params.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkAuthAzureSASRef.html#SetTokenParam
	 * @param ?string $name
	 * @param ?string $authParamName
	 * @param ?string $value
	 * @return bool
	 */
	function SetTokenParam($name,$authParamName,$value) {
		return CkAuthAzureSAS_SetTokenParam($this->_cPtr,$name,$authParamName,$value);
	}
}
