<?php

/* CkBinData.php -- Chilkat PHP extension proxy class CkBinData.
 * Generated by ChilkatApi/GenCkPhp.cs for Chilkat v11.6.1 -- do not edit.
 * Reference documentation: https://www.chilkatsoft.com/refdoc/ */

/**
 * Build, transform, encode, decode, inspect, and save binary data.
 *
 * Chilkat.BinData is a general-purpose mutable byte container used throughout Chilkat for working with binary content in memory. It can load bytes from files, byte arrays, strings, and encoded text; append additional data in many forms; retrieve content as raw bytes, chunks, text, or encoded strings; compute hashes; convert character encodings; validate UTF-8; remove byte ranges; and write the final result to files.
 *
 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html
 */
class CkBinData {
	public $_cPtr=null;
	protected $_pData=array();

	function __set($var,$value) {
		if ($var === 'thisown') return swig_chilkat_alter_newobject($this->_cPtr,$value);
		$this->_pData[$var] = $value;
	}

	function __get($var) {
		if ($var === 'thisown') return swig_chilkat_get_newobject($this->_cPtr);
		return $this->_pData[$var];
	}

	function __isset($var) {
		if ($var === 'thisown') return true;
		return array_key_exists($var, $this->_pData);
	}

	function __construct($res=null) {
		if (is_resource($res) && get_resource_type($res) === '_p_CkBinData') {
			$this->_cPtr=$res;
			return;
		}
		$this->_cPtr=new_CkBinData();
	}

	/**
	 * When true, strings passed to and returned from the object are UTF-8. When false (the default), they are ANSI (the locale's 8-bit character encoding).
	 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html
	 * @return bool
	 */
	function get_Utf8() {
		return CkBinData_get_Utf8($this->_cPtr);
	}

	/**
	 * When true, strings passed to and returned from the object are UTF-8. When false (the default), they are ANSI (the locale's 8-bit character encoding).
	 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html
	 * @param bool $b
	 */
	function put_Utf8($b) {
		CkBinData_put_Utf8($this->_cPtr,$b);
	}

	/**
	 * If set to a file path, this property logs the LastErrorText of each Chilkat method or property call to the specified file. This logging helps identify the context and history of Chilkat calls leading up to any crash or hang, aiding in debugging.  Enabling the VerboseLogging property provides more detailed information.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html#DebugLogFilePath
	 * @param CkString $str
	 */
	function get_DebugLogFilePath($str) {
		CkBinData_get_DebugLogFilePath($this->_cPtr,$str);
	}

	/**
	 * If set to a file path, this property logs the LastErrorText of each Chilkat method or property call to the specified file. This logging helps identify the context and history of Chilkat calls leading up to any crash or hang, aiding in debugging.  Enabling the VerboseLogging property provides more detailed information.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html#DebugLogFilePath
	 * @return ?string
	 */
	function debugLogFilePath() {
		return CkBinData_debugLogFilePath($this->_cPtr);
	}

	/**
	 * If set to a file path, this property logs the LastErrorText of each Chilkat method or property call to the specified file. This logging helps identify the context and history of Chilkat calls leading up to any crash or hang, aiding in debugging.  Enabling the VerboseLogging property provides more detailed information.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html#DebugLogFilePath
	 * @param ?string $newVal
	 */
	function put_DebugLogFilePath($newVal) {
		CkBinData_put_DebugLogFilePath($this->_cPtr,$newVal);
	}

	/**
	 * Provides HTML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html#LastErrorHtml
	 * @param CkString $str
	 */
	function get_LastErrorHtml($str) {
		CkBinData_get_LastErrorHtml($this->_cPtr,$str);
	}

	/**
	 * Provides HTML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html#LastErrorHtml
	 * @return ?string
	 */
	function lastErrorHtml() {
		return CkBinData_lastErrorHtml($this->_cPtr);
	}

	/**
	 * Provides plain text information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html#LastErrorText
	 * @param CkString $str
	 */
	function get_LastErrorText($str) {
		CkBinData_get_LastErrorText($this->_cPtr,$str);
	}

	/**
	 * Provides plain text information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html#LastErrorText
	 * @return ?string
	 */
	function lastErrorText() {
		return CkBinData_lastErrorText($this->_cPtr);
	}

	/**
	 * Provides XML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html#LastErrorXml
	 * @param CkString $str
	 */
	function get_LastErrorXml($str) {
		CkBinData_get_LastErrorXml($this->_cPtr,$str);
	}

	/**
	 * Provides XML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html#LastErrorXml
	 * @return ?string
	 */
	function lastErrorXml() {
		return CkBinData_lastErrorXml($this->_cPtr);
	}

	/**
	 * Indicates the success or failure of the most recent method call: _TRUE_ means success, _FALSE_ means failure. This property remains unchanged by property setters or getters.  This method is present to address challenges in checking for null or Nothing returns in certain programming languages.  Note: This property does not apply to methods that return integer values or to boolean-returning methods where the boolean does not indicate success or failure.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html#LastMethodSuccess
	 * @return bool
	 */
	function get_LastMethodSuccess() {
		return CkBinData_get_LastMethodSuccess($this->_cPtr);
	}

	/**
	 * Indicates the success or failure of the most recent method call: _TRUE_ means success, _FALSE_ means failure. This property remains unchanged by property setters or getters.  This method is present to address challenges in checking for null or Nothing returns in certain programming languages.  Note: This property does not apply to methods that return integer values or to boolean-returning methods where the boolean does not indicate success or failure.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html#LastMethodSuccess
	 * @param bool $newVal
	 */
	function put_LastMethodSuccess($newVal) {
		CkBinData_put_LastMethodSuccess($this->_cPtr,$newVal);
	}

	/**
	 * The number of bytes contained within the object.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html#NumBytes
	 * @return int
	 */
	function get_NumBytes() {
		return CkBinData_get_NumBytes($this->_cPtr);
	}

	/**
	 * If set to _TRUE_, then the contents of LastErrorText (or LastErrorXml, or LastErrorHtml) may contain more verbose information. The default value is _FALSE_.  Verbose logging should only be used for debugging.  The potentially large quantity of logged information may adversely affect peformance.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html#VerboseLogging
	 * @return bool
	 */
	function get_VerboseLogging() {
		return CkBinData_get_VerboseLogging($this->_cPtr);
	}

	/**
	 * If set to _TRUE_, then the contents of LastErrorText (or LastErrorXml, or LastErrorHtml) may contain more verbose information. The default value is _FALSE_.  Verbose logging should only be used for debugging.  The potentially large quantity of logged information may adversely affect peformance.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html#VerboseLogging
	 * @param bool $newVal
	 */
	function put_VerboseLogging($newVal) {
		CkBinData_put_VerboseLogging($this->_cPtr,$newVal);
	}

	/**
	 * Version of the component/library, such as "10.1.0"
	 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html#Version
	 * @param CkString $str
	 */
	function get_Version($str) {
		CkBinData_get_Version($this->_cPtr,$str);
	}

	/**
	 * Version of the component/library, such as "10.1.0"
	 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html#Version
	 * @return ?string
	 */
	function version() {
		return CkBinData_version($this->_cPtr);
	}

	/**
	 * Appends the contents of another BinData to this object.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html#AppendBd
	 * @param CkBinData $binData
	 * @return bool
	 */
	function AppendBd($binData) {
		return CkBinData_AppendBd($this->_cPtr,$binData);
	}

	/**
	 * Appends binary data to the current contents, if any.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html#AppendBinary
	 * @param CkByteData $data
	 * @return bool
	 */
	function AppendBinary($data) {
		return CkBinData_AppendBinary($this->_cPtr,$data);
	}

	/**
	 * Appends the appropriate BOM (byte order mark), also known as a preamble, for the given charset.   If the ARG1 has no defined BOM, then nothing is appended.   An application would typically call this to append the utf-8, utf-16, or utf-32 BOM.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html#AppendBom
	 * @param ?string $charset
	 * @return bool
	 */
	function AppendBom($charset) {
		return CkBinData_AppendBom($this->_cPtr,$charset);
	}

	/**
	 * Appends a single byte.  The ARG1 should be a value from 0 to 255.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html#AppendByte
	 * @param int $byteValue
	 * @return bool
	 */
	function AppendByte($byteValue) {
		return CkBinData_AppendByte($this->_cPtr,$byteValue);
	}

	/**
	 * Appends a byte count followed by the string in the desired character encoding, such as utf-8. The ARG1 is the size in bytes of the integer to represent the byte count.  If 0, then a minimal number of bytes is used.  If ARG2 is _TRUE_, the byte count is appended in big endian byte ordering, otherwise little-ending byte ordering.  The ARG3 is the string to be appended.  The ARG4 is the character encoding, such as utf-8, utf-16, windows-1252, etc.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html#AppendCountedString
	 * @param int $numCountBytes
	 * @param bool $bigEndian
	 * @param ?string $str
	 * @param ?string $charset
	 * @return bool
	 */
	function AppendCountedString($numCountBytes,$bigEndian,$str,$charset) {
		return CkBinData_AppendCountedString($this->_cPtr,$numCountBytes,$bigEndian,$str,$charset);
	}

	/**
	 * Appends binary data to the current contents.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html#AppendData
	 * @param string $data
	 * @param int $numBytes
	 * @return bool
	 */
	function AppendData($data,$numBytes) {
		return CkBinData_AppendData($this->_cPtr,$data,$numBytes);
	}

	/**
	 * Appends encoded binary data to the current data.  The ARG2  may be Base64, modBase64, base64Url, Base32, Base58,  QP (for quoted-printable), URL (for url-encoding), Hex, or any of the encodings found at Chilkat Binary Encodings List.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html#AppendEncoded
	 * @param ?string $encData
	 * @param ?string $encoding
	 * @return bool
	 */
	function AppendEncoded($encData,$encoding) {
		return CkBinData_AppendEncoded($this->_cPtr,$encData,$encoding);
	}

	/**
	 * Decodes the contents of ARG1 and appends the decoded bytes to this object.  The ARG2  may be Base64, modBase64, base64Url, Base32, Base58,  QP (for quoted-printable), URL (for url-encoding), Hex, or any of the encodings found at Chilkat Binary Encodings List.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html#AppendEncodedSb
	 * @param CkStringBuilder $sb
	 * @param ?string $encoding
	 * @return bool
	 */
	function AppendEncodedSb($sb,$encoding) {
		return CkBinData_AppendEncodedSb($this->_cPtr,$sb,$encoding);
	}

	/**
	 * Appends a 16-bit integer (2 bytes).  If ARG2 is _TRUE_, then the integer bytes are appended in little-endian byte order, otherwise big-endian byte order is used.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html#AppendInt2
	 * @param int $value
	 * @param bool $littleEndian
	 * @return bool
	 */
	function AppendInt2($value,$littleEndian) {
		return CkBinData_AppendInt2($this->_cPtr,$value,$littleEndian);
	}

	/**
	 * Appends a 32-bit integer (4 bytes).  If ARG2 is _TRUE_, then the integer bytes are appended in little-endian byte order, otherwise big-endian byte order is used.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html#AppendInt4
	 * @param int $value
	 * @param bool $littleEndian
	 * @return bool
	 */
	function AppendInt4($value,$littleEndian) {
		return CkBinData_AppendInt4($this->_cPtr,$value,$littleEndian);
	}

	/**
	 * Appends a string to this object, padded to the ARG4 with NULL or SPACE chars.   If ARG3 is _TRUE_, then SPACE chars are used and the string is not null-terminated.  If ARG4 is _FALSE_, then null bytes are used.  The ARG2 controls the byte representation to use, such as utf-8.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html#AppendPadded
	 * @param ?string $str
	 * @param ?string $charset
	 * @param bool $padWithSpace
	 * @param int $fieldLen
	 * @return bool
	 */
	function AppendPadded($str,$charset,$padWithSpace,$fieldLen) {
		return CkBinData_AppendPadded($this->_cPtr,$str,$charset,$padWithSpace,$fieldLen);
	}

	/**
	 * Appends the contents of a StringBuilder to this object.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html#AppendSb
	 * @param CkStringBuilder $sb
	 * @param ?string $charset
	 * @return bool
	 */
	function AppendSb($sb,$charset) {
		return CkBinData_AppendSb($this->_cPtr,$sb,$charset);
	}

	/**
	 * Appends a string to this object.  (This does not append the BOM.  If a BOM is required, the AppendBom method can be called to append the appropriate BOM.)
	 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html#AppendString
	 * @param ?string $str
	 * @param ?string $charset
	 * @return bool
	 */
	function AppendString($str,$charset) {
		return CkBinData_AppendString($this->_cPtr,$str,$charset);
	}

	/**
	 * Does either 16-bit or 32-bit byte swapping of the entire contents.  If ARG1 equals 16, then swaps in 2 bytes (e.g., 0x1234 → 0x3412).  If ARG1 equals 32, then swaps 4 bytes (e.g., 0x12345678 → 0x78563412)
	 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html#ByteSwap
	 * @param int $size
	 */
	function ByteSwap($size) {
		CkBinData_ByteSwap($this->_cPtr,$size);
	}

	/**
	 * This method converts the character encoding of an object's contents from one format to another, such as from Windows-1252 to UTF-8. The ARG3 parameter determines error handling for unrepresentable bytes. If ARG3 is _TRUE_, the object's contents remain unchanged when errors occur. If _FALSE_, error bytes are discarded. The method returns _TRUE_ if successful and _FALSE_ if errors occur.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html#CharsetConvert
	 * @param ?string $fromCharset
	 * @param ?string $toCharset
	 * @param bool $allOrNone
	 * @return bool
	 */
	function CharsetConvert($fromCharset,$toCharset,$allOrNone) {
		return CkBinData_CharsetConvert($this->_cPtr,$fromCharset,$toCharset,$allOrNone);
	}

	/**
	 * Clears the contents.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html#Clear
	 * @return bool
	 */
	function Clear() {
		return CkBinData_Clear($this->_cPtr);
	}

	/**
	 * Return _TRUE_ if the contents of this object equals the contents of ARG1.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html#ContentsEqual
	 * @param CkBinData $binData
	 * @return bool
	 */
	function ContentsEqual($binData) {
		return CkBinData_ContentsEqual($this->_cPtr,$binData);
	}

	/**
	 * Return the index where the first occurrence of ARG1 is found.  Return -1 if not found.  The ARG2 indicates the byte index where the search begins.  The ARG3 specifies the byte representation of ARG1 that is to be searched.  For example, it can be utf-8, windows-1252, ansi, utf-16, etc.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html#FindString
	 * @param ?string $str
	 * @param int $startIdx
	 * @param ?string $charset
	 * @return int
	 */
	function FindString($str,$startIdx,$charset) {
		return CkBinData_FindString($this->_cPtr,$str,$startIdx,$charset);
	}

	/**
	 * Retrieves the binary data contained within the object.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html#GetBinary
	 * @param CkByteData $outBytes
	 * @return bool
	 */
	function GetBinary($outBytes) {
		return CkBinData_GetBinary($this->_cPtr,$outBytes);
	}

	/**
	 * Retrieves a chunk of the binary data contained within the object.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html#GetBinaryChunk
	 * @param int $offset
	 * @param int $numBytes
	 * @param CkByteData $outBytes
	 * @return bool
	 */
	function GetBinaryChunk($offset,$numBytes,$outBytes) {
		return CkBinData_GetBinaryChunk($this->_cPtr,$offset,$numBytes,$outBytes);
	}

	/**
	 * Returns the value of the byte at the given ARG1.  The returned value is an integer from 0 to 255.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html#GetByte
	 * @param int $index
	 * @return int
	 */
	function GetByte($index) {
		return CkBinData_GetByte($this->_cPtr,$index);
	}

	/**
	 * Retrieves the binary data contained within the object.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html#GetData
	 * @return string
	 */
	function GetData() {
		return CkBinData_GetData($this->_cPtr);
	}

	/**
	 * Retrieves a chunk of the binary data contained within the object.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html#GetDataChunk
	 * @param int $offset
	 * @param int $numBytes
	 * @return string
	 */
	function GetDataChunk($offset,$numBytes) {
		return CkBinData_GetDataChunk($this->_cPtr,$offset,$numBytes);
	}

	/**
	 * Retrieves the binary data as an encoded string.   The ARG1  may be Base64, modBase64, base64Url, Base32, Base58,  QP (for quoted-printable), URL (for url-encoding), Hex, or any of the encodings found at Chilkat Binary Encodings List.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html#GetEncoded
	 * @param ?string $encoding
	 * @return ?string
	 */
	function getEncoded($encoding) {
		return CkBinData_getEncoded($this->_cPtr,$encoding);
	}

	/**
	 * Retrieves the binary data as an encoded string.   The ARG1  may be Base64, modBase64, base64Url, Base32, Base58,  QP (for quoted-printable), URL (for url-encoding), Hex, or any of the encodings found at Chilkat Binary Encodings List.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html#GetEncoded
	 * @param ?string $encoding
	 * @return ?string
	 */
	function encoded($encoding) {
		return CkBinData_encoded($this->_cPtr,$encoding);
	}

	/**
	 * Retrieves a chunk of the binary data and returns it in encoded form. The ARG3  may be Base64, modBase64, base64Url, Base32, Base58,  QP (for quoted-printable), URL (for url-encoding), Hex, or any of the encodings found at Chilkat Binary Encodings List.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html#GetEncodedChunk
	 * @param int $offset
	 * @param int $numBytes
	 * @param ?string $encoding
	 * @return ?string
	 */
	function getEncodedChunk($offset,$numBytes,$encoding) {
		return CkBinData_getEncodedChunk($this->_cPtr,$offset,$numBytes,$encoding);
	}

	/**
	 * Retrieves a chunk of the binary data and returns it in encoded form. The ARG3  may be Base64, modBase64, base64Url, Base32, Base58,  QP (for quoted-printable), URL (for url-encoding), Hex, or any of the encodings found at Chilkat Binary Encodings List.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html#GetEncodedChunk
	 * @param int $offset
	 * @param int $numBytes
	 * @param ?string $encoding
	 * @return ?string
	 */
	function encodedChunk($offset,$numBytes,$encoding) {
		return CkBinData_encodedChunk($this->_cPtr,$offset,$numBytes,$encoding);
	}

	/**
	 * Writes the encoded data to a StringBuilder.   The ARG1  may be Base64, modBase64, base64Url, Base32, Base58,  QP (for quoted-printable), URL (for url-encoding), Hex, or any of the encodings found at Chilkat Binary Encodings List.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html#GetEncodedSb
	 * @param ?string $encoding
	 * @param CkStringBuilder $sb
	 * @return bool
	 */
	function GetEncodedSb($encoding,$sb) {
		return CkBinData_GetEncodedSb($this->_cPtr,$encoding,$sb);
	}

	/**
	 * Returns the hash of the contents of this object.  The ARG1 is the hash algorithm, and can be sha1, sha256, sha384, sha512, sha3-224, sha3-256, sha3-384, sha3-512, md2, md5, ripemd128, ripemd160,ripemd256, or ripemd320.   The ARG2  can be base64, modBase64, base64Url, base32, base58,  qp (for quoted-printable), url (for url-encoding), hex, hexLower, or any of the encodings found at Chilkat Binary Encodings List.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html#GetHash
	 * @param ?string $algorithm
	 * @param ?string $encoding
	 * @return ?string
	 */
	function getHash($algorithm,$encoding) {
		return CkBinData_getHash($this->_cPtr,$algorithm,$encoding);
	}

	/**
	 * Returns the hash of the contents of this object.  The ARG1 is the hash algorithm, and can be sha1, sha256, sha384, sha512, sha3-224, sha3-256, sha3-384, sha3-512, md2, md5, ripemd128, ripemd160,ripemd256, or ripemd320.   The ARG2  can be base64, modBase64, base64Url, base32, base58,  qp (for quoted-printable), url (for url-encoding), hex, hexLower, or any of the encodings found at Chilkat Binary Encodings List.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html#GetHash
	 * @param ?string $algorithm
	 * @param ?string $encoding
	 * @return ?string
	 */
	function hash($algorithm,$encoding) {
		return CkBinData_hash($this->_cPtr,$algorithm,$encoding);
	}

	/**
	 * Returns the value of the 16-bit signed integer stored in big-endian or little-endian byte ordering at the given index.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html#GetInt2
	 * @param int $index
	 * @param bool $littleEndian
	 * @return int
	 */
	function GetInt2($index,$littleEndian) {
		return CkBinData_GetInt2($this->_cPtr,$index,$littleEndian);
	}

	/**
	 * Returns the value of the 32-bit signed integer stored in big-endian or little-endian byte ordering at the given index.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html#GetInt4
	 * @param int $index
	 * @param bool $littleEndian
	 * @return int
	 */
	function GetInt4($index,$littleEndian) {
		return CkBinData_GetInt4($this->_cPtr,$index,$littleEndian);
	}

	/**
	 * Interprets the bytes according to ARG1 and returns the string.   The ARG1 can be utf-8, utf-16, ansi, iso-8859-*, windows-125*, or any of the supported character encodings listed in the link below.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html#GetString
	 * @param ?string $charset
	 * @return ?string
	 */
	function getString($charset) {
		return CkBinData_getString($this->_cPtr,$charset);
	}

	/**
	 * Interprets the bytes according to ARG1 and returns the string.   The ARG1 can be utf-8, utf-16, ansi, iso-8859-*, windows-125*, or any of the supported character encodings listed in the link below.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html#GetString
	 * @param ?string $charset
	 * @return ?string
	 */
	function string($charset) {
		return CkBinData_string($this->_cPtr,$charset);
	}

	/**
	 * Returns ARG2 bytes starting at ARG1.  The bytes are interpreted according to ARG3 (for example, utf-8, ansi, utf-16, windows-1252, etc.)
	 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html#GetTextChunk
	 * @param int $startIdx
	 * @param int $numBytes
	 * @param ?string $charset
	 * @return ?string
	 */
	function getTextChunk($startIdx,$numBytes,$charset) {
		return CkBinData_getTextChunk($this->_cPtr,$startIdx,$numBytes,$charset);
	}

	/**
	 * Returns ARG2 bytes starting at ARG1.  The bytes are interpreted according to ARG3 (for example, utf-8, ansi, utf-16, windows-1252, etc.)
	 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html#GetTextChunk
	 * @param int $startIdx
	 * @param int $numBytes
	 * @param ?string $charset
	 * @return ?string
	 */
	function textChunk($startIdx,$numBytes,$charset) {
		return CkBinData_textChunk($this->_cPtr,$startIdx,$numBytes,$charset);
	}

	/**
	 * Returns the value of the 16-bit unsigned integer stored in big-endian or little-endian byte ordering at the given index.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html#GetUInt2
	 * @param int $index
	 * @param bool $littleEndian
	 * @return int
	 */
	function GetUInt2($index,$littleEndian) {
		return CkBinData_GetUInt2($this->_cPtr,$index,$littleEndian);
	}

	/**
	 * Returns the value of the 32-bit unsigned integer stored in big-endian or little-endian byte ordering at the given index.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html#GetUInt4
	 * @param int $index
	 * @param bool $littleEndian
	 * @return int
	 */
	function GetUInt4($index,$littleEndian) {
		return CkBinData_GetUInt4($this->_cPtr,$index,$littleEndian);
	}

	/**
	 * Returns _TRUE_ if this object contains valid utf-8 byte sequences.  Any invalid byte sequence that is not valid utf-8 will cause this function to return _FALSE_.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html#IsValidUtf8
	 * @return bool
	 */
	function IsValidUtf8() {
		return CkBinData_IsValidUtf8($this->_cPtr);
	}

	/**
	 * Loads binary data and replaces the current contents, if any.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html#LoadBinary
	 * @param CkByteData $data
	 * @return bool
	 */
	function LoadBinary($data) {
		return CkBinData_LoadBinary($this->_cPtr,$data);
	}

	/**
	 * Loads binary data from an encoded string, replacing the current contents, if any.  The ARG2 may be Base64, modBase64, base64Url, Base32, Base58,  QP (for quoted-printable), URL (for url-encoding), Hex, or any of the encodings found at Chilkat Binary Encodings List.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html#LoadEncoded
	 * @param ?string $encData
	 * @param ?string $encoding
	 * @return bool
	 */
	function LoadEncoded($encData,$encoding) {
		return CkBinData_LoadEncoded($this->_cPtr,$encData,$encoding);
	}

	/**
	 * Loads data from a file.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html#LoadFile
	 * @param ?string $path
	 * @return bool
	 */
	function LoadFile($path) {
		return CkBinData_LoadFile($this->_cPtr,$path);
	}

	/**
	 * Removes bytes having a specified value (0-255).  For example, to remove all null bytes, pass 0 in ARG1.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html#RemoveByteVal
	 * @param int $value
	 */
	function RemoveByteVal($value) {
		CkBinData_RemoveByteVal($this->_cPtr,$value);
	}

	/**
	 * Removes a chunk of bytes from the binary data.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html#RemoveChunk
	 * @param int $offset
	 * @param int $numBytes
	 * @return bool
	 */
	function RemoveChunk($offset,$numBytes) {
		return CkBinData_RemoveChunk($this->_cPtr,$offset,$numBytes);
	}

	/**
	 * Securely clears the contents by writing 0 bytes to the memory prior to deallocating the internal memory.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html#SecureClear
	 * @return bool
	 */
	function SecureClear() {
		return CkBinData_SecureClear($this->_cPtr);
	}

	/**
	 * Appends the contents of this object to a file.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html#WriteAppendFile
	 * @param ?string $path
	 * @return bool
	 */
	function WriteAppendFile($path) {
		return CkBinData_WriteAppendFile($this->_cPtr,$path);
	}

	/**
	 * Writes the contents to a file.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkBinDataRef.html#WriteFile
	 * @param ?string $path
	 * @return bool
	 */
	function WriteFile($path) {
		return CkBinData_WriteFile($this->_cPtr,$path);
	}
}
