<?php

/* CkByteData.php -- Chilkat PHP extension proxy class CkByteData.
 * Generated by ChilkatApi/GenCkPhp.cs for Chilkat v11.6.1 -- do not edit.
 * Reference documentation: https://www.chilkatsoft.com/refdoc/ */

/**
 * @see https://www.chilkatsoft.com/refdoc/phpCkByteDataRef.html
 */
class CkByteData {
	public $_cPtr=null;
	protected $_pData=array();

	function __set($var,$value) {
		if ($var === 'thisown') return swig_chilkat_alter_newobject($this->_cPtr,$value);
		$this->_pData[$var] = $value;
	}

	function __get($var) {
		if ($var === 'thisown') return swig_chilkat_get_newobject($this->_cPtr);
		return $this->_pData[$var];
	}

	function __isset($var) {
		if ($var === 'thisown') return true;
		return array_key_exists($var, $this->_pData);
	}

	function __construct($res=null) {
		if (is_resource($res) && get_resource_type($res) === '_p_CkByteData') {
			$this->_cPtr=$res;
			return;
		}
		$this->_cPtr=new_CkByteData();
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkByteDataRef.html
	 * @return bool
	 */
	function get_Utf8() {
		return CkByteData_get_Utf8($this->_cPtr);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkByteDataRef.html
	 * @param bool $b
	 */
	function put_Utf8($b) {
		CkByteData_put_Utf8($this->_cPtr,$b);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkByteDataRef.html
	 * @return ?string
	 */
	function to_s() {
		return CkByteData_to_s($this->_cPtr);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkByteDataRef.html
	 * @param int $numBytes
	 */
	function appendRandom($numBytes) {
		CkByteData_appendRandom($this->_cPtr,$numBytes);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkByteDataRef.html
	 * @param int $v
	 * @param bool $littleEndian
	 */
	function appendInt($v,$littleEndian) {
		CkByteData_appendInt($this->_cPtr,$v,$littleEndian);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkByteDataRef.html
	 * @param int $v
	 * @param bool $littleEndian
	 */
	function appendShort($v,$littleEndian) {
		CkByteData_appendShort($this->_cPtr,$v,$littleEndian);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkByteDataRef.html
	 * @param ?string $encoding
	 * @param int $index
	 * @param int $numBytes
	 * @return ?string
	 */
	function getEncodedRange($encoding,$index,$numBytes) {
		return CkByteData_getEncodedRange($this->_cPtr,$encoding,$index,$numBytes);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkByteDataRef.html
	 * @param CkByteData $byteData
	 * @param int $index
	 * @param int $numBytes
	 */
	function appendRange($byteData,$index,$numBytes) {
		CkByteData_appendRange($this->_cPtr,$byteData,$index,$numBytes);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkByteDataRef.html
	 * @param int $numBytes
	 * @return bool
	 */
	function ensureBuffer($numBytes) {
		return CkByteData_ensureBuffer($this->_cPtr,$numBytes);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkByteDataRef.html
	 * @param ?string $byteData
	 * @param int $byteDataLen
	 * @return int
	 */
	function findBytes2($byteData,$byteDataLen) {
		return CkByteData_findBytes2($this->_cPtr,$byteData,$byteDataLen);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkByteDataRef.html
	 * @param CkByteData $byteData
	 * @return int
	 */
	function findBytes($byteData) {
		return CkByteData_findBytes($this->_cPtr,$byteData);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkByteDataRef.html
	 * @param ?string $byteData
	 * @param int $byteDataLen
	 * @return bool
	 */
	function beginsWith2($byteData,$byteDataLen) {
		return CkByteData_beginsWith2($this->_cPtr,$byteData,$byteDataLen);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkByteDataRef.html
	 * @param CkByteData $byteData
	 * @return bool
	 */
	function beginsWith($byteData) {
		return CkByteData_beginsWith($this->_cPtr,$byteData);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkByteDataRef.html
	 * @param int $index
	 * @param int $numBytes
	 */
	function removeChunk($index,$numBytes) {
		CkByteData_removeChunk($this->_cPtr,$index,$numBytes);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkByteDataRef.html
	 */
	function byteSwap4321() {
		CkByteData_byteSwap4321($this->_cPtr);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkByteDataRef.html
	 * @param int $blockSize
	 * @param int $paddingScheme
	 */
	function pad($blockSize,$paddingScheme) {
		CkByteData_pad($this->_cPtr,$blockSize,$paddingScheme);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkByteDataRef.html
	 * @param int $blockSize
	 * @param int $paddingScheme
	 */
	function unpad($blockSize,$paddingScheme) {
		CkByteData_unpad($this->_cPtr,$blockSize,$paddingScheme);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkByteDataRef.html
	 * @return bool
	 */
	function is7bit() {
		return CkByteData_is7bit($this->_cPtr);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkByteDataRef.html
	 */
	function clear() {
		CkByteData_clear($this->_cPtr);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkByteDataRef.html
	 * @return int
	 */
	function getSize() {
		return CkByteData_getSize($this->_cPtr);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkByteDataRef.html
	 * @param ?string $str
	 * @param ?string $encoding
	 */
	function appendEncoded($str,$encoding) {
		CkByteData_appendEncoded($this->_cPtr,$str,$encoding);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkByteDataRef.html
	 * @param ?string $encoding
	 * @param CkString $str
	 */
	function encode($encoding,$str) {
		CkByteData_encode($this->_cPtr,$encoding,$str);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkByteDataRef.html
	 * @return string
	 */
	function getData() {
		return CkByteData_getData($this->_cPtr);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkByteDataRef.html
	 * @return string
	 */
	function getBytes() {
		return CkByteData_getBytes($this->_cPtr);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkByteDataRef.html
	 * @param ?string $encoding
	 * @return ?string
	 */
	function getEncoded($encoding) {
		return CkByteData_getEncoded($this->_cPtr,$encoding);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkByteDataRef.html
	 * @param int $index
	 * @param int $numBytes
	 * @return string
	 */
	function getRange($index,$numBytes) {
		return CkByteData_getRange($this->_cPtr,$index,$numBytes);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkByteDataRef.html
	 * @param int $index
	 * @param int $numAnsiChars
	 * @return ?string
	 */
	function getRangeStr($index,$numAnsiChars) {
		return CkByteData_getRangeStr($this->_cPtr,$index,$numAnsiChars);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkByteDataRef.html
	 * @param ?string $data
	 * @param int $numBytes
	 */
	function append2($data,$numBytes) {
		CkByteData_append2($this->_cPtr,$data,$numBytes);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkByteDataRef.html
	 * @param ?string $data
	 * @param int $numBytes
	 * @return bool
	 */
	function equals2($data,$numBytes) {
		return CkByteData_equals2($this->_cPtr,$data,$numBytes);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkByteDataRef.html
	 * @param CkByteData $db
	 * @return bool
	 */
	function equals($db) {
		return CkByteData_equals($this->_cPtr,$db);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkByteDataRef.html
	 * @param ?string $str
	 */
	function appendStr($str) {
		CkByteData_appendStr($this->_cPtr,$str);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkByteDataRef.html
	 * @param string $ch
	 */
	function appendChar($ch) {
		CkByteData_appendChar($this->_cPtr,$ch);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkByteDataRef.html
	 * @param int $byteIndex
	 * @return int
	 */
	function getByte($byteIndex) {
		return CkByteData_getByte($this->_cPtr,$byteIndex);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkByteDataRef.html
	 * @param int $byteIndex
	 * @return string
	 */
	function getChar($byteIndex) {
		return CkByteData_getChar($this->_cPtr,$byteIndex);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkByteDataRef.html
	 * @param int $byteIndex
	 * @return int
	 */
	function getUInt($byteIndex) {
		return CkByteData_getUInt($this->_cPtr,$byteIndex);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkByteDataRef.html
	 * @param int $byteIndex
	 * @return int
	 */
	function getInt($byteIndex) {
		return CkByteData_getInt($this->_cPtr,$byteIndex);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkByteDataRef.html
	 * @param int $byteIndex
	 * @return int
	 */
	function getUShort($byteIndex) {
		return CkByteData_getUShort($this->_cPtr,$byteIndex);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkByteDataRef.html
	 * @param int $byteIndex
	 * @return int
	 */
	function getShort($byteIndex) {
		return CkByteData_getShort($this->_cPtr,$byteIndex);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkByteDataRef.html
	 * @param ?string $filename
	 * @return bool
	 */
	function loadFile($filename) {
		return CkByteData_loadFile($this->_cPtr,$filename);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkByteDataRef.html
	 * @param ?string $filename
	 * @return bool
	 */
	function saveFile($filename) {
		return CkByteData_saveFile($this->_cPtr,$filename);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkByteDataRef.html
	 * @param ?string $filename
	 * @return bool
	 */
	function appendFile($filename) {
		return CkByteData_appendFile($this->_cPtr,$filename);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkByteDataRef.html
	 * @param int $numBytes
	 */
	function shorten($numBytes) {
		CkByteData_shorten($this->_cPtr,$numBytes);
	}
}
