<?php

/* CkCharset.php -- Chilkat PHP extension proxy class CkCharset.
 * Generated by ChilkatApi/GenCkPhp.cs for Chilkat v11.6.1 -- do not edit.
 * Reference documentation: https://www.chilkatsoft.com/refdoc/ */

/**
 * Deprecated — scheduled for removal
 *
 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html
 */
class CkCharset {
	public $_cPtr=null;
	protected $_pData=array();

	function __set($var,$value) {
		if ($var === 'thisown') return swig_chilkat_alter_newobject($this->_cPtr,$value);
		$this->_pData[$var] = $value;
	}

	function __get($var) {
		if ($var === 'thisown') return swig_chilkat_get_newobject($this->_cPtr);
		return $this->_pData[$var];
	}

	function __isset($var) {
		if ($var === 'thisown') return true;
		return array_key_exists($var, $this->_pData);
	}

	function __construct($res=null) {
		if (is_resource($res) && get_resource_type($res) === '_p_CkCharset') {
			$this->_cPtr=$res;
			return;
		}
		$this->_cPtr=new_CkCharset();
	}

	/**
	 * When true, strings passed to and returned from the object are UTF-8. When false (the default), they are ANSI (the locale's 8-bit character encoding).
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html
	 * @return bool
	 */
	function get_Utf8() {
		return CkCharset_get_Utf8($this->_cPtr);
	}

	/**
	 * When true, strings passed to and returned from the object are UTF-8. When false (the default), they are ANSI (the locale's 8-bit character encoding).
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html
	 * @param bool $b
	 */
	function put_Utf8($b) {
		CkCharset_put_Utf8($this->_cPtr,$b);
	}

	/**
	 * Specifies the alternate destination character encoding used only when ErrorAction is 6. If a decoded input character cannot be represented in ToCharset, Chilkat attempts to encode that character using this alternate charset. If the alternate conversion also fails, the character is omitted from the output. Mixed-encoding output: The result can contain a mixture of byte encodings. Such output is usually unsuitable for interchange unless the receiving format explicitly supports this behavior.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#AltToCharset
	 * @param CkString $str
	 */
	function get_AltToCharset($str) {
		CkCharset_get_AltToCharset($this->_cPtr,$str);
	}

	/**
	 * Specifies the alternate destination character encoding used only when ErrorAction is 6. If a decoded input character cannot be represented in ToCharset, Chilkat attempts to encode that character using this alternate charset. If the alternate conversion also fails, the character is omitted from the output. Mixed-encoding output: The result can contain a mixture of byte encodings. Such output is usually unsuitable for interchange unless the receiving format explicitly supports this behavior.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#AltToCharset
	 * @return ?string
	 */
	function altToCharset() {
		return CkCharset_altToCharset($this->_cPtr);
	}

	/**
	 * Specifies the alternate destination character encoding used only when ErrorAction is 6. If a decoded input character cannot be represented in ToCharset, Chilkat attempts to encode that character using this alternate charset. If the alternate conversion also fails, the character is omitted from the output. Mixed-encoding output: The result can contain a mixture of byte encodings. Such output is usually unsuitable for interchange unless the receiving format explicitly supports this behavior.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#AltToCharset
	 * @param ?string $newVal
	 */
	function put_AltToCharset($newVal) {
		CkCharset_put_AltToCharset($this->_cPtr,$newVal);
	}

	/**
	 * If set to a file path, this property logs the LastErrorText of each Chilkat method or property call to the specified file. This logging helps identify the context and history of Chilkat calls leading up to any crash or hang, aiding in debugging.  Enabling the VerboseLogging property provides more detailed information.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#DebugLogFilePath
	 * @param CkString $str
	 */
	function get_DebugLogFilePath($str) {
		CkCharset_get_DebugLogFilePath($this->_cPtr,$str);
	}

	/**
	 * If set to a file path, this property logs the LastErrorText of each Chilkat method or property call to the specified file. This logging helps identify the context and history of Chilkat calls leading up to any crash or hang, aiding in debugging.  Enabling the VerboseLogging property provides more detailed information.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#DebugLogFilePath
	 * @return ?string
	 */
	function debugLogFilePath() {
		return CkCharset_debugLogFilePath($this->_cPtr);
	}

	/**
	 * If set to a file path, this property logs the LastErrorText of each Chilkat method or property call to the specified file. This logging helps identify the context and history of Chilkat calls leading up to any crash or hang, aiding in debugging.  Enabling the VerboseLogging property provides more detailed information.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#DebugLogFilePath
	 * @param ?string $newVal
	 */
	function put_DebugLogFilePath($newVal) {
		CkCharset_put_DebugLogFilePath($this->_cPtr,$newVal);
	}

	/**
	 * Controls what happens when an input character has been decoded successfully but cannot be represented in the destination charset. ValueAction 0Drop the unrepresentable character. 1Insert the replacement configured by SetErrorString. 2Emit a hexadecimal numeric character reference such as &#x20AC;. 3–5Reserved. Do not use. 6Encode the character using AltToCharset; drop it if that also fails. 7Pass the nonconvertible data through unchanged. Data-integrity warning: Values 0, 6, and 7 can silently lose data or produce output that is not valid in the declared destination charset. For new code, prefer an explicit failure or replacement policy in the replacement API.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#ErrorAction
	 * @return int
	 */
	function get_ErrorAction() {
		return CkCharset_get_ErrorAction($this->_cPtr);
	}

	/**
	 * Controls what happens when an input character has been decoded successfully but cannot be represented in the destination charset. ValueAction 0Drop the unrepresentable character. 1Insert the replacement configured by SetErrorString. 2Emit a hexadecimal numeric character reference such as &#x20AC;. 3–5Reserved. Do not use. 6Encode the character using AltToCharset; drop it if that also fails. 7Pass the nonconvertible data through unchanged. Data-integrity warning: Values 0, 6, and 7 can silently lose data or produce output that is not valid in the declared destination charset. For new code, prefer an explicit failure or replacement policy in the replacement API.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#ErrorAction
	 * @param int $newVal
	 */
	function put_ErrorAction($newVal) {
		CkCharset_put_ErrorAction($this->_cPtr,$newVal);
	}

	/**
	 * Specifies the character encoding of the input bytes for conversion operations. Chilkat decodes the source bytes using this charset before encoding the resulting Unicode text using ToCharset.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#FromCharset
	 * @param CkString $str
	 */
	function get_FromCharset($str) {
		CkCharset_get_FromCharset($this->_cPtr,$str);
	}

	/**
	 * Specifies the character encoding of the input bytes for conversion operations. Chilkat decodes the source bytes using this charset before encoding the resulting Unicode text using ToCharset.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#FromCharset
	 * @return ?string
	 */
	function fromCharset() {
		return CkCharset_fromCharset($this->_cPtr);
	}

	/**
	 * Specifies the character encoding of the input bytes for conversion operations. Chilkat decodes the source bytes using this charset before encoding the resulting Unicode text using ToCharset.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#FromCharset
	 * @param ?string $newVal
	 */
	function put_FromCharset($newVal) {
		CkCharset_put_FromCharset($this->_cPtr,$newVal);
	}

	/**
	 * Provides HTML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#LastErrorHtml
	 * @param CkString $str
	 */
	function get_LastErrorHtml($str) {
		CkCharset_get_LastErrorHtml($this->_cPtr,$str);
	}

	/**
	 * Provides HTML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#LastErrorHtml
	 * @return ?string
	 */
	function lastErrorHtml() {
		return CkCharset_lastErrorHtml($this->_cPtr);
	}

	/**
	 * Provides plain text information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#LastErrorText
	 * @param CkString $str
	 */
	function get_LastErrorText($str) {
		CkCharset_get_LastErrorText($this->_cPtr,$str);
	}

	/**
	 * Provides plain text information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#LastErrorText
	 * @return ?string
	 */
	function lastErrorText() {
		return CkCharset_lastErrorText($this->_cPtr);
	}

	/**
	 * Provides XML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#LastErrorXml
	 * @param CkString $str
	 */
	function get_LastErrorXml($str) {
		CkCharset_get_LastErrorXml($this->_cPtr,$str);
	}

	/**
	 * Provides XML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#LastErrorXml
	 * @return ?string
	 */
	function lastErrorXml() {
		return CkCharset_lastErrorXml($this->_cPtr);
	}

	/**
	 * Returns the input bytes captured for the most recent conversion performed while SaveLast was enabled, represented as hexadecimal text. Diagnostic snapshot: This is a diagnostic representation of the raw bytes. It does not perform another charset conversion, and the quoted-printable form is intended to make otherwise nonprintable bytes easier to inspect.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#LastInputAsHex
	 * @param CkString $str
	 */
	function get_LastInputAsHex($str) {
		CkCharset_get_LastInputAsHex($this->_cPtr,$str);
	}

	/**
	 * Returns the input bytes captured for the most recent conversion performed while SaveLast was enabled, represented as hexadecimal text. Diagnostic snapshot: This is a diagnostic representation of the raw bytes. It does not perform another charset conversion, and the quoted-printable form is intended to make otherwise nonprintable bytes easier to inspect.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#LastInputAsHex
	 * @return ?string
	 */
	function lastInputAsHex() {
		return CkCharset_lastInputAsHex($this->_cPtr);
	}

	/**
	 * Returns the input bytes captured for the most recent conversion performed while SaveLast was enabled, represented as quoted-printable text. Diagnostic snapshot: This is a diagnostic representation of the raw bytes. It does not perform another charset conversion, and the quoted-printable form is intended to make otherwise nonprintable bytes easier to inspect.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#LastInputAsQP
	 * @param CkString $str
	 */
	function get_LastInputAsQP($str) {
		CkCharset_get_LastInputAsQP($this->_cPtr,$str);
	}

	/**
	 * Returns the input bytes captured for the most recent conversion performed while SaveLast was enabled, represented as quoted-printable text. Diagnostic snapshot: This is a diagnostic representation of the raw bytes. It does not perform another charset conversion, and the quoted-printable form is intended to make otherwise nonprintable bytes easier to inspect.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#LastInputAsQP
	 * @return ?string
	 */
	function lastInputAsQP() {
		return CkCharset_lastInputAsQP($this->_cPtr);
	}

	/**
	 * Indicates the success or failure of the most recent method call: _TRUE_ means success, _FALSE_ means failure. This property remains unchanged by property setters or getters.  This method is present to address challenges in checking for null or Nothing returns in certain programming languages.  Note: This property does not apply to methods that return integer values or to boolean-returning methods where the boolean does not indicate success or failure.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#LastMethodSuccess
	 * @return bool
	 */
	function get_LastMethodSuccess() {
		return CkCharset_get_LastMethodSuccess($this->_cPtr);
	}

	/**
	 * Indicates the success or failure of the most recent method call: _TRUE_ means success, _FALSE_ means failure. This property remains unchanged by property setters or getters.  This method is present to address challenges in checking for null or Nothing returns in certain programming languages.  Note: This property does not apply to methods that return integer values or to boolean-returning methods where the boolean does not indicate success or failure.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#LastMethodSuccess
	 * @param bool $newVal
	 */
	function put_LastMethodSuccess($newVal) {
		CkCharset_put_LastMethodSuccess($this->_cPtr,$newVal);
	}

	/**
	 * Returns the output bytes captured for the most recent conversion performed while SaveLast was enabled, represented as hexadecimal text. Diagnostic snapshot: This is a diagnostic representation of the raw bytes. It does not perform another charset conversion, and the quoted-printable form is intended to make otherwise nonprintable bytes easier to inspect.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#LastOutputAsHex
	 * @param CkString $str
	 */
	function get_LastOutputAsHex($str) {
		CkCharset_get_LastOutputAsHex($this->_cPtr,$str);
	}

	/**
	 * Returns the output bytes captured for the most recent conversion performed while SaveLast was enabled, represented as hexadecimal text. Diagnostic snapshot: This is a diagnostic representation of the raw bytes. It does not perform another charset conversion, and the quoted-printable form is intended to make otherwise nonprintable bytes easier to inspect.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#LastOutputAsHex
	 * @return ?string
	 */
	function lastOutputAsHex() {
		return CkCharset_lastOutputAsHex($this->_cPtr);
	}

	/**
	 * Returns the output bytes captured for the most recent conversion performed while SaveLast was enabled, represented as quoted-printable text. Diagnostic snapshot: This is a diagnostic representation of the raw bytes. It does not perform another charset conversion, and the quoted-printable form is intended to make otherwise nonprintable bytes easier to inspect.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#LastOutputAsQP
	 * @param CkString $str
	 */
	function get_LastOutputAsQP($str) {
		CkCharset_get_LastOutputAsQP($this->_cPtr,$str);
	}

	/**
	 * Returns the output bytes captured for the most recent conversion performed while SaveLast was enabled, represented as quoted-printable text. Diagnostic snapshot: This is a diagnostic representation of the raw bytes. It does not perform another charset conversion, and the quoted-printable form is intended to make otherwise nonprintable bytes easier to inspect.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#LastOutputAsQP
	 * @return ?string
	 */
	function lastOutputAsQP() {
		return CkCharset_lastOutputAsQP($this->_cPtr);
	}

	/**
	 * When _TRUE_, retains the input and output byte sequences from each conversion so they can be inspected through LastInputAsHex, LastInputAsQP, LastOutputAsHex, and LastOutputAsQP. Debugging only: Enable this only while troubleshooting. Retaining both sides of a large conversion increases memory use and may keep sensitive plaintext in memory longer than necessary.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#SaveLast
	 * @return bool
	 */
	function get_SaveLast() {
		return CkCharset_get_SaveLast($this->_cPtr);
	}

	/**
	 * When _TRUE_, retains the input and output byte sequences from each conversion so they can be inspected through LastInputAsHex, LastInputAsQP, LastOutputAsHex, and LastOutputAsQP. Debugging only: Enable this only while troubleshooting. Retaining both sides of a large conversion increases memory use and may keep sensitive plaintext in memory longer than necessary.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#SaveLast
	 * @param bool $newVal
	 */
	function put_SaveLast($newVal) {
		CkCharset_put_SaveLast($this->_cPtr,$newVal);
	}

	/**
	 * Specifies the destination character encoding for conversion operations. After decoding the source bytes using FromCharset, Chilkat encodes the resulting Unicode text in this charset.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#ToCharset
	 * @param CkString $str
	 */
	function get_ToCharset($str) {
		CkCharset_get_ToCharset($this->_cPtr,$str);
	}

	/**
	 * Specifies the destination character encoding for conversion operations. After decoding the source bytes using FromCharset, Chilkat encodes the resulting Unicode text in this charset.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#ToCharset
	 * @return ?string
	 */
	function toCharset() {
		return CkCharset_toCharset($this->_cPtr);
	}

	/**
	 * Specifies the destination character encoding for conversion operations. After decoding the source bytes using FromCharset, Chilkat encodes the resulting Unicode text in this charset.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#ToCharset
	 * @param ?string $newVal
	 */
	function put_ToCharset($newVal) {
		CkCharset_put_ToCharset($this->_cPtr,$newVal);
	}

	/**
	 * If set to _TRUE_, then the contents of LastErrorText (or LastErrorXml, or LastErrorHtml) may contain more verbose information. The default value is _FALSE_.  Verbose logging should only be used for debugging.  The potentially large quantity of logged information may adversely affect peformance.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#VerboseLogging
	 * @return bool
	 */
	function get_VerboseLogging() {
		return CkCharset_get_VerboseLogging($this->_cPtr);
	}

	/**
	 * If set to _TRUE_, then the contents of LastErrorText (or LastErrorXml, or LastErrorHtml) may contain more verbose information. The default value is _FALSE_.  Verbose logging should only be used for debugging.  The potentially large quantity of logged information may adversely affect peformance.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#VerboseLogging
	 * @param bool $newVal
	 */
	function put_VerboseLogging($newVal) {
		CkCharset_put_VerboseLogging($this->_cPtr,$newVal);
	}

	/**
	 * Version of the component/library, such as "10.1.0"
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#Version
	 * @param CkString $str
	 */
	function get_Version($str) {
		CkCharset_get_Version($this->_cPtr,$str);
	}

	/**
	 * Version of the component/library, such as "10.1.0"
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#Version
	 * @return ?string
	 */
	function version() {
		return CkCharset_version($this->_cPtr);
	}

	/**
	 * Returns the numeric Windows code-page identifier corresponding to ARG1. For example, iso-8859-1 maps to 28591, and utf-8 maps to 65001. Code pages: A code page number is a legacy Windows identifier for a character encoding. Internet protocols and modern APIs normally use charset names such as utf-8 rather than numeric code pages.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#CharsetToCodePage
	 * @param ?string $charsetName
	 * @return int
	 */
	function CharsetToCodePage($charsetName) {
		return CkCharset_CharsetToCodePage($this->_cPtr,$charsetName);
	}

	/**
	 * Returns the charset name corresponding to the numeric code-page identifier in ARG1. For example, 65001 maps to utf-8. The operation fails when the code page is not recognized. Name normalization: Different aliases can identify the same encoding. The returned value is Chilkat’s canonical name for the recognized code page, not necessarily the alias originally used by another application.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#CodePageToCharset
	 * @param int $codePage
	 * @return ?string
	 */
	function codePageToCharset($codePage) {
		return CkCharset_codePageToCharset($this->_cPtr,$codePage);
	}

	/**
	 * Converts the bytes in ARG1 from FromCharset to ToCharset and returns the converted bytes.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#ConvertData
	 * @param CkByteData $inData
	 * @param CkByteData $outData
	 * @return bool
	 */
	function ConvertData($inData,$outData) {
		return CkCharset_ConvertData($this->_cPtr,$inData,$outData);
	}

	/**
	 * Reads the file at ARG1, converts its text from FromCharset to ToCharset, and writes the converted bytes to the file at ARG2. When the destination charset is utf-8 or utf-16, this method writes the corresponding byte-order mark (BOM) at the beginning of the output. Use ConvertFileNoPreamble when the output must not contain a BOM. BOM behavior: A BOM is a leading byte sequence that can identify a Unicode encoding or byte order. UTF-8 does not require a BOM, and many modern formats prefer UTF-8 without one.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#ConvertFile
	 * @param ?string $inPath
	 * @param ?string $destPath
	 * @return bool
	 */
	function ConvertFile($inPath,$destPath) {
		return CkCharset_ConvertFile($this->_cPtr,$inPath,$destPath);
	}

	/**
	 * Reads the file at ARG1, converts its text from FromCharset to ToCharset, and writes the converted bytes to ARG2 without adding a byte-order mark or other encoding preamble. UTF-8 output: This is generally the appropriate choice for UTF-8 files unless the consuming system specifically requires a UTF-8 BOM.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#ConvertFileNoPreamble
	 * @param ?string $inPath
	 * @param ?string $destPath
	 * @return bool
	 */
	function ConvertFileNoPreamble($inPath,$destPath) {
		return CkCharset_ConvertFileNoPreamble($this->_cPtr,$inPath,$destPath);
	}

	/**
	 * Encodes the Unicode string in ARG1 using ToCharset and returns the resulting bytes.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#ConvertFromUnicode
	 * @param ?string $inData
	 * @param CkByteData $outBytes
	 * @return bool
	 */
	function ConvertFromUnicode($inData,$outBytes) {
		return CkCharset_ConvertFromUnicode($this->_cPtr,$inData,$outBytes);
	}

	/**
	 * Converts the UTF-16 byte sequence in ARG1 to the character encoding specified by ToCharset and returns the resulting bytes.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#ConvertFromUtf16
	 * @param CkByteData $uniData
	 * @param CkByteData $outMbData
	 * @return bool
	 */
	function ConvertFromUtf16($uniData,$outMbData) {
		return CkCharset_ConvertFromUtf16($this->_cPtr,$uniData,$outMbData);
	}

	/**
	 * Converts HTML bytes in ARG1 from FromCharset to ToCharset. The returned bytes contain the converted HTML, and Chilkat updates the HTML <meta> charset declaration to identify the destination encoding. HTML charset declarations: Updating a <meta charset> declaration does not change HTTP response headers. When serving the converted file over HTTP, the server’s Content-Type charset must agree with the actual bytes.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#ConvertHtml
	 * @param CkByteData $inData
	 * @param CkByteData $outHtml
	 * @return bool
	 */
	function ConvertHtml($inData,$outHtml) {
		return CkCharset_ConvertHtml($this->_cPtr,$inData,$outHtml);
	}

	/**
	 * Converts the HTML file at ARG1 to ToCharset and writes the result to ARG2. Chilkat also updates the HTML <meta> charset declaration to identify the destination encoding. If FromCharset is empty, Chilkat attempts to obtain the source charset from an HTML <meta> declaration. Otherwise, the explicitly configured source charset is used. Detection limitation: A declared charset is metadata, not proof of the file’s actual encoding. Incorrect or missing declarations can cause decoding errors; use an explicit source charset when it is known.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#ConvertHtmlFile
	 * @param ?string $inPath
	 * @param ?string $destPath
	 * @return bool
	 */
	function ConvertHtmlFile($inPath,$destPath) {
		return CkCharset_ConvertHtmlFile($this->_cPtr,$inPath,$destPath);
	}

	/**
	 * Decodes the bytes in ARG1 using FromCharset and returns the resulting Unicode string.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#ConvertToUnicode
	 * @param CkByteData $inData
	 * @return ?string
	 */
	function convertToUnicode($inData) {
		return CkCharset_convertToUnicode($this->_cPtr,$inData);
	}

	/**
	 * Decodes the bytes in ARG1 using FromCharset and returns the text encoded as UTF-16 bytes.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#ConvertToUtf16
	 * @param CkByteData $mbData
	 * @param CkByteData $outUniData
	 * @return bool
	 */
	function ConvertToUtf16($mbData,$outUniData) {
		return CkCharset_ConvertToUtf16($this->_cPtr,$mbData,$outUniData);
	}

	/**
	 * Returns ARG1 with each non-US-ASCII character replaced by a decimal HTML/XML numeric character reference. For example, é becomes &#233;. Entity encoding: Numeric character references describe Unicode characters; they are not a character-set conversion and do not make arbitrary binary data safe for HTML.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#EntityEncodeDec
	 * @param ?string $str
	 * @return ?string
	 */
	function entityEncodeDec($str) {
		return CkCharset_entityEncodeDec($this->_cPtr,$str);
	}

	/**
	 * Returns ARG1 with each non-US-ASCII character replaced by a hexadecimal HTML/XML numeric character reference. For example, é becomes &#xE9;. Entity encoding: Decimal and hexadecimal numeric references represent the same Unicode character; only the textual notation differs.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#EntityEncodeHex
	 * @param ?string $str
	 * @return ?string
	 */
	function entityEncodeHex($str) {
		return CkCharset_entityEncodeHex($this->_cPtr,$str);
	}

	/**
	 * Examines the HTML bytes in ARG1 and returns the charset name declared by an HTML <meta> element, when present. Metadata only: This reports the declaration found in the document. It does not verify that the bytes actually use that encoding, and it does not inspect an HTTP Content-Type header.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#GetHtmlCharset
	 * @param CkByteData $inData
	 * @return ?string
	 */
	function getHtmlCharset($inData) {
		return CkCharset_getHtmlCharset($this->_cPtr,$inData);
	}

	/**
	 * Examines the HTML bytes in ARG1 and returns the charset name declared by an HTML <meta> element, when present. Metadata only: This reports the declaration found in the document. It does not verify that the bytes actually use that encoding, and it does not inspect an HTTP Content-Type header.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#GetHtmlCharset
	 * @param CkByteData $inData
	 * @return ?string
	 */
	function htmlCharset($inData) {
		return CkCharset_htmlCharset($this->_cPtr,$inData);
	}

	/**
	 * Examines the HTML file at ARG1 and returns the charset name declared by an HTML <meta> element, when present. Metadata only: The method reads document metadata only. A missing, stale, or incorrect declaration does not reveal the file’s true encoding.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#GetHtmlFileCharset
	 * @param ?string $htmlFilePath
	 * @return ?string
	 */
	function getHtmlFileCharset($htmlFilePath) {
		return CkCharset_getHtmlFileCharset($this->_cPtr,$htmlFilePath);
	}

	/**
	 * Examines the HTML file at ARG1 and returns the charset name declared by an HTML <meta> element, when present. Metadata only: The method reads document metadata only. A missing, stale, or incorrect declaration does not reveal the file’s true encoding.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#GetHtmlFileCharset
	 * @param ?string $htmlFilePath
	 * @return ?string
	 */
	function htmlFileCharset($htmlFilePath) {
		return CkCharset_htmlFileCharset($this->_cPtr,$htmlFilePath);
	}

	/**
	 * Decodes HTML named entities and numeric character references in ARG1 and returns the resulting Unicode string. Examples include &lt;, &amp;, &#233;, and &#xE9;. Security context: Entity decoding is a text transformation, not HTML parsing or sanitization. Decoding untrusted text can reintroduce markup-significant characters such as <, >, and &.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#HtmlDecodeToStr
	 * @param ?string $inStr
	 * @return ?string
	 */
	function htmlDecodeToStr($inStr) {
		return CkCharset_htmlDecodeToStr($this->_cPtr,$inStr);
	}

	/**
	 * Decodes HTML entities and numeric character references in the byte data supplied in ARG1 and returns the resulting bytes. Operation scope: Entity decoding is not a charset conversion and does not sanitize HTML.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#HtmlEntityDecode
	 * @param CkByteData $inHtml
	 * @param CkByteData $outData
	 * @return bool
	 */
	function HtmlEntityDecode($inHtml,$outData) {
		return CkCharset_HtmlEntityDecode($this->_cPtr,$inHtml,$outData);
	}

	/**
	 * Reads the file at ARG1, decodes HTML named entities and numeric character references, and writes the transformed content to ARG2. Content transformation: The output may contain literal markup-significant characters that were previously escaped. This operation does not parse, validate, or sanitize HTML.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#HtmlEntityDecodeFile
	 * @param ?string $inPath
	 * @param ?string $destPath
	 * @return bool
	 */
	function HtmlEntityDecodeFile($inPath,$destPath) {
		return CkCharset_HtmlEntityDecodeFile($this->_cPtr,$inPath,$destPath);
	}

	/**
	 * Returns the lowercase form of ARG1 using Chilkat’s Unicode case conversion. Unicode casing: Case conversion can change string length and is not the same operation as locale-aware collation or case-insensitive comparison.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#LowerCase
	 * @param ?string $inStr
	 * @return ?string
	 */
	function lowerCase($inStr) {
		return CkCharset_lowerCase($this->_cPtr,$inStr);
	}

	/**
	 * Reads the entire file at ARG1 and returns its raw bytes without performing charset conversion.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#ReadFile
	 * @param ?string $path
	 * @param CkByteData $outData
	 * @return bool
	 */
	function ReadFile($path,$outData) {
		return CkCharset_ReadFile($this->_cPtr,$path,$outData);
	}

	/**
	 * Reads the text file at ARG1, decodes its bytes using the charset named by ARG2, and returns the resulting Unicode string. Charset must match the file: The caller must supply the actual source encoding. Choosing the wrong charset can produce replacement characters or silently incorrect text even when the file can be decoded.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#ReadFileToString
	 * @param ?string $path
	 * @param ?string $charset
	 * @return ?string
	 */
	function readFileToString($path,$charset) {
		return CkCharset_readFileToString($this->_cPtr,$path,$charset);
	}

	/**
	 * Configures the replacement used when ErrorAction is 1. ARG1 is the replacement text, and ARG2 identifies the charset used to encode that replacement into the conversion output. Replacement behavior: Choose replacement text that is representable in the specified charset. A common replacement is ?, but explicit error handling is safer when data loss is unacceptable.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#SetErrorString
	 * @param ?string $str
	 * @param ?string $charset
	 */
	function SetErrorString($str,$charset) {
		CkCharset_SetErrorString($this->_cPtr,$str,$charset);
	}

	/**
	 * Returns the uppercase form of ARG1 using Chilkat’s Unicode case conversion. Unicode casing: Case conversion can change string length and is not the same operation as locale-aware collation or case-insensitive comparison.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#UpperCase
	 * @param ?string $inStr
	 * @return ?string
	 */
	function upperCase($inStr) {
		return CkCharset_upperCase($this->_cPtr,$inStr);
	}

	/**
	 * Percent-decodes ARG1 and interprets the resulting bytes using the platform’s legacy ANSI character encoding. For example, in a Western Windows code page, %C9 may decode as É. UTF-8 input would encode the same character as %C3%89 and is therefore not handled correctly by this legacy assumption. Legacy ANSI behavior: Do not use this method for modern URLs or form data unless the data is known to use the applicable ANSI code page. Use StringBuilder URL decoding with an explicit charset, normally utf-8.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#UrlDecodeStr
	 * @param ?string $inStr
	 * @return ?string
	 */
	function urlDecodeStr($inStr) {
		return CkCharset_urlDecodeStr($this->_cPtr,$inStr);
	}

	/**
	 * Returns _TRUE_ when the bytes in ARG2 form a valid sequence for the charset named by ARG1; otherwise returns _FALSE_. What validation means: This checks encoding validity only. It does not prove that the selected charset is the intended one. For many single-byte encodings, every possible byte value is valid.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#VerifyData
	 * @param ?string $charset
	 * @param CkByteData $inData
	 * @return bool
	 */
	function VerifyData($charset,$inData) {
		return CkCharset_VerifyData($this->_cPtr,$charset,$inData);
	}

	/**
	 * Returns _TRUE_ when the contents of the file at ARG2 form a valid byte sequence for the charset named by ARG1; otherwise returns _FALSE_. Validation limitation: A successful result means only that the bytes are structurally valid for that encoding. It does not identify the encoding or confirm that the decoded text is semantically correct.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#VerifyFile
	 * @param ?string $charset
	 * @param ?string $path
	 * @return bool
	 */
	function VerifyFile($charset,$path) {
		return CkCharset_VerifyFile($this->_cPtr,$charset,$path);
	}

	/**
	 * Writes all bytes from ARG2 to the file at ARG1 without performing charset conversion.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#WriteFile
	 * @param ?string $path
	 * @param CkByteData $byteData
	 * @return bool
	 */
	function WriteFile($path,$byteData) {
		return CkCharset_WriteFile($this->_cPtr,$path,$byteData);
	}

	/**
	 * Encodes the Unicode text in ARG1 using the charset named by ARG3 and writes the resulting bytes to the file at ARG2. Destination encoding: The charset argument is the third parameter. Select utf-8 for modern interchange unless a receiving system requires a specific legacy encoding.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkCharsetRef.html#WriteStringToFile
	 * @param ?string $textData
	 * @param ?string $path
	 * @param ?string $charset
	 * @return bool
	 */
	function WriteStringToFile($textData,$path,$charset) {
		return CkCharset_WriteStringToFile($this->_cPtr,$textData,$path,$charset);
	}
}
