<?php

/* CkDateTime.php -- Chilkat PHP extension proxy class CkDateTime.
 * Generated by ChilkatApi/GenCkPhp.cs for Chilkat v11.6.1 -- do not edit.
 * Reference documentation: https://www.chilkatsoft.com/refdoc/ */

/**
 * @see https://www.chilkatsoft.com/refdoc/phpExtCkDateTimeRef.html
 */
class CkDateTime {
	public $_cPtr=null;
	protected $_pData=array();

	function __set($var,$value) {
		if ($var === 'thisown') return swig_chilkat_alter_newobject($this->_cPtr,$value);
		$this->_pData[$var] = $value;
	}

	function __get($var) {
		if ($var === 'thisown') return swig_chilkat_get_newobject($this->_cPtr);
		return $this->_pData[$var];
	}

	function __isset($var) {
		if ($var === 'thisown') return true;
		return array_key_exists($var, $this->_pData);
	}

	function __construct($res=null) {
		if (is_resource($res) && get_resource_type($res) === '_p_CkDateTime') {
			$this->_cPtr=$res;
			return;
		}
		$this->_cPtr=new_CkDateTime();
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpExtCkDateTimeRef.html
	 * @return bool
	 */
	function get_Utf8() {
		return CkDateTime_get_Utf8($this->_cPtr);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpExtCkDateTimeRef.html
	 * @param bool $b
	 */
	function put_Utf8($b) {
		CkDateTime_put_Utf8($this->_cPtr,$b);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpExtCkDateTimeRef.html
	 * @return int
	 */
	function get_IsDst() {
		return CkDateTime_get_IsDst($this->_cPtr);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpExtCkDateTimeRef.html
	 * @return int
	 */
	function get_UtcOffset() {
		return CkDateTime_get_UtcOffset($this->_cPtr);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpExtCkDateTimeRef.html
	 * @return bool
	 */
	function SetFromCurrentSystemTime() {
		return CkDateTime_SetFromCurrentSystemTime($this->_cPtr);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpExtCkDateTimeRef.html
	 * @param ?string $rfc822Str
	 * @return bool
	 */
	function SetFromRfc822($rfc822Str) {
		return CkDateTime_SetFromRfc822($this->_cPtr,$rfc822Str);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpExtCkDateTimeRef.html
	 * @param bool $bLocal
	 * @return int
	 */
	function GetAsUnixTimeInt($bLocal) {
		return CkDateTime_GetAsUnixTimeInt($this->_cPtr,$bLocal);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpExtCkDateTimeRef.html
	 * @param bool $bLocal
	 * @return int
	 */
	function GetAsUnixTime64($bLocal) {
		return CkDateTime_GetAsUnixTime64($this->_cPtr,$bLocal);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpExtCkDateTimeRef.html
	 * @param bool $bLocal
	 * @return float
	 */
	function GetAsOleDate($bLocal) {
		return CkDateTime_GetAsOleDate($this->_cPtr,$bLocal);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpExtCkDateTimeRef.html
	 * @param bool $bLocal
	 * @return int
	 */
	function GetAsDosDate($bLocal) {
		return CkDateTime_GetAsDosDate($this->_cPtr,$bLocal);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpExtCkDateTimeRef.html
	 * @param bool $bLocal
	 * @return int
	 */
	function GetAsDateTimeTicks($bLocal) {
		return CkDateTime_GetAsDateTimeTicks($this->_cPtr,$bLocal);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpExtCkDateTimeRef.html
	 * @param bool $bLocal
	 * @param int $t
	 * @return bool
	 */
	function SetFromUnixTime64($bLocal,$t) {
		return CkDateTime_SetFromUnixTime64($this->_cPtr,$bLocal,$t);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpExtCkDateTimeRef.html
	 * @param bool $bLocal
	 * @param float $dt
	 * @return bool
	 */
	function SetFromOleDate($bLocal,$dt) {
		return CkDateTime_SetFromOleDate($this->_cPtr,$bLocal,$dt);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpExtCkDateTimeRef.html
	 * @param bool $bLocal
	 * @param int $t
	 * @return bool
	 */
	function SetFromDosDate($bLocal,$t) {
		return CkDateTime_SetFromDosDate($this->_cPtr,$bLocal,$t);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpExtCkDateTimeRef.html
	 * @param bool $bLocal
	 * @param int $n
	 * @return bool
	 */
	function SetFromDateTimeTicks($bLocal,$n) {
		return CkDateTime_SetFromDateTimeTicks($this->_cPtr,$bLocal,$n);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpExtCkDateTimeRef.html
	 * @return ?string
	 */
	function serialize() {
		return CkDateTime_serialize($this->_cPtr);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpExtCkDateTimeRef.html
	 * @param ?string $serializedDateTime
	 */
	function DeSerialize($serializedDateTime) {
		CkDateTime_DeSerialize($this->_cPtr,$serializedDateTime);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpExtCkDateTimeRef.html
	 * @param int $numDays
	 * @return bool
	 */
	function AddDays($numDays) {
		return CkDateTime_AddDays($this->_cPtr,$numDays);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpExtCkDateTimeRef.html
	 * @param bool $bLocal
	 * @return ?string
	 */
	function getAsRfc822($bLocal) {
		return CkDateTime_getAsRfc822($this->_cPtr,$bLocal);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpExtCkDateTimeRef.html
	 * @return bool
	 */
	function get_LastMethodSuccess() {
		return CkDateTime_get_LastMethodSuccess($this->_cPtr);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpExtCkDateTimeRef.html
	 * @param bool $newVal
	 */
	function put_LastMethodSuccess($newVal) {
		CkDateTime_put_LastMethodSuccess($this->_cPtr,$newVal);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpExtCkDateTimeRef.html
	 * @param int $numSeconds
	 * @return bool
	 */
	function AddSeconds($numSeconds) {
		return CkDateTime_AddSeconds($this->_cPtr,$numSeconds);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpExtCkDateTimeRef.html
	 * @param CkDateTime $dt
	 * @return int
	 */
	function DiffSeconds($dt) {
		return CkDateTime_DiffSeconds($this->_cPtr,$dt);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpExtCkDateTimeRef.html
	 * @param bool $bLocal
	 * @return ?string
	 */
	function getAsUnixTimeStr($bLocal) {
		return CkDateTime_getAsUnixTimeStr($this->_cPtr,$bLocal);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpExtCkDateTimeRef.html
	 * @param ?string $formatStr
	 * @param bool $bLocal
	 * @return ?string
	 */
	function getAsIso8601($formatStr,$bLocal) {
		return CkDateTime_getAsIso8601($this->_cPtr,$formatStr,$bLocal);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpExtCkDateTimeRef.html
	 * @param bool $bLocal
	 * @return ?string
	 */
	function getAsTimestamp($bLocal) {
		return CkDateTime_getAsTimestamp($this->_cPtr,$bLocal);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpExtCkDateTimeRef.html
	 * @param int $n
	 * @param ?string $units
	 * @return bool
	 */
	function ExpiresWithin($n,$units) {
		return CkDateTime_ExpiresWithin($this->_cPtr,$n,$units);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpExtCkDateTimeRef.html
	 * @param int $n
	 * @param ?string $units
	 * @return bool
	 */
	function OlderThan($n,$units) {
		return CkDateTime_OlderThan($this->_cPtr,$n,$units);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpExtCkDateTimeRef.html
	 * @param bool $bLocal
	 * @return ?CkDtObj
	 */
	function GetDtObj($bLocal) {
		return chilkat::_obj(CkDateTime_GetDtObj($this->_cPtr,$bLocal),'CkDtObj');
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpExtCkDateTimeRef.html
	 * @param CkDtObj $dtObj
	 * @return bool
	 */
	function SetFromDtObj($dtObj) {
		return CkDateTime_SetFromDtObj($this->_cPtr,$dtObj);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpExtCkDateTimeRef.html
	 * @param CkTask $task
	 * @return bool
	 */
	function LoadTaskResult($task) {
		return CkDateTime_LoadTaskResult($this->_cPtr,$task);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpExtCkDateTimeRef.html
	 * @param int $t
	 * @return bool
	 */
	function SetFromNtpTime($t) {
		return CkDateTime_SetFromNtpTime($this->_cPtr,$t);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpExtCkDateTimeRef.html
	 * @param ?string $rfc3339Str
	 * @return bool
	 */
	function SetFromTimestamp($rfc3339Str) {
		return CkDateTime_SetFromTimestamp($this->_cPtr,$rfc3339Str);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpExtCkDateTimeRef.html
	 * @param ?string $jsonNtpInfo
	 * @return bool
	 */
	function SetFromNtpServer($jsonNtpInfo) {
		return CkDateTime_SetFromNtpServer($this->_cPtr,$jsonNtpInfo);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpExtCkDateTimeRef.html
	 * @param CkStringBuilder $sb
	 * @return bool
	 */
	function UlidIncrement($sb) {
		return CkDateTime_UlidIncrement($this->_cPtr,$sb);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpExtCkDateTimeRef.html
	 * @param bool $bLocal
	 * @return ?string
	 */
	function ulidGenerate($bLocal) {
		return CkDateTime_ulidGenerate($this->_cPtr,$bLocal);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpExtCkDateTimeRef.html
	 * @param bool $bLocal
	 * @param ?string $ulid
	 * @return bool
	 */
	function SetFromUlid($bLocal,$ulid) {
		return CkDateTime_SetFromUlid($this->_cPtr,$bLocal,$ulid);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpExtCkDateTimeRef.html
	 * @param ?string $ulid
	 * @return bool
	 */
	function UlidValidate($ulid) {
		return CkDateTime_UlidValidate($this->_cPtr,$ulid);
	}
}
