<?php

/* CkDns.php -- Chilkat PHP extension proxy class CkDns.
 * Generated by ChilkatApi/GenCkPhp.cs for Chilkat v11.6.1 -- do not edit.
 * Reference documentation: https://www.chilkatsoft.com/refdoc/ */

/**
 * Configure DNS resolution and query DNS records directly from Chilkat.
 *
 * Chilkat.Dns is a focused class for DNS configuration and DNS record querying. It allows applications to control the nameservers used by Chilkat, query common DNS record types into JSON, configure DNS-over-TLS preference, set DNS query timeouts, and obtain useful diagnostics through LastErrorText.
 *
 * @see https://www.chilkatsoft.com/refdoc/phpCkDnsRef.html
 */
class CkDns {
	public $_cPtr=null;
	protected $_pData=array();

	function __set($var,$value) {
		if ($var === 'thisown') return swig_chilkat_alter_newobject($this->_cPtr,$value);
		$this->_pData[$var] = $value;
	}

	function __get($var) {
		if ($var === 'thisown') return swig_chilkat_get_newobject($this->_cPtr);
		return $this->_pData[$var];
	}

	function __isset($var) {
		if ($var === 'thisown') return true;
		return array_key_exists($var, $this->_pData);
	}

	function __construct($res=null) {
		if (is_resource($res) && get_resource_type($res) === '_p_CkDns') {
			$this->_cPtr=$res;
			return;
		}
		$this->_cPtr=new_CkDns();
	}

	/**
	 * When true, strings passed to and returned from the object are UTF-8. When false (the default), they are ANSI (the locale's 8-bit character encoding).
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDnsRef.html
	 * @return bool
	 */
	function get_Utf8() {
		return CkDns_get_Utf8($this->_cPtr);
	}

	/**
	 * When true, strings passed to and returned from the object are UTF-8. When false (the default), they are ANSI (the locale's 8-bit character encoding).
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDnsRef.html
	 * @param bool $b
	 */
	function put_Utf8($b) {
		CkDns_put_Utf8($this->_cPtr,$b);
	}

	/**
	 * Sets the event callback object.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDnsRef.html
	 * @param ?CkBaseProgress $progress
	 */
	function put_EventCallbackObject($progress) {
		CkDns_put_EventCallbackObject($this->_cPtr,$progress);
	}

	/**
	 * If set to a file path, this property logs the LastErrorText of each Chilkat method or property call to the specified file. This logging helps identify the context and history of Chilkat calls leading up to any crash or hang, aiding in debugging.  Enabling the VerboseLogging property provides more detailed information.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDnsRef.html#DebugLogFilePath
	 * @param CkString $str
	 */
	function get_DebugLogFilePath($str) {
		CkDns_get_DebugLogFilePath($this->_cPtr,$str);
	}

	/**
	 * If set to a file path, this property logs the LastErrorText of each Chilkat method or property call to the specified file. This logging helps identify the context and history of Chilkat calls leading up to any crash or hang, aiding in debugging.  Enabling the VerboseLogging property provides more detailed information.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDnsRef.html#DebugLogFilePath
	 * @return ?string
	 */
	function debugLogFilePath() {
		return CkDns_debugLogFilePath($this->_cPtr);
	}

	/**
	 * If set to a file path, this property logs the LastErrorText of each Chilkat method or property call to the specified file. This logging helps identify the context and history of Chilkat calls leading up to any crash or hang, aiding in debugging.  Enabling the VerboseLogging property provides more detailed information.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDnsRef.html#DebugLogFilePath
	 * @param ?string $newVal
	 */
	function put_DebugLogFilePath($newVal) {
		CkDns_put_DebugLogFilePath($this->_cPtr,$newVal);
	}

	/**
	 * The interval in milliseconds between each AbortCheck event callback, which enables an application to abort certain method calls before they complete. By default, HeartbeatMs is set to 0, meaning no AbortCheck event callbacks will trigger.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDnsRef.html#HeartbeatMs
	 * @return int
	 */
	function get_HeartbeatMs() {
		return CkDns_get_HeartbeatMs($this->_cPtr);
	}

	/**
	 * The interval in milliseconds between each AbortCheck event callback, which enables an application to abort certain method calls before they complete. By default, HeartbeatMs is set to 0, meaning no AbortCheck event callbacks will trigger.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDnsRef.html#HeartbeatMs
	 * @param int $newVal
	 */
	function put_HeartbeatMs($newVal) {
		CkDns_put_HeartbeatMs($this->_cPtr,$newVal);
	}

	/**
	 * Provides HTML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDnsRef.html#LastErrorHtml
	 * @param CkString $str
	 */
	function get_LastErrorHtml($str) {
		CkDns_get_LastErrorHtml($this->_cPtr,$str);
	}

	/**
	 * Provides HTML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDnsRef.html#LastErrorHtml
	 * @return ?string
	 */
	function lastErrorHtml() {
		return CkDns_lastErrorHtml($this->_cPtr);
	}

	/**
	 * Provides plain text information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDnsRef.html#LastErrorText
	 * @param CkString $str
	 */
	function get_LastErrorText($str) {
		CkDns_get_LastErrorText($this->_cPtr,$str);
	}

	/**
	 * Provides plain text information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDnsRef.html#LastErrorText
	 * @return ?string
	 */
	function lastErrorText() {
		return CkDns_lastErrorText($this->_cPtr);
	}

	/**
	 * Provides XML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDnsRef.html#LastErrorXml
	 * @param CkString $str
	 */
	function get_LastErrorXml($str) {
		CkDns_get_LastErrorXml($this->_cPtr,$str);
	}

	/**
	 * Provides XML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDnsRef.html#LastErrorXml
	 * @return ?string
	 */
	function lastErrorXml() {
		return CkDns_lastErrorXml($this->_cPtr);
	}

	/**
	 * Indicates the success or failure of the most recent method call: _TRUE_ means success, _FALSE_ means failure. This property remains unchanged by property setters or getters.  This method is present to address challenges in checking for null or Nothing returns in certain programming languages.  Note: This property does not apply to methods that return integer values or to boolean-returning methods where the boolean does not indicate success or failure.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDnsRef.html#LastMethodSuccess
	 * @return bool
	 */
	function get_LastMethodSuccess() {
		return CkDns_get_LastMethodSuccess($this->_cPtr);
	}

	/**
	 * Indicates the success or failure of the most recent method call: _TRUE_ means success, _FALSE_ means failure. This property remains unchanged by property setters or getters.  This method is present to address challenges in checking for null or Nothing returns in certain programming languages.  Note: This property does not apply to methods that return integer values or to boolean-returning methods where the boolean does not indicate success or failure.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDnsRef.html#LastMethodSuccess
	 * @param bool $newVal
	 */
	function put_LastMethodSuccess($newVal) {
		CkDns_put_LastMethodSuccess($this->_cPtr,$newVal);
	}

	/**
	 * The maxiumum number of milliseconds to wait for the answer to a DNS query.  A value of 0 is to wait indefinitely (no timeout).  It's not a good idea to specify 0 (infinite timeout) or a value less than 1000 (1 second).  The default value is 10000 milliseconds.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDnsRef.html#MaxWaitMs
	 * @return int
	 */
	function get_MaxWaitMs() {
		return CkDns_get_MaxWaitMs($this->_cPtr);
	}

	/**
	 * The maxiumum number of milliseconds to wait for the answer to a DNS query.  A value of 0 is to wait indefinitely (no timeout).  It's not a good idea to specify 0 (infinite timeout) or a value less than 1000 (1 second).  The default value is 10000 milliseconds.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDnsRef.html#MaxWaitMs
	 * @param int $newVal
	 */
	function put_MaxWaitMs($newVal) {
		CkDns_put_MaxWaitMs($this->_cPtr,$newVal);
	}

	/**
	 * The number of nameservers currently being used by Chilkat for DNS queries in all objects/classes, such as for HTTP, Email, FTP, SSH, etc.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDnsRef.html#NumNameservers
	 * @return int
	 */
	function get_NumNameservers() {
		return CkDns_get_NumNameservers($this->_cPtr);
	}

	/**
	 * Specifies the TLS preference.  Possible values are:
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDnsRef.html#TlsPref
	 * @return int
	 */
	function get_TlsPref() {
		return CkDns_get_TlsPref($this->_cPtr);
	}

	/**
	 * Specifies the TLS preference.  Possible values are:
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDnsRef.html#TlsPref
	 * @param int $newVal
	 */
	function put_TlsPref($newVal) {
		CkDns_put_TlsPref($this->_cPtr,$newVal);
	}

	/**
	 * This is a catch-all property to be used for uncommon needs.  This property defaults to the empty string and should typically remain empty.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDnsRef.html#UncommonOptions
	 * @param CkString $str
	 */
	function get_UncommonOptions($str) {
		CkDns_get_UncommonOptions($this->_cPtr,$str);
	}

	/**
	 * This is a catch-all property to be used for uncommon needs.  This property defaults to the empty string and should typically remain empty.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDnsRef.html#UncommonOptions
	 * @return ?string
	 */
	function uncommonOptions() {
		return CkDns_uncommonOptions($this->_cPtr);
	}

	/**
	 * This is a catch-all property to be used for uncommon needs.  This property defaults to the empty string and should typically remain empty.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDnsRef.html#UncommonOptions
	 * @param ?string $newVal
	 */
	function put_UncommonOptions($newVal) {
		CkDns_put_UncommonOptions($this->_cPtr,$newVal);
	}

	/**
	 * If set to _TRUE_, then the contents of LastErrorText (or LastErrorXml, or LastErrorHtml) may contain more verbose information. The default value is _FALSE_.  Verbose logging should only be used for debugging.  The potentially large quantity of logged information may adversely affect peformance.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDnsRef.html#VerboseLogging
	 * @return bool
	 */
	function get_VerboseLogging() {
		return CkDns_get_VerboseLogging($this->_cPtr);
	}

	/**
	 * If set to _TRUE_, then the contents of LastErrorText (or LastErrorXml, or LastErrorHtml) may contain more verbose information. The default value is _FALSE_.  Verbose logging should only be used for debugging.  The potentially large quantity of logged information may adversely affect peformance.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDnsRef.html#VerboseLogging
	 * @param bool $newVal
	 */
	function put_VerboseLogging($newVal) {
		CkDns_put_VerboseLogging($this->_cPtr,$newVal);
	}

	/**
	 * Version of the component/library, such as "10.1.0"
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDnsRef.html#Version
	 * @param CkString $str
	 */
	function get_Version($str) {
		CkDns_get_Version($this->_cPtr,$str);
	}

	/**
	 * Version of the component/library, such as "10.1.0"
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDnsRef.html#Version
	 * @return ?string
	 */
	function version() {
		return CkDns_version($this->_cPtr);
	}

	/**
	 * Adds the default (auto-assigned) nameservers to the collection of nameservers used by Chilkat for DNS queries and domain to IP address lookups.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDnsRef.html#AddDefaultNameservers
	 */
	function AddDefaultNameservers() {
		CkDns_AddDefaultNameservers($this->_cPtr);
	}

	/**
	 * Adds a new nameserver to the collection of nameservers used by Chilkat for DNS queries and domain to IP address lookups.  The ARG1 specifies the IPv4 address of the nameserver.  The ARG2 indicates if the namserver supports DoT (DNS over TLS.  DoT uses port 853 for encrypted DNS communication.)  If the TlsPreference property is set to 1 or 2, then Chilkat will use TLS nameservers.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDnsRef.html#AddNameserver
	 * @param ?string $ipAddr
	 * @param bool $supportsTls
	 */
	function AddNameserver($ipAddr,$supportsTls) {
		CkDns_AddNameserver($this->_cPtr,$ipAddr,$supportsTls);
	}

	/**
	 * Returns the IP address of the Nth nameserver currently used by Chilkat for DNS queries and domain to IP address lookups.  The ARG1 specifies the index of the nameserver.  The 1st nameserver is at ARG1 0.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDnsRef.html#GetNameserver
	 * @param int $index
	 * @return ?string
	 */
	function getNameserver($index) {
		return CkDns_getNameserver($this->_cPtr,$index);
	}

	/**
	 * Returns the IP address of the Nth nameserver currently used by Chilkat for DNS queries and domain to IP address lookups.  The ARG1 specifies the index of the nameserver.  The 1st nameserver is at ARG1 0.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDnsRef.html#GetNameserver
	 * @param int $index
	 * @return ?string
	 */
	function nameserver($index) {
		return CkDns_nameserver($this->_cPtr,$index);
	}

	/**
	 * Performs an DNS query for ARG2 and returns the answer in ARG3. The type of DNS query is specified in ARG1 and can be A, AAAA, ALIAS, CAA, MX, NS, SOA, TXT.  Additional record types can be added as needed.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDnsRef.html#Query
	 * @param ?string $recordType
	 * @param ?string $domain
	 * @param CkJsonObject $answer
	 * @return bool
	 */
	function Query($recordType,$domain,$answer) {
		return CkDns_Query($this->_cPtr,$recordType,$domain,$answer);
	}

	/**
	 * Creates an asynchronous task to call the Query method with the arguments provided.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDnsRef.html#QueryAsync
	 * @param ?string $recordType
	 * @param ?string $domain
	 * @param CkJsonObject $answer
	 * @return ?CkTask
	 */
	function QueryAsync($recordType,$domain,$answer) {
		return chilkat::_obj(CkDns_QueryAsync($this->_cPtr,$recordType,$domain,$answer),'CkTask');
	}

	/**
	 * Removes all nameservers from the collection of nameservers used by Chilkat.  An application can call this method to reset to 0 nameservers before adding new nameservers.  If a DNS domain to IP address resolution is needed by Chilkat, then the auto-assigned nameserver IP addresses will be automaticaly restored.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDnsRef.html#RemoveAllNameservers
	 */
	function RemoveAllNameservers() {
		CkDns_RemoveAllNameservers($this->_cPtr);
	}

	/**
	 * Removes a nameserver from the collection of nameservers used by Chilkat.  The ARG1 is the IPv4 address of the nameserver to be removed.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDnsRef.html#RemoveNameserver
	 * @param ?string $ipAddr
	 */
	function RemoveNameserver($ipAddr) {
		CkDns_RemoveNameserver($this->_cPtr,$ipAddr);
	}
}
