<?php

/* CkDsa.php -- Chilkat PHP extension proxy class CkDsa.
 * Generated by ChilkatApi/GenCkPhp.cs for Chilkat v11.6.1 -- do not edit.
 * Reference documentation: https://www.chilkatsoft.com/refdoc/ */

/**
 * Generate, import, export, sign, and verify DSA keys and signatures.
 *
 * Chilkat.Dsa is the Chilkat class for DSA key generation, DSA key import/export, DSA hash signing, and DSA signature verification. It supports private and public keys in DER, PEM, encrypted PEM, XML, explicit component, and OpenSSL parameter workflows. It also exposes DSA key components as hex-encoded SSH1-format bignums and provides helpers for working with encoded hashes and signatures.
 *
 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html
 */
class CkDsa {
	public $_cPtr=null;
	protected $_pData=array();

	function __set($var,$value) {
		if ($var === 'thisown') return swig_chilkat_alter_newobject($this->_cPtr,$value);
		$this->_pData[$var] = $value;
	}

	function __get($var) {
		if ($var === 'thisown') return swig_chilkat_get_newobject($this->_cPtr);
		return $this->_pData[$var];
	}

	function __isset($var) {
		if ($var === 'thisown') return true;
		return array_key_exists($var, $this->_pData);
	}

	function __construct($res=null) {
		if (is_resource($res) && get_resource_type($res) === '_p_CkDsa') {
			$this->_cPtr=$res;
			return;
		}
		$this->_cPtr=new_CkDsa();
	}

	/**
	 * When true, strings passed to and returned from the object are UTF-8. When false (the default), they are ANSI (the locale's 8-bit character encoding).
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html
	 * @return bool
	 */
	function get_Utf8() {
		return CkDsa_get_Utf8($this->_cPtr);
	}

	/**
	 * When true, strings passed to and returned from the object are UTF-8. When false (the default), they are ANSI (the locale's 8-bit character encoding).
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html
	 * @param bool $b
	 */
	function put_Utf8($b) {
		CkDsa_put_Utf8($this->_cPtr,$b);
	}

	/**
	 * If set to a file path, this property logs the LastErrorText of each Chilkat method or property call to the specified file. This logging helps identify the context and history of Chilkat calls leading up to any crash or hang, aiding in debugging.  Enabling the VerboseLogging property provides more detailed information.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#DebugLogFilePath
	 * @param CkString $str
	 */
	function get_DebugLogFilePath($str) {
		CkDsa_get_DebugLogFilePath($this->_cPtr,$str);
	}

	/**
	 * If set to a file path, this property logs the LastErrorText of each Chilkat method or property call to the specified file. This logging helps identify the context and history of Chilkat calls leading up to any crash or hang, aiding in debugging.  Enabling the VerboseLogging property provides more detailed information.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#DebugLogFilePath
	 * @return ?string
	 */
	function debugLogFilePath() {
		return CkDsa_debugLogFilePath($this->_cPtr);
	}

	/**
	 * If set to a file path, this property logs the LastErrorText of each Chilkat method or property call to the specified file. This logging helps identify the context and history of Chilkat calls leading up to any crash or hang, aiding in debugging.  Enabling the VerboseLogging property provides more detailed information.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#DebugLogFilePath
	 * @param ?string $newVal
	 */
	function put_DebugLogFilePath($newVal) {
		CkDsa_put_DebugLogFilePath($this->_cPtr,$newVal);
	}

	/**
	 * Specifies the size, in bits, of the DSA subgroup parameter Q used by the legacy GenKey method. The default is 160. This also determines the natural size of the DSA signature components r and s.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#GroupSize
	 * @return int
	 */
	function get_GroupSize() {
		return CkDsa_get_GroupSize($this->_cPtr);
	}

	/**
	 * Specifies the size, in bits, of the DSA subgroup parameter Q used by the legacy GenKey method. The default is 160. This also determines the natural size of the DSA signature components r and s.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#GroupSize
	 * @param int $newVal
	 */
	function put_GroupSize($newVal) {
		CkDsa_put_GroupSize($this->_cPtr,$newVal);
	}

	/**
	 * Returns the DSA domain parameter G, the generator of the subgroup of order Q modulo P.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#HexG
	 * @param CkString $str
	 */
	function get_HexG($str) {
		CkDsa_get_HexG($this->_cPtr,$str);
	}

	/**
	 * Returns the DSA domain parameter G, the generator of the subgroup of order Q modulo P.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#HexG
	 * @return ?string
	 */
	function hexG() {
		return CkDsa_hexG($this->_cPtr);
	}

	/**
	 * Returns the DSA domain parameter P, the large prime modulus.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#HexP
	 * @param CkString $str
	 */
	function get_HexP($str) {
		CkDsa_get_HexP($this->_cPtr,$str);
	}

	/**
	 * Returns the DSA domain parameter P, the large prime modulus.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#HexP
	 * @return ?string
	 */
	function hexP() {
		return CkDsa_hexP($this->_cPtr);
	}

	/**
	 * Returns the DSA domain parameter Q, a prime divisor of P - 1. The bit length of Q is commonly written as N and determines the range of the private value X and signature components r and s.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#HexQ
	 * @param CkString $str
	 */
	function get_HexQ($str) {
		CkDsa_get_HexQ($this->_cPtr,$str);
	}

	/**
	 * Returns the DSA domain parameter Q, a prime divisor of P - 1. The bit length of Q is commonly written as N and determines the range of the private value X and signature components r and s.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#HexQ
	 * @return ?string
	 */
	function hexQ() {
		return CkDsa_hexQ($this->_cPtr);
	}

	/**
	 * Returns the DSA private value X. It is present only when the object contains a private key and satisfies 0 < X < Q.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#HexX
	 * @param CkString $str
	 */
	function get_HexX($str) {
		CkDsa_get_HexX($this->_cPtr,$str);
	}

	/**
	 * Returns the DSA private value X. It is present only when the object contains a private key and satisfies 0 < X < Q.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#HexX
	 * @return ?string
	 */
	function hexX() {
		return CkDsa_hexX($this->_cPtr);
	}

	/**
	 * Returns the DSA public value Y, where Y = GX mod P. It is available when either a public or private DSA key is loaded.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#HexY
	 * @param CkString $str
	 */
	function get_HexY($str) {
		CkDsa_get_HexY($this->_cPtr,$str);
	}

	/**
	 * Returns the DSA public value Y, where Y = GX mod P. It is available when either a public or private DSA key is loaded.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#HexY
	 * @return ?string
	 */
	function hexY() {
		return CkDsa_hexY($this->_cPtr);
	}

	/**
	 * Provides HTML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#LastErrorHtml
	 * @param CkString $str
	 */
	function get_LastErrorHtml($str) {
		CkDsa_get_LastErrorHtml($this->_cPtr,$str);
	}

	/**
	 * Provides HTML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#LastErrorHtml
	 * @return ?string
	 */
	function lastErrorHtml() {
		return CkDsa_lastErrorHtml($this->_cPtr);
	}

	/**
	 * Provides plain text information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#LastErrorText
	 * @param CkString $str
	 */
	function get_LastErrorText($str) {
		CkDsa_get_LastErrorText($this->_cPtr,$str);
	}

	/**
	 * Provides plain text information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#LastErrorText
	 * @return ?string
	 */
	function lastErrorText() {
		return CkDsa_lastErrorText($this->_cPtr);
	}

	/**
	 * Provides XML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#LastErrorXml
	 * @param CkString $str
	 */
	function get_LastErrorXml($str) {
		CkDsa_get_LastErrorXml($this->_cPtr,$str);
	}

	/**
	 * Provides XML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#LastErrorXml
	 * @return ?string
	 */
	function lastErrorXml() {
		return CkDsa_lastErrorXml($this->_cPtr);
	}

	/**
	 * Indicates the success or failure of the most recent method call: _TRUE_ means success, _FALSE_ means failure. This property remains unchanged by property setters or getters.  This method is present to address challenges in checking for null or Nothing returns in certain programming languages.  Note: This property does not apply to methods that return integer values or to boolean-returning methods where the boolean does not indicate success or failure.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#LastMethodSuccess
	 * @return bool
	 */
	function get_LastMethodSuccess() {
		return CkDsa_get_LastMethodSuccess($this->_cPtr);
	}

	/**
	 * Indicates the success or failure of the most recent method call: _TRUE_ means success, _FALSE_ means failure. This property remains unchanged by property setters or getters.  This method is present to address challenges in checking for null or Nothing returns in certain programming languages.  Note: This property does not apply to methods that return integer values or to boolean-returning methods where the boolean does not indicate success or failure.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#LastMethodSuccess
	 * @param bool $newVal
	 */
	function put_LastMethodSuccess($newVal) {
		CkDsa_put_LastMethodSuccess($this->_cPtr,$newVal);
	}

	/**
	 * Reserved for uncommon or compatibility-specific options. The default is the empty string, and applications should normally leave this property unchanged unless Chilkat documentation or support identifies a specific keyword required for the target system.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#UncommonOptions
	 * @param CkString $str
	 */
	function get_UncommonOptions($str) {
		CkDsa_get_UncommonOptions($this->_cPtr,$str);
	}

	/**
	 * Reserved for uncommon or compatibility-specific options. The default is the empty string, and applications should normally leave this property unchanged unless Chilkat documentation or support identifies a specific keyword required for the target system.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#UncommonOptions
	 * @return ?string
	 */
	function uncommonOptions() {
		return CkDsa_uncommonOptions($this->_cPtr);
	}

	/**
	 * Reserved for uncommon or compatibility-specific options. The default is the empty string, and applications should normally leave this property unchanged unless Chilkat documentation or support identifies a specific keyword required for the target system.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#UncommonOptions
	 * @param ?string $newVal
	 */
	function put_UncommonOptions($newVal) {
		CkDsa_put_UncommonOptions($this->_cPtr,$newVal);
	}

	/**
	 * If set to _TRUE_, then the contents of LastErrorText (or LastErrorXml, or LastErrorHtml) may contain more verbose information. The default value is _FALSE_.  Verbose logging should only be used for debugging.  The potentially large quantity of logged information may adversely affect peformance.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#VerboseLogging
	 * @return bool
	 */
	function get_VerboseLogging() {
		return CkDsa_get_VerboseLogging($this->_cPtr);
	}

	/**
	 * If set to _TRUE_, then the contents of LastErrorText (or LastErrorXml, or LastErrorHtml) may contain more verbose information. The default value is _FALSE_.  Verbose logging should only be used for debugging.  The potentially large quantity of logged information may adversely affect peformance.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#VerboseLogging
	 * @param bool $newVal
	 */
	function put_VerboseLogging($newVal) {
		CkDsa_put_VerboseLogging($this->_cPtr,$newVal);
	}

	/**
	 * Version of the component/library, such as "10.1.0"
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#Version
	 * @param CkString $str
	 */
	function get_Version($str) {
		CkDsa_get_Version($this->_cPtr,$str);
	}

	/**
	 * Version of the component/library, such as "10.1.0"
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#Version
	 * @return ?string
	 */
	function version() {
		return CkDsa_version($this->_cPtr);
	}

	/**
	 * Loads a DSA private key from the DER-encoded bytes in ARG1. On success, the object contains both the private and public key components and can sign or verify digests.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#FromDer
	 * @param CkByteData $derData
	 * @return bool
	 */
	function FromDer($derData) {
		return CkDsa_FromDer($this->_cPtr,$derData);
	}

	/**
	 * Loads a DSA private key from the DER bytes contained in the BinData object passed in ARG1. Returns _TRUE_ on successful decoding.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#FromDerBd
	 * @param CkBinData $bd
	 * @return bool
	 */
	function FromDerBd($bd) {
		return CkDsa_FromDerBd($this->_cPtr,$bd);
	}

	/**
	 * Loads a DSA private key from the DER-encoded file specified by ARG1. Returns _TRUE_ when the file is read and decoded successfully; otherwise returns _FALSE_.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#FromDerFile
	 * @param ?string $path
	 * @return bool
	 */
	function FromDerFile($path) {
		return CkDsa_FromDerFile($this->_cPtr,$path);
	}

	/**
	 * Loads a DSA private key from the PEM text in ARG2. ARG1 supplies the password when the PEM is encrypted. If the PEM is unencrypted, the password is ignored and the key is loaded normally.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#FromEncryptedPem
	 * @param ?string $password
	 * @param ?string $pemData
	 * @return bool
	 */
	function FromEncryptedPem($password,$pemData) {
		return CkDsa_FromEncryptedPem($this->_cPtr,$password,$pemData);
	}

	/**
	 * Loads an unencrypted DSA private key from the PEM text in ARG1. On success, the object contains the private key and its corresponding public components.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#FromPem
	 * @param ?string $pemData
	 * @return bool
	 */
	function FromPem($pemData) {
		return CkDsa_FromPem($this->_cPtr,$pemData);
	}

	/**
	 * Loads a DSA public key from the DER-encoded bytes in ARG1. A public key can be used with Verify and can be exported, but it cannot be used by SignHash.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#FromPublicDer
	 * @param CkByteData $derData
	 * @return bool
	 */
	function FromPublicDer($derData) {
		return CkDsa_FromPublicDer($this->_cPtr,$derData);
	}

	/**
	 * Loads a DSA public key from the DER bytes contained in the BinData object passed in ARG1. The resulting key can verify signatures but cannot sign.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#FromPublicDerBd
	 * @param CkBinData $bd
	 * @return bool
	 */
	function FromPublicDerBd($bd) {
		return CkDsa_FromPublicDerBd($this->_cPtr,$bd);
	}

	/**
	 * Loads a DSA public key from the DER-encoded file specified by ARG1. Returns _TRUE_ when the file is read and decoded successfully; otherwise returns _FALSE_.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#FromPublicDerFile
	 * @param ?string $path
	 * @return bool
	 */
	function FromPublicDerFile($path) {
		return CkDsa_FromPublicDerFile($this->_cPtr,$path);
	}

	/**
	 * Loads a DSA public key from the PEM text in ARG1. Returns _TRUE_ when the PEM contains a supported DSA public key and is decoded successfully.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#FromPublicPem
	 * @param ?string $pemData
	 * @return bool
	 */
	function FromPublicPem($pemData) {
		return CkDsa_FromPublicPem($this->_cPtr,$pemData);
	}

	/**
	 * Loads a DSA public or private key from the XML text in ARG1. The XML content determines whether the resulting object contains public components only or also includes the private value X.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#FromXml
	 * @param ?string $xmlKey
	 * @return bool
	 */
	function FromXml($xmlKey) {
		return CkDsa_FromXml($this->_cPtr,$xmlKey);
	}

	/**
	 * Generates a new DSA key pair with a P size of ARG1 bits. ARG1 must be at least 1024 and a multiple of 64. This legacy method uses the subgroup size selected by GroupSize, whose default is 160 bits.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#GenKey
	 * @param int $numBits
	 * @return bool
	 */
	function GenKey($numBits) {
		return CkDsa_GenKey($this->_cPtr,$numBits);
	}

	/**
	 * Generates a new DSA key pair using an explicit (L, N) parameter-size combination. ARG1 is L, the bit length of the prime modulus P. ARG2 is N, the bit length of the subgroup prime Q.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#GenKey2
	 * @param int $keyLenBits
	 * @param int $modLenBits
	 * @return bool
	 */
	function GenKey2($keyLenBits,$modLenBits) {
		return CkDsa_GenKey2($this->_cPtr,$keyLenBits,$modLenBits);
	}

	/**
	 * Generates a new DSA key pair from OpenSSL-style DSA parameters supplied as DER-encoded bytes in ARG1.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#GenKeyFromParamsDer
	 * @param CkByteData $derBytes
	 * @return bool
	 */
	function GenKeyFromParamsDer($derBytes) {
		return CkDsa_GenKeyFromParamsDer($this->_cPtr,$derBytes);
	}

	/**
	 * Generates a new DSA key pair from OpenSSL-style DSA parameters stored as DER bytes in the BinData object passed in ARG1.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#GenKeyFromParamsDerBd
	 * @param CkBinData $bd
	 * @return bool
	 */
	function GenKeyFromParamsDerBd($bd) {
		return CkDsa_GenKeyFromParamsDerBd($this->_cPtr,$bd);
	}

	/**
	 * Generates a new DSA key pair from the OpenSSL-style DER DSA-parameters file specified by ARG1.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#GenKeyFromParamsDerFile
	 * @param ?string $path
	 * @return bool
	 */
	function GenKeyFromParamsDerFile($path) {
		return CkDsa_GenKeyFromParamsDerFile($this->_cPtr,$path);
	}

	/**
	 * Generates a new DSA key pair from OpenSSL-style DSA parameters supplied as PEM text in ARG1.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#GenKeyFromParamsPem
	 * @param ?string $pem
	 * @return bool
	 */
	function GenKeyFromParamsPem($pem) {
		return CkDsa_GenKeyFromParamsPem($this->_cPtr,$pem);
	}

	/**
	 * Generates a new DSA key pair from the OpenSSL-style PEM DSA-parameters file specified by ARG1.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#GenKeyFromParamsPemFile
	 * @param ?string $path
	 * @return bool
	 */
	function GenKeyFromParamsPemFile($path) {
		return CkDsa_GenKeyFromParamsPemFile($this->_cPtr,$path);
	}

	/**
	 * Generates a new DSA private/public key pair using the preselected domain parameters P, Q, and G supplied in ARG1, ARG2, and ARG3.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#GenKeyFromPQG
	 * @param ?string $pHex
	 * @param ?string $qHex
	 * @param ?string $gHex
	 * @return bool
	 */
	function GenKeyFromPQG($pHex,$qHex,$gHex) {
		return CkDsa_GenKeyFromPQG($this->_cPtr,$pHex,$qHex,$gHex);
	}

	/**
	 * Returns the current Hash bytes encoded according to ARG1. Use hex or base64.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#GetEncodedHash
	 * @param ?string $encoding
	 * @return ?string
	 */
	function getEncodedHash($encoding) {
		return CkDsa_getEncodedHash($this->_cPtr,$encoding);
	}

	/**
	 * Returns the current Hash bytes encoded according to ARG1. Use hex or base64.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#GetEncodedHash
	 * @param ?string $encoding
	 * @return ?string
	 */
	function encodedHash($encoding) {
		return CkDsa_encodedHash($this->_cPtr,$encoding);
	}

	/**
	 * Returns the current Signature bytes encoded according to ARG1. Use hex or base64.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#GetEncodedSignature
	 * @param ?string $encoding
	 * @return ?string
	 */
	function getEncodedSignature($encoding) {
		return CkDsa_getEncodedSignature($this->_cPtr,$encoding);
	}

	/**
	 * Returns the current Signature bytes encoded according to ARG1. Use hex or base64.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#GetEncodedSignature
	 * @param ?string $encoding
	 * @return ?string
	 */
	function encodedSignature($encoding) {
		return CkDsa_encodedSignature($this->_cPtr,$encoding);
	}

	/**
	 * Loads the entire file specified by ARG1 and returns its contents as text using the legacy ANSI character encoding.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#LoadText
	 * @param ?string $path
	 * @return ?string
	 */
	function loadText($path) {
		return CkDsa_loadText($this->_cPtr,$path);
	}

	/**
	 * Writes ARG1 to the file specified by ARG2 using the legacy ANSI character encoding. Returns _TRUE_ on success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#SaveText
	 * @param ?string $strToSave
	 * @param ?string $path
	 * @return bool
	 */
	function SaveText($strToSave,$path) {
		return CkDsa_SaveText($this->_cPtr,$strToSave,$path);
	}

	/**
	 * Decodes ARG2 using the encoding named by ARG1 and stores the resulting bytes in the Hash property. Use hex or base64.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#SetEncodedHash
	 * @param ?string $encoding
	 * @param ?string $encodedHash
	 * @return bool
	 */
	function SetEncodedHash($encoding,$encodedHash) {
		return CkDsa_SetEncodedHash($this->_cPtr,$encoding,$encodedHash);
	}

	/**
	 * Decodes the signature text in ARG2 using the encoding named by ARG1 and stores the resulting bytes in the Signature property. Use hex or base64.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#SetEncodedSignature
	 * @param ?string $encoding
	 * @param ?string $encodedSig
	 * @return bool
	 */
	function SetEncodedSignature($encoding,$encodedSig) {
		return CkDsa_SetEncodedSignature($this->_cPtr,$encoding,$encodedSig);
	}

	/**
	 * Builds the DSA signature from separately encoded r and s integer values. ARG1 identifies the encoding used by both ARG2 and ARG3; use hex or base64.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#SetEncodedSignatureRS
	 * @param ?string $encoding
	 * @param ?string $encodedR
	 * @param ?string $encodedS
	 * @return bool
	 */
	function SetEncodedSignatureRS($encoding,$encodedR,$encodedS) {
		return CkDsa_SetEncodedSignatureRS($this->_cPtr,$encoding,$encodedR,$encodedS);
	}

	/**
	 * Loads a DSA private key from explicitly supplied components. ARG1 is the size of Q in bytes. ARG2, ARG3, ARG4, and ARG5 provide P, Q, G, and the private value X, respectively.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#SetKeyExplicit
	 * @param int $groupSizeInBytes
	 * @param ?string $pHex
	 * @param ?string $qHex
	 * @param ?string $gHex
	 * @param ?string $xHex
	 * @return bool
	 */
	function SetKeyExplicit($groupSizeInBytes,$pHex,$qHex,$gHex,$xHex) {
		return CkDsa_SetKeyExplicit($this->_cPtr,$groupSizeInBytes,$pHex,$qHex,$gHex,$xHex);
	}

	/**
	 * Loads a DSA public key from explicitly supplied components. ARG1 is the size of Q in bytes. ARG2, ARG3, ARG4, and ARG5 provide P, Q, G, and the public value Y, respectively.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#SetPubKeyExplicit
	 * @param int $groupSizeInBytes
	 * @param ?string $pHex
	 * @param ?string $qHex
	 * @param ?string $gHex
	 * @param ?string $yHex
	 * @return bool
	 */
	function SetPubKeyExplicit($groupSizeInBytes,$pHex,$qHex,$gHex,$yHex) {
		return CkDsa_SetPubKeyExplicit($this->_cPtr,$groupSizeInBytes,$pHex,$qHex,$gHex,$yHex);
	}

	/**
	 * Creates a DSA signature over the digest currently stored in Hash. A DSA private key must be loaded, and the digest must be set directly or with SetEncodedHash before this method is called.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#SignHash
	 * @return bool
	 */
	function SignHash() {
		return CkDsa_SignHash($this->_cPtr);
	}

	/**
	 * Returns the loaded DSA private key as DER-encoded bytes. A private key must be present; a public-only key cannot be exported by this method.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#ToDer
	 * @param CkByteData $outBytes
	 * @return bool
	 */
	function ToDer($outBytes) {
		return CkDsa_ToDer($this->_cPtr,$outBytes);
	}

	/**
	 * Writes the DER-encoded DSA private key to the BinData object passed in ARG1. Returns _TRUE_ on success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#ToDerBd
	 * @param CkBinData $bd
	 * @return bool
	 */
	function ToDerBd($bd) {
		return CkDsa_ToDerBd($this->_cPtr,$bd);
	}

	/**
	 * Writes the loaded DSA private key to the DER file specified by ARG1. Returns _TRUE_ on success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#ToDerFile
	 * @param ?string $path
	 * @return bool
	 */
	function ToDerFile($path) {
		return CkDsa_ToDerFile($this->_cPtr,$path);
	}

	/**
	 * Returns the loaded DSA private key as password-encrypted PEM text using ARG1 as the password.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#ToEncryptedPem
	 * @param ?string $password
	 * @return ?string
	 */
	function toEncryptedPem($password) {
		return CkDsa_toEncryptedPem($this->_cPtr,$password);
	}

	/**
	 * Returns the loaded DSA private key as unencrypted PEM text.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#ToPem
	 * @return ?string
	 */
	function toPem() {
		return CkDsa_toPem($this->_cPtr);
	}

	/**
	 * Returns the public portion of the loaded DSA key as DER-encoded bytes. This works whether the object contains a public key or a private key with a corresponding public value.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#ToPublicDer
	 * @param CkByteData $outBytes
	 * @return bool
	 */
	function ToPublicDer($outBytes) {
		return CkDsa_ToPublicDer($this->_cPtr,$outBytes);
	}

	/**
	 * Writes the DER-encoded public portion of the loaded DSA key to the BinData object passed in ARG1. Returns _TRUE_ on success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#ToPublicDerBd
	 * @param CkBinData $bd
	 * @return bool
	 */
	function ToPublicDerBd($bd) {
		return CkDsa_ToPublicDerBd($this->_cPtr,$bd);
	}

	/**
	 * Writes the public portion of the loaded DSA key to the DER file specified by ARG1. Returns _TRUE_ on success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#ToPublicDerFile
	 * @param ?string $path
	 * @return bool
	 */
	function ToPublicDerFile($path) {
		return CkDsa_ToPublicDerFile($this->_cPtr,$path);
	}

	/**
	 * Returns the public portion of the loaded DSA key as PEM text. Public-key PEM may be distributed to parties that need to verify signatures; it does not contain the private value X.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#ToPublicPem
	 * @return ?string
	 */
	function toPublicPem() {
		return CkDsa_toPublicPem($this->_cPtr);
	}

	/**
	 * Returns the loaded DSA key as XML. Set ARG1 to _TRUE_ to export public components only. Set it to _FALSE_ to include the private component when a private key is loaded.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#ToXml
	 * @param bool $bPublicOnly
	 * @return ?string
	 */
	function toXml($bPublicOnly) {
		return CkDsa_toXml($this->_cPtr,$bPublicOnly);
	}

	/**
	 * Verifies the DSA signature currently stored in Signature against the digest stored in Hash, using the loaded public key. Both values must be set before calling this method.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#Verify
	 * @return bool
	 */
	function Verify() {
		return CkDsa_Verify($this->_cPtr);
	}

	/**
	 * Checks the mathematical validity and internal consistency of the DSA public or private key currently loaded in the object. Returns _TRUE_ when the key parameters and available key components pass validation.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDsaRef.html#VerifyKey
	 * @return bool
	 */
	function VerifyKey() {
		return CkDsa_VerifyKey($this->_cPtr);
	}
}
