<?php

/* CkDtObj.php -- Chilkat PHP extension proxy class CkDtObj.
 * Generated by ChilkatApi/GenCkPhp.cs for Chilkat v11.6.1 -- do not edit.
 * Reference documentation: https://www.chilkatsoft.com/refdoc/ */

/**
 * @see https://www.chilkatsoft.com/refdoc/phpCkDtObjRef.html
 */
class CkDtObj {
	public $_cPtr=null;
	protected $_pData=array();

	function __set($var,$value) {
		if ($var === 'thisown') return swig_chilkat_alter_newobject($this->_cPtr,$value);
		$this->_pData[$var] = $value;
	}

	function __get($var) {
		if ($var === 'thisown') return swig_chilkat_get_newobject($this->_cPtr);
		return $this->_pData[$var];
	}

	function __isset($var) {
		if ($var === 'thisown') return true;
		return array_key_exists($var, $this->_pData);
	}

	function __construct($res=null) {
		if (is_resource($res) && get_resource_type($res) === '_p_CkDtObj') {
			$this->_cPtr=$res;
			return;
		}
		$this->_cPtr=new_CkDtObj();
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDtObjRef.html
	 * @return bool
	 */
	function get_Utf8() {
		return CkDtObj_get_Utf8($this->_cPtr);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDtObjRef.html
	 * @param bool $b
	 */
	function put_Utf8($b) {
		CkDtObj_put_Utf8($this->_cPtr,$b);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDtObjRef.html
	 * @return bool
	 */
	function get_Utc() {
		return CkDtObj_get_Utc($this->_cPtr);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDtObjRef.html
	 * @param bool $newVal
	 */
	function put_Utc($newVal) {
		CkDtObj_put_Utc($this->_cPtr,$newVal);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDtObjRef.html
	 * @return int
	 */
	function get_Year() {
		return CkDtObj_get_Year($this->_cPtr);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDtObjRef.html
	 * @param int $newVal
	 */
	function put_Year($newVal) {
		CkDtObj_put_Year($this->_cPtr,$newVal);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDtObjRef.html
	 * @return int
	 */
	function get_Month() {
		return CkDtObj_get_Month($this->_cPtr);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDtObjRef.html
	 * @param int $newVal
	 */
	function put_Month($newVal) {
		CkDtObj_put_Month($this->_cPtr,$newVal);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDtObjRef.html
	 * @return int
	 */
	function get_Day() {
		return CkDtObj_get_Day($this->_cPtr);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDtObjRef.html
	 * @param int $newVal
	 */
	function put_Day($newVal) {
		CkDtObj_put_Day($this->_cPtr,$newVal);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDtObjRef.html
	 * @return int
	 */
	function get_Hour() {
		return CkDtObj_get_Hour($this->_cPtr);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDtObjRef.html
	 * @param int $newVal
	 */
	function put_Hour($newVal) {
		CkDtObj_put_Hour($this->_cPtr,$newVal);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDtObjRef.html
	 * @return int
	 */
	function get_Minute() {
		return CkDtObj_get_Minute($this->_cPtr);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDtObjRef.html
	 * @param int $newVal
	 */
	function put_Minute($newVal) {
		CkDtObj_put_Minute($this->_cPtr,$newVal);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDtObjRef.html
	 * @return int
	 */
	function get_Second() {
		return CkDtObj_get_Second($this->_cPtr);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDtObjRef.html
	 * @param int $newVal
	 */
	function put_Second($newVal) {
		CkDtObj_put_Second($this->_cPtr,$newVal);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDtObjRef.html
	 * @return int
	 */
	function get_StructTmYear() {
		return CkDtObj_get_StructTmYear($this->_cPtr);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDtObjRef.html
	 * @param int $newVal
	 */
	function put_StructTmYear($newVal) {
		CkDtObj_put_StructTmYear($this->_cPtr,$newVal);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDtObjRef.html
	 * @return int
	 */
	function get_StructTmMonth() {
		return CkDtObj_get_StructTmMonth($this->_cPtr);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDtObjRef.html
	 * @param int $newVal
	 */
	function put_StructTmMonth($newVal) {
		CkDtObj_put_StructTmMonth($this->_cPtr,$newVal);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDtObjRef.html
	 * @return ?string
	 */
	function serialize() {
		return CkDtObj_serialize($this->_cPtr);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkDtObjRef.html
	 * @param ?string $serializedDtObj
	 */
	function DeSerialize($serializedDtObj) {
		CkDtObj_DeSerialize($this->_cPtr,$serializedDtObj);
	}
}
