<?php

/* CkEdDSA.php -- Chilkat PHP extension proxy class CkEdDSA.
 * Generated by ChilkatApi/GenCkPhp.cs for Chilkat v11.6.1 -- do not edit.
 * Reference documentation: https://www.chilkatsoft.com/refdoc/ */

/**
 * Generate Ed25519 keys, sign data, verify signatures, and compute shared secrets.
 *
 * Chilkat.EdDSA is the Chilkat class for Ed25519-based EdDSA operations. It can generate Ed25519 private keys, sign data contained in BinData, verify encoded signatures with public keys, and compute encoded shared secrets from compatible private/public key pairs. It supports the Ed25519, Ed25519ph, and Ed25519ctx variants, with optional context bytes supplied as a hex string when the selected variant requires them.
 *
 * @see https://www.chilkatsoft.com/refdoc/phpCkEdDSARef.html
 */
class CkEdDSA {
	public $_cPtr=null;
	protected $_pData=array();

	function __set($var,$value) {
		if ($var === 'thisown') return swig_chilkat_alter_newobject($this->_cPtr,$value);
		$this->_pData[$var] = $value;
	}

	function __get($var) {
		if ($var === 'thisown') return swig_chilkat_get_newobject($this->_cPtr);
		return $this->_pData[$var];
	}

	function __isset($var) {
		if ($var === 'thisown') return true;
		return array_key_exists($var, $this->_pData);
	}

	function __construct($res=null) {
		if (is_resource($res) && get_resource_type($res) === '_p_CkEdDSA') {
			$this->_cPtr=$res;
			return;
		}
		$this->_cPtr=new_CkEdDSA();
	}

	/**
	 * When true, strings passed to and returned from the object are UTF-8. When false (the default), they are ANSI (the locale's 8-bit character encoding).
	 * @see https://www.chilkatsoft.com/refdoc/phpCkEdDSARef.html
	 * @return bool
	 */
	function get_Utf8() {
		return CkEdDSA_get_Utf8($this->_cPtr);
	}

	/**
	 * When true, strings passed to and returned from the object are UTF-8. When false (the default), they are ANSI (the locale's 8-bit character encoding).
	 * @see https://www.chilkatsoft.com/refdoc/phpCkEdDSARef.html
	 * @param bool $b
	 */
	function put_Utf8($b) {
		CkEdDSA_put_Utf8($this->_cPtr,$b);
	}

	/**
	 * Selects the Ed25519 signature variant used by SignBdENC and VerifyBdENC. The default is Ed25519.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkEdDSARef.html#Algorithm
	 * @param CkString $str
	 */
	function get_Algorithm($str) {
		CkEdDSA_get_Algorithm($this->_cPtr,$str);
	}

	/**
	 * Selects the Ed25519 signature variant used by SignBdENC and VerifyBdENC. The default is Ed25519.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkEdDSARef.html#Algorithm
	 * @return ?string
	 */
	function algorithm() {
		return CkEdDSA_algorithm($this->_cPtr);
	}

	/**
	 * Selects the Ed25519 signature variant used by SignBdENC and VerifyBdENC. The default is Ed25519.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkEdDSARef.html#Algorithm
	 * @param ?string $newVal
	 */
	function put_Algorithm($newVal) {
		CkEdDSA_put_Algorithm($this->_cPtr,$newVal);
	}

	/**
	 * Gets or sets the context bytes used by the Ed25519ctx and Ed25519ph signature variants. Supply the bytes as a hexadecimal string. The default is an empty string.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkEdDSARef.html#Context
	 * @param CkString $str
	 */
	function get_Context($str) {
		CkEdDSA_get_Context($this->_cPtr,$str);
	}

	/**
	 * Gets or sets the context bytes used by the Ed25519ctx and Ed25519ph signature variants. Supply the bytes as a hexadecimal string. The default is an empty string.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkEdDSARef.html#Context
	 * @return ?string
	 */
	function context() {
		return CkEdDSA_context($this->_cPtr);
	}

	/**
	 * Gets or sets the context bytes used by the Ed25519ctx and Ed25519ph signature variants. Supply the bytes as a hexadecimal string. The default is an empty string.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkEdDSARef.html#Context
	 * @param ?string $newVal
	 */
	function put_Context($newVal) {
		CkEdDSA_put_Context($this->_cPtr,$newVal);
	}

	/**
	 * If set to a file path, this property logs the LastErrorText of each Chilkat method or property call to the specified file. This logging helps identify the context and history of Chilkat calls leading up to any crash or hang, aiding in debugging.  Enabling the VerboseLogging property provides more detailed information.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkEdDSARef.html#DebugLogFilePath
	 * @param CkString $str
	 */
	function get_DebugLogFilePath($str) {
		CkEdDSA_get_DebugLogFilePath($this->_cPtr,$str);
	}

	/**
	 * If set to a file path, this property logs the LastErrorText of each Chilkat method or property call to the specified file. This logging helps identify the context and history of Chilkat calls leading up to any crash or hang, aiding in debugging.  Enabling the VerboseLogging property provides more detailed information.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkEdDSARef.html#DebugLogFilePath
	 * @return ?string
	 */
	function debugLogFilePath() {
		return CkEdDSA_debugLogFilePath($this->_cPtr);
	}

	/**
	 * If set to a file path, this property logs the LastErrorText of each Chilkat method or property call to the specified file. This logging helps identify the context and history of Chilkat calls leading up to any crash or hang, aiding in debugging.  Enabling the VerboseLogging property provides more detailed information.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkEdDSARef.html#DebugLogFilePath
	 * @param ?string $newVal
	 */
	function put_DebugLogFilePath($newVal) {
		CkEdDSA_put_DebugLogFilePath($this->_cPtr,$newVal);
	}

	/**
	 * Provides HTML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkEdDSARef.html#LastErrorHtml
	 * @param CkString $str
	 */
	function get_LastErrorHtml($str) {
		CkEdDSA_get_LastErrorHtml($this->_cPtr,$str);
	}

	/**
	 * Provides HTML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkEdDSARef.html#LastErrorHtml
	 * @return ?string
	 */
	function lastErrorHtml() {
		return CkEdDSA_lastErrorHtml($this->_cPtr);
	}

	/**
	 * Provides plain text information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkEdDSARef.html#LastErrorText
	 * @param CkString $str
	 */
	function get_LastErrorText($str) {
		CkEdDSA_get_LastErrorText($this->_cPtr,$str);
	}

	/**
	 * Provides plain text information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkEdDSARef.html#LastErrorText
	 * @return ?string
	 */
	function lastErrorText() {
		return CkEdDSA_lastErrorText($this->_cPtr);
	}

	/**
	 * Provides XML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkEdDSARef.html#LastErrorXml
	 * @param CkString $str
	 */
	function get_LastErrorXml($str) {
		CkEdDSA_get_LastErrorXml($this->_cPtr,$str);
	}

	/**
	 * Provides XML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkEdDSARef.html#LastErrorXml
	 * @return ?string
	 */
	function lastErrorXml() {
		return CkEdDSA_lastErrorXml($this->_cPtr);
	}

	/**
	 * Indicates the success or failure of the most recent method call: _TRUE_ means success, _FALSE_ means failure. This property remains unchanged by property setters or getters.  This method is present to address challenges in checking for null or Nothing returns in certain programming languages.  Note: This property does not apply to methods that return integer values or to boolean-returning methods where the boolean does not indicate success or failure.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkEdDSARef.html#LastMethodSuccess
	 * @return bool
	 */
	function get_LastMethodSuccess() {
		return CkEdDSA_get_LastMethodSuccess($this->_cPtr);
	}

	/**
	 * Indicates the success or failure of the most recent method call: _TRUE_ means success, _FALSE_ means failure. This property remains unchanged by property setters or getters.  This method is present to address challenges in checking for null or Nothing returns in certain programming languages.  Note: This property does not apply to methods that return integer values or to boolean-returning methods where the boolean does not indicate success or failure.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkEdDSARef.html#LastMethodSuccess
	 * @param bool $newVal
	 */
	function put_LastMethodSuccess($newVal) {
		CkEdDSA_put_LastMethodSuccess($this->_cPtr,$newVal);
	}

	/**
	 * If set to _TRUE_, then the contents of LastErrorText (or LastErrorXml, or LastErrorHtml) may contain more verbose information. The default value is _FALSE_.  Verbose logging should only be used for debugging.  The potentially large quantity of logged information may adversely affect peformance.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkEdDSARef.html#VerboseLogging
	 * @return bool
	 */
	function get_VerboseLogging() {
		return CkEdDSA_get_VerboseLogging($this->_cPtr);
	}

	/**
	 * If set to _TRUE_, then the contents of LastErrorText (or LastErrorXml, or LastErrorHtml) may contain more verbose information. The default value is _FALSE_.  Verbose logging should only be used for debugging.  The potentially large quantity of logged information may adversely affect peformance.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkEdDSARef.html#VerboseLogging
	 * @param bool $newVal
	 */
	function put_VerboseLogging($newVal) {
		CkEdDSA_put_VerboseLogging($this->_cPtr,$newVal);
	}

	/**
	 * Version of the component/library, such as "10.1.0"
	 * @see https://www.chilkatsoft.com/refdoc/phpCkEdDSARef.html#Version
	 * @param CkString $str
	 */
	function get_Version($str) {
		CkEdDSA_get_Version($this->_cPtr,$str);
	}

	/**
	 * Version of the component/library, such as "10.1.0"
	 * @see https://www.chilkatsoft.com/refdoc/phpCkEdDSARef.html#Version
	 * @return ?string
	 */
	function version() {
		return CkEdDSA_version($this->_cPtr);
	}

	/**
	 * Generates a new Ed25519 key pair using ARG1 as the source of cryptographically secure random bytes. On success, the generated private key and its corresponding public key are stored in the existing PrivateKey object passed in ARG2.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkEdDSARef.html#GenEd25519Key
	 * @param CkPrng $prng
	 * @param CkPrivateKey $privKey
	 * @return bool
	 */
	function GenEd25519Key($prng,$privKey) {
		return CkEdDSA_GenEd25519Key($this->_cPtr,$prng,$privKey);
	}

	/**
	 * Computes a 32-byte X25519 shared secret from the private key in ARG1 and the peer's public key in ARG2. The resulting bytes are returned as text using the binary encoding named by ARG3, such as hex, hexlower, or base64.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkEdDSARef.html#SharedSecretENC
	 * @param CkPrivateKey $privkey
	 * @param CkPublicKey $pubkey
	 * @param ?string $encoding
	 * @return ?string
	 */
	function sharedSecretENC($privkey,$pubkey,$encoding) {
		return CkEdDSA_sharedSecretENC($this->_cPtr,$privkey,$pubkey,$encoding);
	}

	/**
	 * Creates an EdDSA signature over the exact byte sequence contained in ARG1, using the Ed25519 private key in ARG3. The 64-byte signature is returned as text using the binary encoding named by ARG2, such as hex, hexlower, or base64.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkEdDSARef.html#SignBdENC
	 * @param CkBinData $bd
	 * @param ?string $encoding
	 * @param CkPrivateKey $privkey
	 * @return ?string
	 */
	function signBdENC($bd,$encoding,$privkey) {
		return CkEdDSA_signBdENC($this->_cPtr,$bd,$encoding,$privkey);
	}

	/**
	 * Verifies the encoded EdDSA signature in ARG2 against the exact byte sequence contained in ARG1, using the Ed25519 public key in ARG4. ARG3 names the binary encoding of ARG2, such as hex, hexlower, or base64.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkEdDSARef.html#VerifyBdENC
	 * @param CkBinData $bd
	 * @param ?string $encodedSig
	 * @param ?string $enocding
	 * @param CkPublicKey $pubkey
	 * @return bool
	 */
	function VerifyBdENC($bd,$encodedSig,$enocding,$pubkey) {
		return CkEdDSA_VerifyBdENC($this->_cPtr,$bd,$encodedSig,$enocding,$pubkey);
	}
}
