<?php

/* CkHtmlToXml.php -- Chilkat PHP extension proxy class CkHtmlToXml.
 * Generated by ChilkatApi/GenCkPhp.cs for Chilkat v11.6.1 -- do not edit.
 * Reference documentation: https://www.chilkatsoft.com/refdoc/ */

/**
 * Convert HTML into well-formed XML for structured parsing and searching.
 *
 * Chilkat.HtmlToXml converts HTML into well-formed XML so the content can be parsed, searched, transformed, or processed programmatically with XML tools. It can accept HTML from strings, files, byte arrays, BinData, or StringBuilder, and provides options for dropping selected tags, removing common text-formatting tags, controlling non-breaking spaces, choosing the XML charset, and saving the converted XML to a file.
 *
 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToXmlRef.html
 */
class CkHtmlToXml {
	public $_cPtr=null;
	protected $_pData=array();

	function __set($var,$value) {
		if ($var === 'thisown') return swig_chilkat_alter_newobject($this->_cPtr,$value);
		$this->_pData[$var] = $value;
	}

	function __get($var) {
		if ($var === 'thisown') return swig_chilkat_get_newobject($this->_cPtr);
		return $this->_pData[$var];
	}

	function __isset($var) {
		if ($var === 'thisown') return true;
		return array_key_exists($var, $this->_pData);
	}

	function __construct($res=null) {
		if (is_resource($res) && get_resource_type($res) === '_p_CkHtmlToXml') {
			$this->_cPtr=$res;
			return;
		}
		$this->_cPtr=new_CkHtmlToXml();
	}

	/**
	 * When true, strings passed to and returned from the object are UTF-8. When false (the default), they are ANSI (the locale's 8-bit character encoding).
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToXmlRef.html
	 * @return bool
	 */
	function get_Utf8() {
		return CkHtmlToXml_get_Utf8($this->_cPtr);
	}

	/**
	 * When true, strings passed to and returned from the object are UTF-8. When false (the default), they are ANSI (the locale's 8-bit character encoding).
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToXmlRef.html
	 * @param bool $b
	 */
	function put_Utf8($b) {
		CkHtmlToXml_put_Utf8($this->_cPtr,$b);
	}

	/**
	 * If set to a file path, this property logs the LastErrorText of each Chilkat method or property call to the specified file. This logging helps identify the context and history of Chilkat calls leading up to any crash or hang, aiding in debugging.  Enabling the VerboseLogging property provides more detailed information.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToXmlRef.html#DebugLogFilePath
	 * @param CkString $str
	 */
	function get_DebugLogFilePath($str) {
		CkHtmlToXml_get_DebugLogFilePath($this->_cPtr,$str);
	}

	/**
	 * If set to a file path, this property logs the LastErrorText of each Chilkat method or property call to the specified file. This logging helps identify the context and history of Chilkat calls leading up to any crash or hang, aiding in debugging.  Enabling the VerboseLogging property provides more detailed information.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToXmlRef.html#DebugLogFilePath
	 * @return ?string
	 */
	function debugLogFilePath() {
		return CkHtmlToXml_debugLogFilePath($this->_cPtr);
	}

	/**
	 * If set to a file path, this property logs the LastErrorText of each Chilkat method or property call to the specified file. This logging helps identify the context and history of Chilkat calls leading up to any crash or hang, aiding in debugging.  Enabling the VerboseLogging property provides more detailed information.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToXmlRef.html#DebugLogFilePath
	 * @param ?string $newVal
	 */
	function put_DebugLogFilePath($newVal) {
		CkHtmlToXml_put_DebugLogFilePath($this->_cPtr,$newVal);
	}

	/**
	 * Controls whether tags that Chilkat does not recognize as standard HTML elements are omitted from the generated XML.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToXmlRef.html#DropCustomTags
	 * @return bool
	 */
	function get_DropCustomTags() {
		return CkHtmlToXml_get_DropCustomTags($this->_cPtr);
	}

	/**
	 * Controls whether tags that Chilkat does not recognize as standard HTML elements are omitted from the generated XML.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToXmlRef.html#DropCustomTags
	 * @param bool $newVal
	 */
	function put_DropCustomTags($newVal) {
		CkHtmlToXml_put_DropCustomTags($this->_cPtr,$newVal);
	}

	/**
	 * The HTML source to be converted. Set this property to an HTML string, configure any conversion options, and then call ToXml, Xml, or ToXmlSb.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToXmlRef.html#Html
	 * @param CkString $str
	 */
	function get_Html($str) {
		CkHtmlToXml_get_Html($this->_cPtr,$str);
	}

	/**
	 * The HTML source to be converted. Set this property to an HTML string, configure any conversion options, and then call ToXml, Xml, or ToXmlSb.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToXmlRef.html#Html
	 * @return ?string
	 */
	function html() {
		return CkHtmlToXml_html($this->_cPtr);
	}

	/**
	 * The HTML source to be converted. Set this property to an HTML string, configure any conversion options, and then call ToXml, Xml, or ToXmlSb.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToXmlRef.html#Html
	 * @param ?string $newVal
	 */
	function put_Html($newVal) {
		CkHtmlToXml_put_Html($this->_cPtr,$newVal);
	}

	/**
	 * Provides HTML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToXmlRef.html#LastErrorHtml
	 * @param CkString $str
	 */
	function get_LastErrorHtml($str) {
		CkHtmlToXml_get_LastErrorHtml($this->_cPtr,$str);
	}

	/**
	 * Provides HTML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToXmlRef.html#LastErrorHtml
	 * @return ?string
	 */
	function lastErrorHtml() {
		return CkHtmlToXml_lastErrorHtml($this->_cPtr);
	}

	/**
	 * Provides plain text information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToXmlRef.html#LastErrorText
	 * @param CkString $str
	 */
	function get_LastErrorText($str) {
		CkHtmlToXml_get_LastErrorText($this->_cPtr,$str);
	}

	/**
	 * Provides plain text information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToXmlRef.html#LastErrorText
	 * @return ?string
	 */
	function lastErrorText() {
		return CkHtmlToXml_lastErrorText($this->_cPtr);
	}

	/**
	 * Provides XML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToXmlRef.html#LastErrorXml
	 * @param CkString $str
	 */
	function get_LastErrorXml($str) {
		CkHtmlToXml_get_LastErrorXml($this->_cPtr,$str);
	}

	/**
	 * Provides XML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToXmlRef.html#LastErrorXml
	 * @return ?string
	 */
	function lastErrorXml() {
		return CkHtmlToXml_lastErrorXml($this->_cPtr);
	}

	/**
	 * Indicates the success or failure of the most recent method call: _TRUE_ means success, _FALSE_ means failure. This property remains unchanged by property setters or getters.  This method is present to address challenges in checking for null or Nothing returns in certain programming languages.  Note: This property does not apply to methods that return integer values or to boolean-returning methods where the boolean does not indicate success or failure.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToXmlRef.html#LastMethodSuccess
	 * @return bool
	 */
	function get_LastMethodSuccess() {
		return CkHtmlToXml_get_LastMethodSuccess($this->_cPtr);
	}

	/**
	 * Indicates the success or failure of the most recent method call: _TRUE_ means success, _FALSE_ means failure. This property remains unchanged by property setters or getters.  This method is present to address challenges in checking for null or Nothing returns in certain programming languages.  Note: This property does not apply to methods that return integer values or to boolean-returning methods where the boolean does not indicate success or failure.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToXmlRef.html#LastMethodSuccess
	 * @param bool $newVal
	 */
	function put_LastMethodSuccess($newVal) {
		CkHtmlToXml_put_LastMethodSuccess($this->_cPtr,$newVal);
	}

	/**
	 * Controls how HTML non-breaking-space entities are handled during conversion. The default value is 0.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToXmlRef.html#Nbsp
	 * @return int
	 */
	function get_Nbsp() {
		return CkHtmlToXml_get_Nbsp($this->_cPtr);
	}

	/**
	 * Controls how HTML non-breaking-space entities are handled during conversion. The default value is 0.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToXmlRef.html#Nbsp
	 * @param int $newVal
	 */
	function put_Nbsp($newVal) {
		CkHtmlToXml_put_Nbsp($this->_cPtr,$newVal);
	}

	/**
	 * If set to _TRUE_, then the contents of LastErrorText (or LastErrorXml, or LastErrorHtml) may contain more verbose information. The default value is _FALSE_.  Verbose logging should only be used for debugging.  The potentially large quantity of logged information may adversely affect peformance.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToXmlRef.html#VerboseLogging
	 * @return bool
	 */
	function get_VerboseLogging() {
		return CkHtmlToXml_get_VerboseLogging($this->_cPtr);
	}

	/**
	 * If set to _TRUE_, then the contents of LastErrorText (or LastErrorXml, or LastErrorHtml) may contain more verbose information. The default value is _FALSE_.  Verbose logging should only be used for debugging.  The potentially large quantity of logged information may adversely affect peformance.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToXmlRef.html#VerboseLogging
	 * @param bool $newVal
	 */
	function put_VerboseLogging($newVal) {
		CkHtmlToXml_put_VerboseLogging($this->_cPtr,$newVal);
	}

	/**
	 * Version of the component/library, such as "10.1.0"
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToXmlRef.html#Version
	 * @param CkString $str
	 */
	function get_Version($str) {
		CkHtmlToXml_get_Version($this->_cPtr,$str);
	}

	/**
	 * Version of the component/library, such as "10.1.0"
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToXmlRef.html#Version
	 * @return ?string
	 */
	function version() {
		return CkHtmlToXml_version($this->_cPtr);
	}

	/**
	 * Specifies the character encoding to identify for the generated XML, such as utf-8 or iso-8859-1. If this property is empty, Chilkat uses the character encoding of the HTML input. Otherwise, the converted XML uses the specified charset.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToXmlRef.html#XmlCharset
	 * @param CkString $str
	 */
	function get_XmlCharset($str) {
		CkHtmlToXml_get_XmlCharset($this->_cPtr,$str);
	}

	/**
	 * Specifies the character encoding to identify for the generated XML, such as utf-8 or iso-8859-1. If this property is empty, Chilkat uses the character encoding of the HTML input. Otherwise, the converted XML uses the specified charset.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToXmlRef.html#XmlCharset
	 * @return ?string
	 */
	function xmlCharset() {
		return CkHtmlToXml_xmlCharset($this->_cPtr);
	}

	/**
	 * Specifies the character encoding to identify for the generated XML, such as utf-8 or iso-8859-1. If this property is empty, Chilkat uses the character encoding of the HTML input. Otherwise, the converted XML uses the specified charset.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToXmlRef.html#XmlCharset
	 * @param ?string $newVal
	 */
	function put_XmlCharset($newVal) {
		CkHtmlToXml_put_XmlCharset($this->_cPtr,$newVal);
	}

	/**
	 * Converts the HTML file at inHtmlPath to a well-formed XML file at destXmlPath. The output encoding is controlled by XmlCharset; if XmlCharset is empty, Chilkat uses the HTML source encoding.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToXmlRef.html#ConvertFile
	 * @param ?string $inHtmlPath
	 * @param ?string $destXmlPath
	 * @return bool
	 */
	function ConvertFile($inHtmlPath,$destXmlPath) {
		return CkHtmlToXml_ConvertFile($this->_cPtr,$inHtmlPath,$destXmlPath);
	}

	/**
	 * Marks the specified HTML tag type to be dropped from the generated XML. To drop multiple tag types, call this method once for each tag name.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToXmlRef.html#DropTagType
	 * @param ?string $tagName
	 */
	function DropTagType($tagName) {
		CkHtmlToXml_DropTagType($this->_cPtr,$tagName);
	}

	/**
	 * Configures the converter to drop common text-formatting tags from the generated XML. The affected tag names are:
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToXmlRef.html#DropTextFormattingTags
	 */
	function DropTextFormattingTags() {
		CkHtmlToXml_DropTextFormattingTags($this->_cPtr);
	}

	/**
	 * Reads the complete contents of path and returns the file data as bytes.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToXmlRef.html#ReadFile
	 * @param ?string $path
	 * @param CkByteData $outBytes
	 * @return bool
	 * @deprecated
	 */
	function ReadFile($path,$outBytes) {
		return CkHtmlToXml_ReadFile($this->_cPtr,$path,$outBytes);
	}

	/**
	 * Reads the complete text file at filename and decodes its bytes using srcCharset, such as utf-8 or iso-8859-1. Returns the decoded text string.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToXmlRef.html#ReadFileToString
	 * @param ?string $filename
	 * @param ?string $srcCharset
	 * @return ?string
	 * @deprecated
	 */
	function readFileToString($filename,$srcCharset) {
		return CkHtmlToXml_readFileToString($this->_cPtr,$filename,$srcCharset);
	}

	/**
	 * Replaces the current HTML source with the complete contents of bd.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToXmlRef.html#SetHtmlBd
	 * @param CkBinData $bd
	 * @return bool
	 */
	function SetHtmlBd($bd) {
		return CkHtmlToXml_SetHtmlBd($this->_cPtr,$bd);
	}

	/**
	 * Replaces the current HTML source with the contents of inData.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToXmlRef.html#SetHtmlBytes
	 * @param CkByteData $inData
	 */
	function SetHtmlBytes($inData) {
		CkHtmlToXml_SetHtmlBytes($this->_cPtr,$inData);
	}

	/**
	 * Loads HTML from filename and replaces the current Html input with the file contents.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToXmlRef.html#SetHtmlFromFile
	 * @param ?string $filename
	 * @return bool
	 */
	function SetHtmlFromFile($filename) {
		return CkHtmlToXml_SetHtmlFromFile($this->_cPtr,$filename);
	}

	/**
	 * Replaces the current HTML source with the complete contents of sb.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToXmlRef.html#SetHtmlSb
	 * @param CkStringBuilder $sb
	 * @return bool
	 */
	function SetHtmlSb($sb) {
		return CkHtmlToXml_SetHtmlSb($this->_cPtr,$sb);
	}

	/**
	 * Converts the current Html input to well-formed XML and returns the XML string. The generated XML uses the conversion settings currently configured on this object, including DropCustomTags, dropped tag types, Nbsp, and XmlCharset.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToXmlRef.html#ToXml
	 * @return ?string
	 */
	function toXml() {
		return CkHtmlToXml_toXml($this->_cPtr);
	}

	/**
	 * Converts the current Html input to well-formed XML and appends the generated XML to sb.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToXmlRef.html#ToXmlSb
	 * @param CkStringBuilder $sb
	 * @return bool
	 */
	function ToXmlSb($sb) {
		return CkHtmlToXml_ToXmlSb($this->_cPtr,$sb);
	}

	/**
	 * Reverses a previous DropTagType setting for the specified tag name so that tag type is no longer intentionally dropped from subsequent XML output.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToXmlRef.html#UndropTagType
	 * @param ?string $tagName
	 */
	function UndropTagType($tagName) {
		CkHtmlToXml_UndropTagType($this->_cPtr,$tagName);
	}

	/**
	 * Configures the converter to retain the common text-formatting tags that are otherwise dropped by default:
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToXmlRef.html#UndropTextFormattingTags
	 */
	function UndropTextFormattingTags() {
		CkHtmlToXml_UndropTextFormattingTags($this->_cPtr);
	}

	/**
	 * Writes the bytes in fileData to path. Returns _TRUE_ on success and _FALSE_ on failure.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToXmlRef.html#WriteFile
	 * @param ?string $path
	 * @param CkByteData $fileData
	 * @return bool
	 * @deprecated
	 */
	function WriteFile($path,$fileData) {
		return CkHtmlToXml_WriteFile($this->_cPtr,$path,$fileData);
	}

	/**
	 * Encodes stringToWrite using charset and writes the resulting text to filename. Typical charset names include utf-8 and iso-8859-1.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToXmlRef.html#WriteStringToFile
	 * @param ?string $stringToWrite
	 * @param ?string $filename
	 * @param ?string $charset
	 * @return bool
	 * @deprecated
	 */
	function WriteStringToFile($stringToWrite,$filename,$charset) {
		return CkHtmlToXml_WriteStringToFile($this->_cPtr,$stringToWrite,$filename,$charset);
	}

	/**
	 * Equivalent to ToXml. Converts the current Html input to well-formed XML and returns the XML string using the object's current conversion settings.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToXmlRef.html#Xml
	 * @return ?string
	 */
	function xml() {
		return CkHtmlToXml_xml($this->_cPtr);
	}
}
