<?php

/* CkHttpRequest.php -- Chilkat PHP extension proxy class CkHttpRequest.
 * Generated by ChilkatApi/GenCkPhp.cs for Chilkat v11.6.1 -- do not edit.
 * Reference documentation: https://www.chilkatsoft.com/refdoc/ */

/**
 * Build structured HTTP requests for use with Chilkat.Http.
 *
 * Chilkat.HttpRequest is a helper class for constructing HTTP requests that are sent by Chilkat.Http. It does not perform network communication on its own. Instead, it provides structured control over the request method, HTTP version, path, headers, query parameters, form parameters, content type, request body, multipart uploads, streamed file bodies, and diagnostic request generation.
 *
 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html
 */
class CkHttpRequest {
	public $_cPtr=null;
	protected $_pData=array();

	function __set($var,$value) {
		if ($var === 'thisown') return swig_chilkat_alter_newobject($this->_cPtr,$value);
		$this->_pData[$var] = $value;
	}

	function __get($var) {
		if ($var === 'thisown') return swig_chilkat_get_newobject($this->_cPtr);
		return $this->_pData[$var];
	}

	function __isset($var) {
		if ($var === 'thisown') return true;
		return array_key_exists($var, $this->_pData);
	}

	function __construct($res=null) {
		if (is_resource($res) && get_resource_type($res) === '_p_CkHttpRequest') {
			$this->_cPtr=$res;
			return;
		}
		$this->_cPtr=new_CkHttpRequest();
	}

	/**
	 * When true, strings passed to and returned from the object are UTF-8. When false (the default), they are ANSI (the locale's 8-bit character encoding).
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html
	 * @return bool
	 */
	function get_Utf8() {
		return CkHttpRequest_get_Utf8($this->_cPtr);
	}

	/**
	 * When true, strings passed to and returned from the object are UTF-8. When false (the default), they are ANSI (the locale's 8-bit character encoding).
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html
	 * @param bool $b
	 */
	function put_Utf8($b) {
		CkHttpRequest_put_Utf8($this->_cPtr,$b);
	}

	/**
	 * Sets an explicit boundary string to be used in multipart/form-data requests.  If no Boundary is set, then a boundary string is automaticaly generated as needed during the sending  of a request.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#Boundary
	 * @param CkString $str
	 */
	function get_Boundary($str) {
		CkHttpRequest_get_Boundary($this->_cPtr,$str);
	}

	/**
	 * Sets an explicit boundary string to be used in multipart/form-data requests.  If no Boundary is set, then a boundary string is automaticaly generated as needed during the sending  of a request.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#Boundary
	 * @return ?string
	 */
	function boundary() {
		return CkHttpRequest_boundary($this->_cPtr);
	}

	/**
	 * Sets an explicit boundary string to be used in multipart/form-data requests.  If no Boundary is set, then a boundary string is automaticaly generated as needed during the sending  of a request.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#Boundary
	 * @param ?string $newVal
	 */
	function put_Boundary($newVal) {
		CkHttpRequest_put_Boundary($this->_cPtr,$newVal);
	}

	/**
	 * Controls the character encoding used in the URL encoding of query params.  The default value of this propoerty is utf-8.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#Charset
	 * @param CkString $str
	 */
	function get_Charset($str) {
		CkHttpRequest_get_Charset($this->_cPtr,$str);
	}

	/**
	 * Controls the character encoding used in the URL encoding of query params.  The default value of this propoerty is utf-8.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#Charset
	 * @return ?string
	 */
	function charset() {
		return CkHttpRequest_charset($this->_cPtr);
	}

	/**
	 * Controls the character encoding used in the URL encoding of query params.  The default value of this propoerty is utf-8.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#Charset
	 * @param ?string $newVal
	 */
	function put_Charset($newVal) {
		CkHttpRequest_put_Charset($this->_cPtr,$newVal);
	}

	/**
	 * The ContentType property sets the Content-Type header field, and identifies the content-type of the HTTP request body.  Common values are:
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#ContentType
	 * @param CkString $str
	 */
	function get_ContentType($str) {
		CkHttpRequest_get_ContentType($this->_cPtr,$str);
	}

	/**
	 * The ContentType property sets the Content-Type header field, and identifies the content-type of the HTTP request body.  Common values are:
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#ContentType
	 * @return ?string
	 */
	function contentType() {
		return CkHttpRequest_contentType($this->_cPtr);
	}

	/**
	 * The ContentType property sets the Content-Type header field, and identifies the content-type of the HTTP request body.  Common values are:
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#ContentType
	 * @param ?string $newVal
	 */
	function put_ContentType($newVal) {
		CkHttpRequest_put_ContentType($this->_cPtr,$newVal);
	}

	/**
	 * If set to a file path, this property logs the LastErrorText of each Chilkat method or property call to the specified file. This logging helps identify the context and history of Chilkat calls leading up to any crash or hang, aiding in debugging.  Enabling the VerboseLogging property provides more detailed information.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#DebugLogFilePath
	 * @param CkString $str
	 */
	function get_DebugLogFilePath($str) {
		CkHttpRequest_get_DebugLogFilePath($this->_cPtr,$str);
	}

	/**
	 * If set to a file path, this property logs the LastErrorText of each Chilkat method or property call to the specified file. This logging helps identify the context and history of Chilkat calls leading up to any crash or hang, aiding in debugging.  Enabling the VerboseLogging property provides more detailed information.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#DebugLogFilePath
	 * @return ?string
	 */
	function debugLogFilePath() {
		return CkHttpRequest_debugLogFilePath($this->_cPtr);
	}

	/**
	 * If set to a file path, this property logs the LastErrorText of each Chilkat method or property call to the specified file. This logging helps identify the context and history of Chilkat calls leading up to any crash or hang, aiding in debugging.  Enabling the VerboseLogging property provides more detailed information.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#DebugLogFilePath
	 * @param ?string $newVal
	 */
	function put_DebugLogFilePath($newVal) {
		CkHttpRequest_put_DebugLogFilePath($this->_cPtr,$newVal);
	}

	/**
	 * Composes and returns the entire MIME header of the HTTP request.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#EntireHeader
	 * @param CkString $str
	 */
	function get_EntireHeader($str) {
		CkHttpRequest_get_EntireHeader($this->_cPtr,$str);
	}

	/**
	 * Composes and returns the entire MIME header of the HTTP request.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#EntireHeader
	 * @return ?string
	 */
	function entireHeader() {
		return CkHttpRequest_entireHeader($this->_cPtr);
	}

	/**
	 * Composes and returns the entire MIME header of the HTTP request.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#EntireHeader
	 * @param ?string $newVal
	 */
	function put_EntireHeader($newVal) {
		CkHttpRequest_put_EntireHeader($this->_cPtr,$newVal);
	}

	/**
	 * The HttpVerb property should be set to the name of the HTTP method that appears on the start line of an HTTP request, such as GET, POST, PUT, DELETE, etc.  It is also possible to use the various WebDav verbs such as PROPFIND, PROPPATCH, MKCOL, COPY, MOVE, LOCK, UNLOCK, etc.  In general, the HttpVerb may be set to anything, even custom verbs recognized by a custom server-side app.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#HttpVerb
	 * @param CkString $str
	 */
	function get_HttpVerb($str) {
		CkHttpRequest_get_HttpVerb($this->_cPtr,$str);
	}

	/**
	 * The HttpVerb property should be set to the name of the HTTP method that appears on the start line of an HTTP request, such as GET, POST, PUT, DELETE, etc.  It is also possible to use the various WebDav verbs such as PROPFIND, PROPPATCH, MKCOL, COPY, MOVE, LOCK, UNLOCK, etc.  In general, the HttpVerb may be set to anything, even custom verbs recognized by a custom server-side app.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#HttpVerb
	 * @return ?string
	 */
	function httpVerb() {
		return CkHttpRequest_httpVerb($this->_cPtr);
	}

	/**
	 * The HttpVerb property should be set to the name of the HTTP method that appears on the start line of an HTTP request, such as GET, POST, PUT, DELETE, etc.  It is also possible to use the various WebDav verbs such as PROPFIND, PROPPATCH, MKCOL, COPY, MOVE, LOCK, UNLOCK, etc.  In general, the HttpVerb may be set to anything, even custom verbs recognized by a custom server-side app.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#HttpVerb
	 * @param ?string $newVal
	 */
	function put_HttpVerb($newVal) {
		CkHttpRequest_put_HttpVerb($this->_cPtr,$newVal);
	}

	/**
	 * The HTTP version in the request header.  Defaults to 1.1.  Can only be set to 1.0 or 1.1.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#HttpVersion
	 * @param CkString $str
	 */
	function get_HttpVersion($str) {
		CkHttpRequest_get_HttpVersion($this->_cPtr,$str);
	}

	/**
	 * The HTTP version in the request header.  Defaults to 1.1.  Can only be set to 1.0 or 1.1.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#HttpVersion
	 * @return ?string
	 */
	function httpVersion() {
		return CkHttpRequest_httpVersion($this->_cPtr);
	}

	/**
	 * The HTTP version in the request header.  Defaults to 1.1.  Can only be set to 1.0 or 1.1.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#HttpVersion
	 * @param ?string $newVal
	 */
	function put_HttpVersion($newVal) {
		CkHttpRequest_put_HttpVersion($this->_cPtr,$newVal);
	}

	/**
	 * Provides HTML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#LastErrorHtml
	 * @param CkString $str
	 */
	function get_LastErrorHtml($str) {
		CkHttpRequest_get_LastErrorHtml($this->_cPtr,$str);
	}

	/**
	 * Provides HTML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#LastErrorHtml
	 * @return ?string
	 */
	function lastErrorHtml() {
		return CkHttpRequest_lastErrorHtml($this->_cPtr);
	}

	/**
	 * Provides plain text information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#LastErrorText
	 * @param CkString $str
	 */
	function get_LastErrorText($str) {
		CkHttpRequest_get_LastErrorText($this->_cPtr,$str);
	}

	/**
	 * Provides plain text information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#LastErrorText
	 * @return ?string
	 */
	function lastErrorText() {
		return CkHttpRequest_lastErrorText($this->_cPtr);
	}

	/**
	 * Provides XML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#LastErrorXml
	 * @param CkString $str
	 */
	function get_LastErrorXml($str) {
		CkHttpRequest_get_LastErrorXml($this->_cPtr,$str);
	}

	/**
	 * Provides XML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#LastErrorXml
	 * @return ?string
	 */
	function lastErrorXml() {
		return CkHttpRequest_lastErrorXml($this->_cPtr);
	}

	/**
	 * Indicates the success or failure of the most recent method call: _TRUE_ means success, _FALSE_ means failure. This property remains unchanged by property setters or getters.  This method is present to address challenges in checking for null or Nothing returns in certain programming languages.  Note: This property does not apply to methods that return integer values or to boolean-returning methods where the boolean does not indicate success or failure.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#LastMethodSuccess
	 * @return bool
	 */
	function get_LastMethodSuccess() {
		return CkHttpRequest_get_LastMethodSuccess($this->_cPtr);
	}

	/**
	 * Indicates the success or failure of the most recent method call: _TRUE_ means success, _FALSE_ means failure. This property remains unchanged by property setters or getters.  This method is present to address challenges in checking for null or Nothing returns in certain programming languages.  Note: This property does not apply to methods that return integer values or to boolean-returning methods where the boolean does not indicate success or failure.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#LastMethodSuccess
	 * @param bool $newVal
	 */
	function put_LastMethodSuccess($newVal) {
		CkHttpRequest_put_LastMethodSuccess($this->_cPtr,$newVal);
	}

	/**
	 * Returns the number of request header fields.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#NumHeaderFields
	 * @return int
	 */
	function get_NumHeaderFields() {
		return CkHttpRequest_get_NumHeaderFields($this->_cPtr);
	}

	/**
	 * Returns the number of query parameters.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#NumParams
	 * @return int
	 */
	function get_NumParams() {
		return CkHttpRequest_get_NumParams($this->_cPtr);
	}

	/**
	 * The path of the resource requested.  A path of / indicates the default document of a domain. Explaining the Parts of a URL
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#Path
	 * @param CkString $str
	 */
	function get_Path($str) {
		CkHttpRequest_get_Path($this->_cPtr,$str);
	}

	/**
	 * The path of the resource requested.  A path of / indicates the default document of a domain. Explaining the Parts of a URL
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#Path
	 * @return ?string
	 */
	function path() {
		return CkHttpRequest_path($this->_cPtr);
	}

	/**
	 * The path of the resource requested.  A path of / indicates the default document of a domain. Explaining the Parts of a URL
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#Path
	 * @param ?string $newVal
	 */
	function put_Path($newVal) {
		CkHttpRequest_put_Path($this->_cPtr,$newVal);
	}

	/**
	 * Controls whether the charset is explicitly included in the content-type header field of the HTTP POST request.  The default value of this property is _FALSE_.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#SendCharset
	 * @return bool
	 */
	function get_SendCharset() {
		return CkHttpRequest_get_SendCharset($this->_cPtr);
	}

	/**
	 * Controls whether the charset is explicitly included in the content-type header field of the HTTP POST request.  The default value of this property is _FALSE_.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#SendCharset
	 * @param bool $newVal
	 */
	function put_SendCharset($newVal) {
		CkHttpRequest_put_SendCharset($this->_cPtr,$newVal);
	}

	/**
	 * If set to _TRUE_, then the contents of LastErrorText (or LastErrorXml, or LastErrorHtml) may contain more verbose information. The default value is _FALSE_.  Verbose logging should only be used for debugging.  The potentially large quantity of logged information may adversely affect peformance.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#VerboseLogging
	 * @return bool
	 */
	function get_VerboseLogging() {
		return CkHttpRequest_get_VerboseLogging($this->_cPtr);
	}

	/**
	 * If set to _TRUE_, then the contents of LastErrorText (or LastErrorXml, or LastErrorHtml) may contain more verbose information. The default value is _FALSE_.  Verbose logging should only be used for debugging.  The potentially large quantity of logged information may adversely affect peformance.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#VerboseLogging
	 * @param bool $newVal
	 */
	function put_VerboseLogging($newVal) {
		CkHttpRequest_put_VerboseLogging($this->_cPtr,$newVal);
	}

	/**
	 * Version of the component/library, such as "10.1.0"
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#Version
	 * @param CkString $str
	 */
	function get_Version($str) {
		CkHttpRequest_get_Version($this->_cPtr,$str);
	}

	/**
	 * Version of the component/library, such as "10.1.0"
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#Version
	 * @return ?string
	 */
	function version() {
		return CkHttpRequest_version($this->_cPtr);
	}

	/**
	 * Adds a file to an upload request where the contents of the file come from ARG3.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#AddBdForUpload
	 * @param ?string $name
	 * @param ?string $remoteFilename
	 * @param CkBinData $byteData
	 * @param ?string $contentType
	 * @return bool
	 */
	function AddBdForUpload($name,$remoteFilename,$byteData,$contentType) {
		return CkHttpRequest_AddBdForUpload($this->_cPtr,$name,$remoteFilename,$byteData,$contentType);
	}

	/**
	 * Adds a file to an upload request where the contents of the file come from an in-memory byte array.  To create a file upload request, set the ContentType property = multipart/form-data and then call AddBytesForUpload, AddStringForUpload, or AddFileForUpload for each file to be uploaded. ARG1 is an arbitrary name.  (In HTML, it is the form field name of the input tag.)
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#AddBytesForUpload
	 * @param ?string $name
	 * @param ?string $remoteFileName
	 * @param CkByteData $byteData
	 * @return bool
	 */
	function AddBytesForUpload($name,$remoteFileName,$byteData) {
		return CkHttpRequest_AddBytesForUpload($this->_cPtr,$name,$remoteFileName,$byteData);
	}

	/**
	 * Same as AddBytesForUpload, but allows the Content-Type header field to be directly specified.  (Otherwise, the Content-Type header is automatically determined based on the ARG2's file extension.)
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#AddBytesForUpload2
	 * @param ?string $name
	 * @param ?string $remoteFileName
	 * @param CkByteData $byteData
	 * @param ?string $contentType
	 * @return bool
	 */
	function AddBytesForUpload2($name,$remoteFileName,$byteData,$contentType) {
		return CkHttpRequest_AddBytesForUpload2($this->_cPtr,$name,$remoteFileName,$byteData,$contentType);
	}

	/**
	 * Adds a file to an upload request.  To create a file upload request, set the ContentType property = multipart/form-data  and then call AddFileForUpload, AddBytesForUpload, or AddStringForUpload for each file to be uploaded.   This method does not read the file into memory.  When the upload occurs, the data is streamed directly from the file, thus allowing for very large files to be uploaded without consuming large amounts of memory.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#AddFileForUpload
	 * @param ?string $name
	 * @param ?string $filePath
	 * @return bool
	 */
	function AddFileForUpload($name,$filePath) {
		return CkHttpRequest_AddFileForUpload($this->_cPtr,$name,$filePath);
	}

	/**
	 * Same as AddFileForUpload, but allows the Content-Type header field to be directly specified.  (Otherwise, the Content-Type header is automatically determined based on the file extension.)
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#AddFileForUpload2
	 * @param ?string $name
	 * @param ?string $filePath
	 * @param ?string $contentType
	 * @return bool
	 */
	function AddFileForUpload2($name,$filePath,$contentType) {
		return CkHttpRequest_AddFileForUpload2($this->_cPtr,$name,$filePath,$contentType);
	}

	/**
	 * Adds a request header to the HTTP request.  If a header having the same field name is already present, this method replaces it.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#AddHeader
	 * @param ?string $name
	 * @param ?string $value
	 */
	function AddHeader($name,$value) {
		CkHttpRequest_AddHeader($this->_cPtr,$name,$value);
	}

	/**
	 * Computes the Amazon MWS signature using the ARG2 and adds the Signature parameter to the request.  This method should be called for all Amazon Marketplace Web Service (Amazon MWS) HTTP requests.   It should be called after all request parameters have been added.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#AddMwsSignature
	 * @param ?string $domain
	 * @param ?string $mwsSecretKey
	 * @return bool
	 */
	function AddMwsSignature($domain,$mwsSecretKey) {
		return CkHttpRequest_AddMwsSignature($this->_cPtr,$domain,$mwsSecretKey);
	}

	/**
	 * Adds a request query parameter (name/value pair) to the HTTP request.  The ARG1 and ARG2 strings passed to this method should not be URL encoded.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#AddParam
	 * @param ?string $name
	 * @param ?string $value
	 */
	function AddParam($name,$value) {
		CkHttpRequest_AddParam($this->_cPtr,$name,$value);
	}

	/**
	 * Same as AddFileForUpload, but the upload data comes from an in-memory string instead of a file.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#AddStringForUpload
	 * @param ?string $name
	 * @param ?string $filename
	 * @param ?string $strData
	 * @param ?string $charset
	 * @return bool
	 */
	function AddStringForUpload($name,$filename,$strData,$charset) {
		return CkHttpRequest_AddStringForUpload($this->_cPtr,$name,$filename,$strData,$charset);
	}

	/**
	 * Same as AddStringForUpload, but allows the Content-Type header field to be directly specified.  (Otherwise, the Content-Type header is automatically determined based on the ARG2's file extension.)
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#AddStringForUpload2
	 * @param ?string $name
	 * @param ?string $filename
	 * @param ?string $strData
	 * @param ?string $charset
	 * @param ?string $contentType
	 * @return bool
	 */
	function AddStringForUpload2($name,$filename,$strData,$charset,$contentType) {
		return CkHttpRequest_AddStringForUpload2($this->_cPtr,$name,$filename,$strData,$charset,$contentType);
	}

	/**
	 * Adds a request header to the Nth sub-header of the HTTP request.  If a header having the same field name is already present, this method replaces it.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#AddSubHeader
	 * @param int $index
	 * @param ?string $name
	 * @param ?string $value
	 * @return bool
	 */
	function AddSubHeader($index,$name,$value) {
		return CkHttpRequest_AddSubHeader($this->_cPtr,$index,$name,$value);
	}

	/**
	 * The same as GenerateRequestText, except the generated request is written to the file specified by ARG1.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#GenerateRequestFile
	 * @param ?string $path
	 * @return bool
	 */
	function GenerateRequestFile($path) {
		return CkHttpRequest_GenerateRequestFile($this->_cPtr,$path);
	}

	/**
	 * Returns the request text that would be sent if Http.SynchronousRequest was called.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#GenerateRequestText
	 * @return ?string
	 */
	function generateRequestText() {
		return CkHttpRequest_generateRequestText($this->_cPtr);
	}

	/**
	 * Returns the value of a request header field.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#GetHeaderField
	 * @param ?string $name
	 * @return ?string
	 */
	function getHeaderField($name) {
		return CkHttpRequest_getHeaderField($this->_cPtr,$name);
	}

	/**
	 * Returns the value of a request header field.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#GetHeaderField
	 * @param ?string $name
	 * @return ?string
	 */
	function headerField($name) {
		return CkHttpRequest_headerField($this->_cPtr,$name);
	}

	/**
	 * Returns the Nth request header field name.  Indexing begins at 0, and the number of request header fields is specified by the  NumHeaderFields property.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#GetHeaderName
	 * @param int $index
	 * @return ?string
	 */
	function getHeaderName($index) {
		return CkHttpRequest_getHeaderName($this->_cPtr,$index);
	}

	/**
	 * Returns the Nth request header field name.  Indexing begins at 0, and the number of request header fields is specified by the  NumHeaderFields property.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#GetHeaderName
	 * @param int $index
	 * @return ?string
	 */
	function headerName($index) {
		return CkHttpRequest_headerName($this->_cPtr,$index);
	}

	/**
	 * Returns the Nth request header field value. Indexing begins at 0, and the number of request header fields is specified by the  NumHeaderFields property.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#GetHeaderValue
	 * @param int $index
	 * @return ?string
	 */
	function getHeaderValue($index) {
		return CkHttpRequest_getHeaderValue($this->_cPtr,$index);
	}

	/**
	 * Returns the Nth request header field value. Indexing begins at 0, and the number of request header fields is specified by the  NumHeaderFields property.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#GetHeaderValue
	 * @param int $index
	 * @return ?string
	 */
	function headerValue($index) {
		return CkHttpRequest_headerValue($this->_cPtr,$index);
	}

	/**
	 * Returns a request query parameter value by name.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#GetParam
	 * @param ?string $name
	 * @return ?string
	 */
	function getParam($name) {
		return CkHttpRequest_getParam($this->_cPtr,$name);
	}

	/**
	 * Returns a request query parameter value by name.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#GetParam
	 * @param ?string $name
	 * @return ?string
	 */
	function param($name) {
		return CkHttpRequest_param($this->_cPtr,$name);
	}

	/**
	 * Returns the Nth request query parameter field name. Indexing begins at 0, and the number of request query parameter fields is specified by the NumParams property.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#GetParamName
	 * @param int $index
	 * @return ?string
	 */
	function getParamName($index) {
		return CkHttpRequest_getParamName($this->_cPtr,$index);
	}

	/**
	 * Returns the Nth request query parameter field name. Indexing begins at 0, and the number of request query parameter fields is specified by the NumParams property.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#GetParamName
	 * @param int $index
	 * @return ?string
	 */
	function paramName($index) {
		return CkHttpRequest_paramName($this->_cPtr,$index);
	}

	/**
	 * Returns the Nth request query parameter field value. Indexing begins at 0, and the number of request query parameter fields is specified by the NumParams property.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#GetParamValue
	 * @param int $index
	 * @return ?string
	 */
	function getParamValue($index) {
		return CkHttpRequest_getParamValue($this->_cPtr,$index);
	}

	/**
	 * Returns the Nth request query parameter field value. Indexing begins at 0, and the number of request query parameter fields is specified by the NumParams property.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#GetParamValue
	 * @param int $index
	 * @return ?string
	 */
	function paramValue($index) {
		return CkHttpRequest_paramValue($this->_cPtr,$index);
	}

	/**
	 * Returns the request parameters in URL encoded form (i.e. in the exact form that would be sent if the ContentType property was application/x-www-form-urlencoded).   For example, if a request has two params:  param1=abc 123 and param2=abc-123, then GetUrlEncodedParams would return  abc+123&param2=abc%2D123
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#GetUrlEncodedParams
	 * @return ?string
	 */
	function getUrlEncodedParams() {
		return CkHttpRequest_getUrlEncodedParams($this->_cPtr);
	}

	/**
	 * Returns the request parameters in URL encoded form (i.e. in the exact form that would be sent if the ContentType property was application/x-www-form-urlencoded).   For example, if a request has two params:  param1=abc 123 and param2=abc-123, then GetUrlEncodedParams would return  abc+123&param2=abc%2D123
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#GetUrlEncodedParams
	 * @return ?string
	 */
	function urlEncodedParams() {
		return CkHttpRequest_urlEncodedParams($this->_cPtr);
	}

	/**
	 * Uses the contents of the ARG1 as the HTTP request body.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#LoadBodyFromBd
	 * @param CkBinData $requestBody
	 * @return bool
	 */
	function LoadBodyFromBd($requestBody) {
		return CkHttpRequest_LoadBodyFromBd($this->_cPtr,$requestBody);
	}

	/**
	 * The HTTP protocol is such that all HTTP requests are MIME.  For non-multipart requests, this method may be called to set the MIME body of the HTTP request to the exact contents of the ARG1.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#LoadBodyFromBytes
	 * @param CkByteData $byteData
	 * @return bool
	 */
	function LoadBodyFromBytes($byteData) {
		return CkHttpRequest_LoadBodyFromBytes($this->_cPtr,$byteData);
	}

	/**
	 * The HTTP protocol is such that all HTTP requests are MIME.  For non-multipart requests, this method may be called to set the MIME body of the HTTP request to the exact contents of ARG1.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#LoadBodyFromFile
	 * @param ?string $filePath
	 * @return bool
	 */
	function LoadBodyFromFile($filePath) {
		return CkHttpRequest_LoadBodyFromFile($this->_cPtr,$filePath);
	}

	/**
	 * Uses the contents of the ARG1 as the HTTP request body.   The ARG2 indicates the binary representation of the string, such as utf-8, utf-16, iso-8859-*, windows-125*, etc.  Any of the character encodings supported at the link below are valid.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#LoadBodyFromSb
	 * @param CkStringBuilder $requestBody
	 * @param ?string $charset
	 * @return bool
	 */
	function LoadBodyFromSb($requestBody,$charset) {
		return CkHttpRequest_LoadBodyFromSb($this->_cPtr,$requestBody,$charset);
	}

	/**
	 * The HTTP protocol is such that all HTTP requests are MIME.  For non-multipart requests, this method may be called to set the MIME body of the HTTP request to the exact contents of ARG1.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#LoadBodyFromString
	 * @param ?string $bodyStr
	 * @param ?string $charset
	 * @return bool
	 */
	function LoadBodyFromString($bodyStr,$charset) {
		return CkHttpRequest_LoadBodyFromString($this->_cPtr,$bodyStr,$charset);
	}

	/**
	 * Removes all request parameters.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#RemoveAllParams
	 */
	function RemoveAllParams() {
		CkHttpRequest_RemoveAllParams($this->_cPtr);
	}

	/**
	 * Removes all occurrences of a HTTP request header field.  Always returns _TRUE_.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#RemoveHeader
	 * @param ?string $name
	 * @return bool
	 */
	function RemoveHeader($name) {
		return CkHttpRequest_RemoveHeader($this->_cPtr,$name);
	}

	/**
	 * Removes a single HTTP request parameter by name.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#RemoveParam
	 * @param ?string $name
	 */
	function RemoveParam($name) {
		CkHttpRequest_RemoveParam($this->_cPtr,$name);
	}

	/**
	 * Parses a URL and sets the Path and query parameters (NumParams, GetParam, GetParamName, GetParamValue).
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#SetFromUrl
	 * @param ?string $url
	 */
	function SetFromUrl($url) {
		CkHttpRequest_SetFromUrl($this->_cPtr,$url);
	}

	/**
	 * Useful for sending HTTP requests where the body is a very large file.  For example, to send an XML HttpRequest containing a very large XML document, one would set the HttpVerb = POST, the ContentType = text/xml, and then call StreamBodyFromFile to indicate that the XML body of the request is to be streamed directly from a file.  When the HTTP request is actually sent, the body is streamed directly from the file, and thus the file never needs to be loaded in its entirety in memory.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#StreamBodyFromFile
	 * @param ?string $filePath
	 * @return bool
	 */
	function StreamBodyFromFile($filePath) {
		return CkHttpRequest_StreamBodyFromFile($this->_cPtr,$filePath);
	}

	/**
	 * This method is the same as StreamBodyFromFile, but allows for an offset and number of bytes to be specified.  The ARG2 and ARG3 are integers passed as strings.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHttpRequestRef.html#StreamChunkFromFile
	 * @param ?string $path
	 * @param ?string $offset
	 * @param ?string $numBytes
	 * @return bool
	 */
	function StreamChunkFromFile($path,$offset,$numBytes) {
		return CkHttpRequest_StreamChunkFromFile($this->_cPtr,$path,$offset,$numBytes);
	}
}
