<?php

/* CkHtmlToText.php -- Chilkat PHP extension proxy class CkHtmlToText.
 * Generated by ChilkatApi/GenCkPhp.cs for Chilkat v11.6.1 -- do not edit.
 * Reference documentation: https://www.chilkatsoft.com/refdoc/ */

/**
 * Convert HTML into readable plain text with control over links, wrapping, and encoding.
 *
 * Chilkat.HtmlToText converts HTML content into readable plain text. It can decode HTML entities, wrap output at a configurable right margin, optionally include or suppress hyperlink URLs, convert HTML supplied as a string or StringBuilder, and read or write files using an explicit character encoding.
 *
 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToTextRef.html
 */
class CkHtmlToText {
	public $_cPtr=null;
	protected $_pData=array();

	function __set($var,$value) {
		if ($var === 'thisown') return swig_chilkat_alter_newobject($this->_cPtr,$value);
		$this->_pData[$var] = $value;
	}

	function __get($var) {
		if ($var === 'thisown') return swig_chilkat_get_newobject($this->_cPtr);
		return $this->_pData[$var];
	}

	function __isset($var) {
		if ($var === 'thisown') return true;
		return array_key_exists($var, $this->_pData);
	}

	function __construct($res=null) {
		if (is_resource($res) && get_resource_type($res) === '_p_CkHtmlToText') {
			$this->_cPtr=$res;
			return;
		}
		$this->_cPtr=new_CkHtmlToText();
	}

	/**
	 * When true, strings passed to and returned from the object are UTF-8. When false (the default), they are ANSI (the locale's 8-bit character encoding).
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToTextRef.html
	 * @return bool
	 */
	function get_Utf8() {
		return CkHtmlToText_get_Utf8($this->_cPtr);
	}

	/**
	 * When true, strings passed to and returned from the object are UTF-8. When false (the default), they are ANSI (the locale's 8-bit character encoding).
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToTextRef.html
	 * @param bool $b
	 */
	function put_Utf8($b) {
		CkHtmlToText_put_Utf8($this->_cPtr,$b);
	}

	/**
	 * If set to a file path, this property logs the LastErrorText of each Chilkat method or property call to the specified file. This logging helps identify the context and history of Chilkat calls leading up to any crash or hang, aiding in debugging.  Enabling the VerboseLogging property provides more detailed information.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToTextRef.html#DebugLogFilePath
	 * @param CkString $str
	 */
	function get_DebugLogFilePath($str) {
		CkHtmlToText_get_DebugLogFilePath($this->_cPtr,$str);
	}

	/**
	 * If set to a file path, this property logs the LastErrorText of each Chilkat method or property call to the specified file. This logging helps identify the context and history of Chilkat calls leading up to any crash or hang, aiding in debugging.  Enabling the VerboseLogging property provides more detailed information.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToTextRef.html#DebugLogFilePath
	 * @return ?string
	 */
	function debugLogFilePath() {
		return CkHtmlToText_debugLogFilePath($this->_cPtr);
	}

	/**
	 * If set to a file path, this property logs the LastErrorText of each Chilkat method or property call to the specified file. This logging helps identify the context and history of Chilkat calls leading up to any crash or hang, aiding in debugging.  Enabling the VerboseLogging property provides more detailed information.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToTextRef.html#DebugLogFilePath
	 * @param ?string $newVal
	 */
	function put_DebugLogFilePath($newVal) {
		CkHtmlToText_put_DebugLogFilePath($this->_cPtr,$newVal);
	}

	/**
	 * Controls whether HTML character references are decoded when converting HTML to plain text. The default value is _TRUE_.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToTextRef.html#DecodeHtmlEntities
	 * @return bool
	 */
	function get_DecodeHtmlEntities() {
		return CkHtmlToText_get_DecodeHtmlEntities($this->_cPtr);
	}

	/**
	 * Controls whether HTML character references are decoded when converting HTML to plain text. The default value is _TRUE_.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToTextRef.html#DecodeHtmlEntities
	 * @param bool $newVal
	 */
	function put_DecodeHtmlEntities($newVal) {
		CkHtmlToText_put_DecodeHtmlEntities($this->_cPtr,$newVal);
	}

	/**
	 * Provides HTML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToTextRef.html#LastErrorHtml
	 * @param CkString $str
	 */
	function get_LastErrorHtml($str) {
		CkHtmlToText_get_LastErrorHtml($this->_cPtr,$str);
	}

	/**
	 * Provides HTML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToTextRef.html#LastErrorHtml
	 * @return ?string
	 */
	function lastErrorHtml() {
		return CkHtmlToText_lastErrorHtml($this->_cPtr);
	}

	/**
	 * Provides plain text information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToTextRef.html#LastErrorText
	 * @param CkString $str
	 */
	function get_LastErrorText($str) {
		CkHtmlToText_get_LastErrorText($this->_cPtr,$str);
	}

	/**
	 * Provides plain text information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToTextRef.html#LastErrorText
	 * @return ?string
	 */
	function lastErrorText() {
		return CkHtmlToText_lastErrorText($this->_cPtr);
	}

	/**
	 * Provides XML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToTextRef.html#LastErrorXml
	 * @param CkString $str
	 */
	function get_LastErrorXml($str) {
		CkHtmlToText_get_LastErrorXml($this->_cPtr,$str);
	}

	/**
	 * Provides XML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToTextRef.html#LastErrorXml
	 * @return ?string
	 */
	function lastErrorXml() {
		return CkHtmlToText_lastErrorXml($this->_cPtr);
	}

	/**
	 * Indicates the success or failure of the most recent method call: _TRUE_ means success, _FALSE_ means failure. This property remains unchanged by property setters or getters.  This method is present to address challenges in checking for null or Nothing returns in certain programming languages.  Note: This property does not apply to methods that return integer values or to boolean-returning methods where the boolean does not indicate success or failure.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToTextRef.html#LastMethodSuccess
	 * @return bool
	 */
	function get_LastMethodSuccess() {
		return CkHtmlToText_get_LastMethodSuccess($this->_cPtr);
	}

	/**
	 * Indicates the success or failure of the most recent method call: _TRUE_ means success, _FALSE_ means failure. This property remains unchanged by property setters or getters.  This method is present to address challenges in checking for null or Nothing returns in certain programming languages.  Note: This property does not apply to methods that return integer values or to boolean-returning methods where the boolean does not indicate success or failure.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToTextRef.html#LastMethodSuccess
	 * @param bool $newVal
	 */
	function put_LastMethodSuccess($newVal) {
		CkHtmlToText_put_LastMethodSuccess($this->_cPtr,$newVal);
	}

	/**
	 * Controls line wrapping in the generated plain text. The default value is 80. As a line approaches the configured margin, Chilkat attempts to wrap at a SPACE character. Set this property to 0 to disable right-margin wrapping.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToTextRef.html#RightMargin
	 * @return int
	 */
	function get_RightMargin() {
		return CkHtmlToText_get_RightMargin($this->_cPtr);
	}

	/**
	 * Controls line wrapping in the generated plain text. The default value is 80. As a line approaches the configured margin, Chilkat attempts to wrap at a SPACE character. Set this property to 0 to disable right-margin wrapping.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToTextRef.html#RightMargin
	 * @param int $newVal
	 */
	function put_RightMargin($newVal) {
		CkHtmlToText_put_RightMargin($this->_cPtr,$newVal);
	}

	/**
	 * Controls whether hyperlink destination URLs are included in the generated plain text. The default value is _TRUE_.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToTextRef.html#SuppressLinks
	 * @return bool
	 */
	function get_SuppressLinks() {
		return CkHtmlToText_get_SuppressLinks($this->_cPtr);
	}

	/**
	 * Controls whether hyperlink destination URLs are included in the generated plain text. The default value is _TRUE_.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToTextRef.html#SuppressLinks
	 * @param bool $newVal
	 */
	function put_SuppressLinks($newVal) {
		CkHtmlToText_put_SuppressLinks($this->_cPtr,$newVal);
	}

	/**
	 * Specifies uncommon HTML-to-text conversion options as a comma-separated list of keywords. The default is the empty string, which is appropriate for normal use.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToTextRef.html#UncommonOptions
	 * @param CkString $str
	 */
	function get_UncommonOptions($str) {
		CkHtmlToText_get_UncommonOptions($this->_cPtr,$str);
	}

	/**
	 * Specifies uncommon HTML-to-text conversion options as a comma-separated list of keywords. The default is the empty string, which is appropriate for normal use.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToTextRef.html#UncommonOptions
	 * @return ?string
	 */
	function uncommonOptions() {
		return CkHtmlToText_uncommonOptions($this->_cPtr);
	}

	/**
	 * Specifies uncommon HTML-to-text conversion options as a comma-separated list of keywords. The default is the empty string, which is appropriate for normal use.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToTextRef.html#UncommonOptions
	 * @param ?string $newVal
	 */
	function put_UncommonOptions($newVal) {
		CkHtmlToText_put_UncommonOptions($this->_cPtr,$newVal);
	}

	/**
	 * If set to _TRUE_, then the contents of LastErrorText (or LastErrorXml, or LastErrorHtml) may contain more verbose information. The default value is _FALSE_.  Verbose logging should only be used for debugging.  The potentially large quantity of logged information may adversely affect peformance.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToTextRef.html#VerboseLogging
	 * @return bool
	 */
	function get_VerboseLogging() {
		return CkHtmlToText_get_VerboseLogging($this->_cPtr);
	}

	/**
	 * If set to _TRUE_, then the contents of LastErrorText (or LastErrorXml, or LastErrorHtml) may contain more verbose information. The default value is _FALSE_.  Verbose logging should only be used for debugging.  The potentially large quantity of logged information may adversely affect peformance.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToTextRef.html#VerboseLogging
	 * @param bool $newVal
	 */
	function put_VerboseLogging($newVal) {
		CkHtmlToText_put_VerboseLogging($this->_cPtr,$newVal);
	}

	/**
	 * Version of the component/library, such as "10.1.0"
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToTextRef.html#Version
	 * @param CkString $str
	 */
	function get_Version($str) {
		CkHtmlToText_get_Version($this->_cPtr,$str);
	}

	/**
	 * Version of the component/library, such as "10.1.0"
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToTextRef.html#Version
	 * @return ?string
	 */
	function version() {
		return CkHtmlToText_version($this->_cPtr);
	}

	/**
	 * Reads an entire text file and returns its contents as a string. The srcCharset argument specifies the character encoding used to decode the file bytes, such as utf-8 or iso-8859-1.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToTextRef.html#ReadFileToString
	 * @param ?string $filename
	 * @param ?string $srcCharset
	 * @return ?string
	 * @deprecated
	 */
	function readFileToString($filename,$srcCharset) {
		return CkHtmlToText_readFileToString($this->_cPtr,$filename,$srcCharset);
	}

	/**
	 * Converts the HTML in html to readable plain text and returns the result.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToTextRef.html#ToText
	 * @param ?string $html
	 * @return ?string
	 */
	function toText($html) {
		return CkHtmlToText_toText($this->_cPtr,$html);
	}

	/**
	 * Converts the HTML currently contained in sb to plain text in place. On success, the same StringBuilder contains the converted plain-text result.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToTextRef.html#ToTextSb
	 * @param CkStringBuilder $sb
	 * @return bool
	 */
	function ToTextSb($sb) {
		return CkHtmlToText_ToTextSb($this->_cPtr,$sb);
	}

	/**
	 * Writes stringToWrite to filename using the character encoding specified by charset. The string is converted to that charset as it is written. Common values include utf-8 and iso-8859-1.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkHtmlToTextRef.html#WriteStringToFile
	 * @param ?string $stringToWrite
	 * @param ?string $filename
	 * @param ?string $charset
	 * @return bool
	 * @deprecated
	 */
	function WriteStringToFile($stringToWrite,$filename,$charset) {
		return CkHtmlToText_WriteStringToFile($this->_cPtr,$stringToWrite,$filename,$charset);
	}
}
