<?php

/* CkJs.php -- Chilkat PHP extension proxy class CkJs.
 * Generated by ChilkatApi/GenCkPhp.cs for Chilkat v11.6.1 -- do not edit.
 * Reference documentation: https://www.chilkatsoft.com/refdoc/ */

/**
 * Execute sandboxed JavaScript inside an application with controlled access to Chilkat features.
 *
 * Use Chilkat.Js when an application needs to execute JavaScript internally while retaining control over what the script is allowed to access. By default, scripts run in a closed sandbox with the JavaScript language and standard library available, but without filesystem, network, or Chilkat class access unless the host application explicitly enables those capabilities.
 *
 * @see https://www.chilkatsoft.com/refdoc/phpCkJsRef.html
 */
class CkJs {
	public $_cPtr=null;
	protected $_pData=array();

	function __set($var,$value) {
		if ($var === 'thisown') return swig_chilkat_alter_newobject($this->_cPtr,$value);
		$this->_pData[$var] = $value;
	}

	function __get($var) {
		if ($var === 'thisown') return swig_chilkat_get_newobject($this->_cPtr);
		return $this->_pData[$var];
	}

	function __isset($var) {
		if ($var === 'thisown') return true;
		return array_key_exists($var, $this->_pData);
	}

	function __construct($res=null) {
		if (is_resource($res) && get_resource_type($res) === '_p_CkJs') {
			$this->_cPtr=$res;
			return;
		}
		$this->_cPtr=new_CkJs();
	}

	/**
	 * When true, strings passed to and returned from the object are UTF-8. When false (the default), they are ANSI (the locale's 8-bit character encoding).
	 * @see https://www.chilkatsoft.com/refdoc/phpCkJsRef.html
	 * @return bool
	 */
	function get_Utf8() {
		return CkJs_get_Utf8($this->_cPtr);
	}

	/**
	 * When true, strings passed to and returned from the object are UTF-8. When false (the default), they are ANSI (the locale's 8-bit character encoding).
	 * @see https://www.chilkatsoft.com/refdoc/phpCkJsRef.html
	 * @param bool $b
	 */
	function put_Utf8($b) {
		CkJs_put_Utf8($this->_cPtr,$b);
	}

	/**
	 * Sets the event callback object.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkJsRef.html
	 * @param ?CkBaseProgress $progress
	 */
	function put_EventCallbackObject($progress) {
		CkJs_put_EventCallbackObject($this->_cPtr,$progress);
	}

	/**
	 * If set to a file path, this property logs the LastErrorText of each Chilkat method or property call to the specified file. This logging helps identify the context and history of Chilkat calls leading up to any crash or hang, aiding in debugging.  Enabling the VerboseLogging property provides more detailed information.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkJsRef.html#DebugLogFilePath
	 * @param CkString $str
	 */
	function get_DebugLogFilePath($str) {
		CkJs_get_DebugLogFilePath($this->_cPtr,$str);
	}

	/**
	 * If set to a file path, this property logs the LastErrorText of each Chilkat method or property call to the specified file. This logging helps identify the context and history of Chilkat calls leading up to any crash or hang, aiding in debugging.  Enabling the VerboseLogging property provides more detailed information.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkJsRef.html#DebugLogFilePath
	 * @return ?string
	 */
	function debugLogFilePath() {
		return CkJs_debugLogFilePath($this->_cPtr);
	}

	/**
	 * If set to a file path, this property logs the LastErrorText of each Chilkat method or property call to the specified file. This logging helps identify the context and history of Chilkat calls leading up to any crash or hang, aiding in debugging.  Enabling the VerboseLogging property provides more detailed information.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkJsRef.html#DebugLogFilePath
	 * @param ?string $newVal
	 */
	function put_DebugLogFilePath($newVal) {
		CkJs_put_DebugLogFilePath($this->_cPtr,$newVal);
	}

	/**
	 * Provides HTML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkJsRef.html#LastErrorHtml
	 * @param CkString $str
	 */
	function get_LastErrorHtml($str) {
		CkJs_get_LastErrorHtml($this->_cPtr,$str);
	}

	/**
	 * Provides HTML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkJsRef.html#LastErrorHtml
	 * @return ?string
	 */
	function lastErrorHtml() {
		return CkJs_lastErrorHtml($this->_cPtr);
	}

	/**
	 * Provides plain text information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkJsRef.html#LastErrorText
	 * @param CkString $str
	 */
	function get_LastErrorText($str) {
		CkJs_get_LastErrorText($this->_cPtr,$str);
	}

	/**
	 * Provides plain text information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkJsRef.html#LastErrorText
	 * @return ?string
	 */
	function lastErrorText() {
		return CkJs_lastErrorText($this->_cPtr);
	}

	/**
	 * Provides XML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkJsRef.html#LastErrorXml
	 * @param CkString $str
	 */
	function get_LastErrorXml($str) {
		CkJs_get_LastErrorXml($this->_cPtr,$str);
	}

	/**
	 * Provides XML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkJsRef.html#LastErrorXml
	 * @return ?string
	 */
	function lastErrorXml() {
		return CkJs_lastErrorXml($this->_cPtr);
	}

	/**
	 * Indicates the success or failure of the most recent method call: _TRUE_ means success, _FALSE_ means failure. This property remains unchanged by property setters or getters.  This method is present to address challenges in checking for null or Nothing returns in certain programming languages.  Note: This property does not apply to methods that return integer values or to boolean-returning methods where the boolean does not indicate success or failure.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkJsRef.html#LastMethodSuccess
	 * @return bool
	 */
	function get_LastMethodSuccess() {
		return CkJs_get_LastMethodSuccess($this->_cPtr);
	}

	/**
	 * Indicates the success or failure of the most recent method call: _TRUE_ means success, _FALSE_ means failure. This property remains unchanged by property setters or getters.  This method is present to address challenges in checking for null or Nothing returns in certain programming languages.  Note: This property does not apply to methods that return integer values or to boolean-returning methods where the boolean does not indicate success or failure.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkJsRef.html#LastMethodSuccess
	 * @param bool $newVal
	 */
	function put_LastMethodSuccess($newVal) {
		CkJs_put_LastMethodSuccess($this->_cPtr,$newVal);
	}

	/**
	 * Specify a timeout in seconds to prevent JavaScript from running indefinitely, such as in an infinite loop. By default, the value is 0, meaning no timeout is set and infinite loops will continue forever.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkJsRef.html#TimeoutSeconds
	 * @return int
	 */
	function get_TimeoutSeconds() {
		return CkJs_get_TimeoutSeconds($this->_cPtr);
	}

	/**
	 * Specify a timeout in seconds to prevent JavaScript from running indefinitely, such as in an infinite loop. By default, the value is 0, meaning no timeout is set and infinite loops will continue forever.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkJsRef.html#TimeoutSeconds
	 * @param int $newVal
	 */
	function put_TimeoutSeconds($newVal) {
		CkJs_put_TimeoutSeconds($this->_cPtr,$newVal);
	}

	/**
	 * If set to _TRUE_, then the contents of LastErrorText (or LastErrorXml, or LastErrorHtml) may contain more verbose information. The default value is _FALSE_.  Verbose logging should only be used for debugging.  The potentially large quantity of logged information may adversely affect peformance.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkJsRef.html#VerboseLogging
	 * @return bool
	 */
	function get_VerboseLogging() {
		return CkJs_get_VerboseLogging($this->_cPtr);
	}

	/**
	 * If set to _TRUE_, then the contents of LastErrorText (or LastErrorXml, or LastErrorHtml) may contain more verbose information. The default value is _FALSE_.  Verbose logging should only be used for debugging.  The potentially large quantity of logged information may adversely affect peformance.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkJsRef.html#VerboseLogging
	 * @param bool $newVal
	 */
	function put_VerboseLogging($newVal) {
		CkJs_put_VerboseLogging($this->_cPtr,$newVal);
	}

	/**
	 * Version of the component/library, such as "10.1.0"
	 * @see https://www.chilkatsoft.com/refdoc/phpCkJsRef.html#Version
	 * @param CkString $str
	 */
	function get_Version($str) {
		CkJs_get_Version($this->_cPtr,$str);
	}

	/**
	 * Version of the component/library, such as "10.1.0"
	 * @see https://www.chilkatsoft.com/refdoc/phpCkJsRef.html#Version
	 * @return ?string
	 */
	function version() {
		return CkJs_version($this->_cPtr);
	}

	/**
	 * Calls a JavaScript function.  The function name and arguments are passed in ARG1.  The result is returned in ARG2.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkJsRef.html#CallFunction
	 * @param CkJsonObject $funcJson
	 * @param CkJsonObject $resultJson
	 * @return bool
	 */
	function CallFunction($funcJson,$resultJson) {
		return CkJs_CallFunction($this->_cPtr,$funcJson,$resultJson);
	}

	/**
	 * Creates an asynchronous task to call the CallFunction method with the arguments provided.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkJsRef.html#CallFunctionAsync
	 * @param CkJsonObject $funcJson
	 * @param CkJsonObject $resultJson
	 * @return ?CkTask
	 */
	function CallFunctionAsync($funcJson,$resultJson) {
		return chilkat::_obj(CkJs_CallFunctionAsync($this->_cPtr,$funcJson,$resultJson),'CkTask');
	}

	/**
	 * Returns the console output in ARG1 from the last call to Eval .
	 * @see https://www.chilkatsoft.com/refdoc/phpCkJsRef.html#ConsoleOutputSb
	 * @param CkStringBuilder $sb
	 */
	function ConsoleOutputSb($sb) {
		CkJs_ConsoleOutputSb($this->_cPtr,$sb);
	}

	/**
	 * Run ARG1 as a script.  Return output and errors in ARG2.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkJsRef.html#Eval
	 * @param CkStringBuilder $jscript
	 * @param CkJsonObject $resultJson
	 * @return bool
	 */
	function c_Eval($jscript,$resultJson) {
		return CkJs_c_Eval($this->_cPtr,$jscript,$resultJson);
	}

	/**
	 * Creates an asynchronous task to call the Eval method with the arguments provided.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkJsRef.html#EvalAsync
	 * @param CkStringBuilder $jscript
	 * @param CkJsonObject $resultJson
	 * @return ?CkTask
	 */
	function EvalAsync($jscript,$resultJson) {
		return chilkat::_obj(CkJs_EvalAsync($this->_cPtr,$jscript,$resultJson),'CkTask');
	}

	/**
	 * Sets sandbox related permissions for Chilkat objects.  The ARG1 is the name of the Chilkat class (case-insensitive), such as Http, Rest, "MailMan", "Ftp2", "Ssh", etc.  The ARG1 can also be set to "all" to apply the permission to all Chilkat classes.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkJsRef.html#SetCkPermission
	 * @param ?string $chilkatClassName
	 * @param ?string $permission
	 * @return bool
	 */
	function SetCkPermission($chilkatClassName,$permission) {
		return CkJs_SetCkPermission($this->_cPtr,$chilkatClassName,$permission);
	}
}
