<?php

/* CkSCard.php -- Chilkat PHP extension proxy class CkSCard.
 * Generated by ChilkatApi/GenCkPhp.cs for Chilkat v11.6.1 -- do not edit.
 * Reference documentation: https://www.chilkatsoft.com/refdoc/ */

/**
 * Communicate directly with smart card readers and cards through PC/SC.
 *
 * Chilkat.SCard is the low-level PC/SC smart card interface for applications that need direct reader and card communication. It supports reader discovery, reader connection, card status checking, APDU transmission, reader-control commands, status-change monitoring, transactions, and diagnostic access to underlying PC/SC errors. Use this class when the application needs APDU-level control rather than a higher-level certificate, minidriver, or PKCS#11 abstraction.
 *
 * @see https://www.chilkatsoft.com/refdoc/phpCkSCardRef.html
 */
class CkSCard {
	public $_cPtr=null;
	protected $_pData=array();

	function __set($var,$value) {
		if ($var === 'thisown') return swig_chilkat_alter_newobject($this->_cPtr,$value);
		$this->_pData[$var] = $value;
	}

	function __get($var) {
		if ($var === 'thisown') return swig_chilkat_get_newobject($this->_cPtr);
		return $this->_pData[$var];
	}

	function __isset($var) {
		if ($var === 'thisown') return true;
		return array_key_exists($var, $this->_pData);
	}

	function __construct($res=null) {
		if (is_resource($res) && get_resource_type($res) === '_p_CkSCard') {
			$this->_cPtr=$res;
			return;
		}
		$this->_cPtr=new_CkSCard();
	}

	/**
	 * When true, strings passed to and returned from the object are UTF-8. When false (the default), they are ANSI (the locale's 8-bit character encoding).
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSCardRef.html
	 * @return bool
	 */
	function get_Utf8() {
		return CkSCard_get_Utf8($this->_cPtr);
	}

	/**
	 * When true, strings passed to and returned from the object are UTF-8. When false (the default), they are ANSI (the locale's 8-bit character encoding).
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSCardRef.html
	 * @param bool $b
	 */
	function put_Utf8($b) {
		CkSCard_put_Utf8($this->_cPtr,$b);
	}

	/**
	 * Sets the event callback object.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSCardRef.html
	 * @param ?CkBaseProgress $progress
	 */
	function put_EventCallbackObject($progress) {
		CkSCard_put_EventCallbackObject($this->_cPtr,$progress);
	}

	/**
	 * The name of the active protocol if connected smart card reader, or an empty string if not connected.  Possible values are T0, T1, raw, undefined, or  if not connected to a reader.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSCardRef.html#ActiveProtocol
	 * @param CkString $str
	 */
	function get_ActiveProtocol($str) {
		CkSCard_get_ActiveProtocol($this->_cPtr,$str);
	}

	/**
	 * The name of the active protocol if connected smart card reader, or an empty string if not connected.  Possible values are T0, T1, raw, undefined, or  if not connected to a reader.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSCardRef.html#ActiveProtocol
	 * @return ?string
	 */
	function activeProtocol() {
		return CkSCard_activeProtocol($this->_cPtr);
	}

	/**
	 * This is the Current ATR of a card in the connected reader.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSCardRef.html#CardAtr
	 * @param CkString $str
	 */
	function get_CardAtr($str) {
		CkSCard_get_CardAtr($this->_cPtr,$str);
	}

	/**
	 * This is the Current ATR of a card in the connected reader.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSCardRef.html#CardAtr
	 * @return ?string
	 */
	function cardAtr() {
		return CkSCard_cardAtr($this->_cPtr);
	}

	/**
	 * The name of the currently connected smart card reader, or an empty string if not connected.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSCardRef.html#ConnectedReader
	 * @param CkString $str
	 */
	function get_ConnectedReader($str) {
		CkSCard_get_ConnectedReader($this->_cPtr,$str);
	}

	/**
	 * The name of the currently connected smart card reader, or an empty string if not connected.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSCardRef.html#ConnectedReader
	 * @return ?string
	 */
	function connectedReader() {
		return CkSCard_connectedReader($this->_cPtr);
	}

	/**
	 * Contains the string user or system if this object has established a context (by calling EstablishContext).  Contains the empty string if no context is established.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSCardRef.html#Context
	 * @param CkString $str
	 */
	function get_Context($str) {
		CkSCard_get_Context($this->_cPtr,$str);
	}

	/**
	 * Contains the string user or system if this object has established a context (by calling EstablishContext).  Contains the empty string if no context is established.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSCardRef.html#Context
	 * @return ?string
	 */
	function context() {
		return CkSCard_context($this->_cPtr);
	}

	/**
	 * If set to a file path, this property logs the LastErrorText of each Chilkat method or property call to the specified file. This logging helps identify the context and history of Chilkat calls leading up to any crash or hang, aiding in debugging.  Enabling the VerboseLogging property provides more detailed information.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSCardRef.html#DebugLogFilePath
	 * @param CkString $str
	 */
	function get_DebugLogFilePath($str) {
		CkSCard_get_DebugLogFilePath($this->_cPtr,$str);
	}

	/**
	 * If set to a file path, this property logs the LastErrorText of each Chilkat method or property call to the specified file. This logging helps identify the context and history of Chilkat calls leading up to any crash or hang, aiding in debugging.  Enabling the VerboseLogging property provides more detailed information.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSCardRef.html#DebugLogFilePath
	 * @return ?string
	 */
	function debugLogFilePath() {
		return CkSCard_debugLogFilePath($this->_cPtr);
	}

	/**
	 * If set to a file path, this property logs the LastErrorText of each Chilkat method or property call to the specified file. This logging helps identify the context and history of Chilkat calls leading up to any crash or hang, aiding in debugging.  Enabling the VerboseLogging property provides more detailed information.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSCardRef.html#DebugLogFilePath
	 * @param ?string $newVal
	 */
	function put_DebugLogFilePath($newVal) {
		CkSCard_put_DebugLogFilePath($this->_cPtr,$newVal);
	}

	/**
	 * Provides HTML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSCardRef.html#LastErrorHtml
	 * @param CkString $str
	 */
	function get_LastErrorHtml($str) {
		CkSCard_get_LastErrorHtml($this->_cPtr,$str);
	}

	/**
	 * Provides HTML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSCardRef.html#LastErrorHtml
	 * @return ?string
	 */
	function lastErrorHtml() {
		return CkSCard_lastErrorHtml($this->_cPtr);
	}

	/**
	 * Provides plain text information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSCardRef.html#LastErrorText
	 * @param CkString $str
	 */
	function get_LastErrorText($str) {
		CkSCard_get_LastErrorText($this->_cPtr,$str);
	}

	/**
	 * Provides plain text information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSCardRef.html#LastErrorText
	 * @return ?string
	 */
	function lastErrorText() {
		return CkSCard_lastErrorText($this->_cPtr);
	}

	/**
	 * Provides XML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSCardRef.html#LastErrorXml
	 * @param CkString $str
	 */
	function get_LastErrorXml($str) {
		CkSCard_get_LastErrorXml($this->_cPtr,$str);
	}

	/**
	 * Provides XML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSCardRef.html#LastErrorXml
	 * @return ?string
	 */
	function lastErrorXml() {
		return CkSCard_lastErrorXml($this->_cPtr);
	}

	/**
	 * Indicates the success or failure of the most recent method call: _TRUE_ means success, _FALSE_ means failure. This property remains unchanged by property setters or getters.  This method is present to address challenges in checking for null or Nothing returns in certain programming languages.  Note: This property does not apply to methods that return integer values or to boolean-returning methods where the boolean does not indicate success or failure.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSCardRef.html#LastMethodSuccess
	 * @return bool
	 */
	function get_LastMethodSuccess() {
		return CkSCard_get_LastMethodSuccess($this->_cPtr);
	}

	/**
	 * Indicates the success or failure of the most recent method call: _TRUE_ means success, _FALSE_ means failure. This property remains unchanged by property setters or getters.  This method is present to address challenges in checking for null or Nothing returns in certain programming languages.  Note: This property does not apply to methods that return integer values or to boolean-returning methods where the boolean does not indicate success or failure.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSCardRef.html#LastMethodSuccess
	 * @param bool $newVal
	 */
	function put_LastMethodSuccess($newVal) {
		CkSCard_put_LastMethodSuccess($this->_cPtr,$newVal);
	}

	/**
	 * For Linux systems only. Specifies the full path of the libpcsclite.so shared lib.  This property should only be used if the libpcsclite.so is in a non-standard location or if Chilkat cannot automatically located it.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSCardRef.html#PcscLibPath
	 * @param CkString $str
	 */
	function get_PcscLibPath($str) {
		CkSCard_get_PcscLibPath($this->_cPtr,$str);
	}

	/**
	 * For Linux systems only. Specifies the full path of the libpcsclite.so shared lib.  This property should only be used if the libpcsclite.so is in a non-standard location or if Chilkat cannot automatically located it.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSCardRef.html#PcscLibPath
	 * @return ?string
	 */
	function pcscLibPath() {
		return CkSCard_pcscLibPath($this->_cPtr);
	}

	/**
	 * For Linux systems only. Specifies the full path of the libpcsclite.so shared lib.  This property should only be used if the libpcsclite.so is in a non-standard location or if Chilkat cannot automatically located it.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSCardRef.html#PcscLibPath
	 * @param ?string $newVal
	 */
	function put_PcscLibPath($newVal) {
		CkSCard_put_PcscLibPath($this->_cPtr,$newVal);
	}

	/**
	 * The current status of the connected reader.  Possible values are:
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSCardRef.html#ReaderStatus
	 * @param CkString $str
	 */
	function get_ReaderStatus($str) {
		CkSCard_get_ReaderStatus($this->_cPtr,$str);
	}

	/**
	 * The current status of the connected reader.  Possible values are:
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSCardRef.html#ReaderStatus
	 * @return ?string
	 */
	function readerStatus() {
		return CkSCard_readerStatus($this->_cPtr);
	}

	/**
	 * The last error returned by an underlying PC/SC function.  Can be one of the following:
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSCardRef.html#ScardError
	 * @param CkString $str
	 */
	function get_ScardError($str) {
		CkSCard_get_ScardError($this->_cPtr,$str);
	}

	/**
	 * The last error returned by an underlying PC/SC function.  Can be one of the following:
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSCardRef.html#ScardError
	 * @return ?string
	 */
	function scardError() {
		return CkSCard_scardError($this->_cPtr);
	}

	/**
	 * If set to _TRUE_, then the contents of LastErrorText (or LastErrorXml, or LastErrorHtml) may contain more verbose information. The default value is _FALSE_.  Verbose logging should only be used for debugging.  The potentially large quantity of logged information may adversely affect peformance.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSCardRef.html#VerboseLogging
	 * @return bool
	 */
	function get_VerboseLogging() {
		return CkSCard_get_VerboseLogging($this->_cPtr);
	}

	/**
	 * If set to _TRUE_, then the contents of LastErrorText (or LastErrorXml, or LastErrorHtml) may contain more verbose information. The default value is _FALSE_.  Verbose logging should only be used for debugging.  The potentially large quantity of logged information may adversely affect peformance.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSCardRef.html#VerboseLogging
	 * @param bool $newVal
	 */
	function put_VerboseLogging($newVal) {
		CkSCard_put_VerboseLogging($this->_cPtr,$newVal);
	}

	/**
	 * Version of the component/library, such as "10.1.0"
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSCardRef.html#Version
	 * @param CkString $str
	 */
	function get_Version($str) {
		CkSCard_get_Version($this->_cPtr,$str);
	}

	/**
	 * Version of the component/library, such as "10.1.0"
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSCardRef.html#Version
	 * @return ?string
	 */
	function version() {
		return CkSCard_version($this->_cPtr);
	}

	/**
	 * Establishes a temporary exclusive access mode for doing a series of commands in a transaction.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSCardRef.html#BeginTransaction
	 * @return bool
	 */
	function BeginTransaction() {
		return CkSCard_BeginTransaction($this->_cPtr);
	}

	/**
	 * Check the current status of the currently connected reader.  Calling this method updates the ReaderStatus, ActiveProtocol, and CardAtr properties.   If this method returns _FALSE_, none of the properties are updated.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSCardRef.html#CheckStatus
	 * @return bool
	 */
	function CheckStatus() {
		return CkSCard_CheckStatus($this->_cPtr);
	}

	/**
	 * Establish a connection to a reader.  The ARG1 is the name of a reader returned from ListReaders.   The ARG2 can be shared, exclusive, or direct.  The ARG3 can be 0 (valid only if the shareMode = direct), T0, T1,  raw, or no_preference.   (No preference is effectively T0 or T1.)
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSCardRef.html#Connect
	 * @param ?string $reader
	 * @param ?string $shareMode
	 * @param ?string $preferredProtocol
	 * @return bool
	 */
	function Connect($reader,$shareMode,$preferredProtocol) {
		return CkSCard_Connect($this->_cPtr,$reader,$shareMode,$preferredProtocol);
	}

	/**
	 * Terminates a connection with a reader.   The ARG1 can be one of the following values:
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSCardRef.html#Disconnect
	 * @param ?string $disposition
	 * @return bool
	 */
	function Disconnect($disposition) {
		return CkSCard_Disconnect($this->_cPtr,$disposition);
	}

	/**
	 * Ends a previously begun transaction.   The ARG1 is the action to be taken on the reader, and can be leave which is to do nothing, reset, unpower, or eject.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSCardRef.html#EndTransaction
	 * @param ?string $disposition
	 * @return bool
	 */
	function EndTransaction($disposition) {
		return CkSCard_EndTransaction($this->_cPtr,$disposition);
	}

	/**
	 * Creates an Application Context to the PC/SC Resource Manager.  This must be the first WinSCard function called in a PC/SC application.  The ARG1 can be user or system.  After calling, this object will have context and all other methods will use the established context.  The Context property will hold the value user or system if context was established, or will be empty if no context was established.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSCardRef.html#EstablishContext
	 * @param ?string $scope
	 * @return bool
	 */
	function EstablishContext($scope) {
		return CkSCard_EstablishContext($this->_cPtr,$scope);
	}

	/**
	 * Returns JSON containing information about the smartcards currently inserted into readers.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSCardRef.html#FindSmartcards
	 * @param CkJsonObject $json
	 * @return bool
	 */
	function FindSmartcards($json) {
		return CkSCard_FindSmartcards($this->_cPtr,$json);
	}

	/**
	 * Get an attribute from the IFD Handler (reader driver).
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSCardRef.html#GetAttrib
	 * @param ?string $attr
	 * @param CkBinData $bd
	 * @return bool
	 */
	function GetAttrib($attr,$bd) {
		return CkSCard_GetAttrib($this->_cPtr,$attr,$bd);
	}

	/**
	 * Get a string typed attribute from the IFD Handler (reader driver).
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSCardRef.html#GetAttribStr
	 * @param ?string $attr
	 * @return ?string
	 */
	function getAttribStr($attr) {
		return CkSCard_getAttribStr($this->_cPtr,$attr);
	}

	/**
	 * Get a string typed attribute from the IFD Handler (reader driver).
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSCardRef.html#GetAttribStr
	 * @param ?string $attr
	 * @return ?string
	 */
	function attribStr($attr) {
		return CkSCard_attribStr($this->_cPtr,$attr);
	}

	/**
	 * Get an unsigned integer typed attribute from the IFD Handler (reader driver).
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSCardRef.html#GetAttribUint
	 * @param ?string $attr
	 * @return int
	 */
	function GetAttribUint($attr) {
		return CkSCard_GetAttribUint($this->_cPtr,$attr);
	}

	/**
	 * Blocks execution until the current availability of the cards in a specific set of readers changes.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSCardRef.html#GetStatusChange
	 * @param int $maxWaitMs
	 * @param CkStringTable $stReaderNames
	 * @param CkJsonObject $json
	 * @return bool
	 */
	function GetStatusChange($maxWaitMs,$stReaderNames,$json) {
		return CkSCard_GetStatusChange($this->_cPtr,$maxWaitMs,$stReaderNames,$json);
	}

	/**
	 * Creates an asynchronous task to call the GetStatusChange method with the arguments provided.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSCardRef.html#GetStatusChangeAsync
	 * @param int $maxWaitMs
	 * @param CkStringTable $stReaderNames
	 * @param CkJsonObject $json
	 * @return ?CkTask
	 */
	function GetStatusChangeAsync($maxWaitMs,$stReaderNames,$json) {
		return chilkat::_obj(CkSCard_GetStatusChangeAsync($this->_cPtr,$maxWaitMs,$stReaderNames,$json),'CkTask');
	}

	/**
	 * Cancels an ongoing GetStatusChange method call.  This would be called from a separate thread in your application if GetStatusChange was called synchronously.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSCardRef.html#GetStatusChangeCancel
	 * @return bool
	 */
	function GetStatusChangeCancel() {
		return CkSCard_GetStatusChangeCancel($this->_cPtr);
	}

	/**
	 * Returns a list of currently available reader groups on the system.  The reader groups are returned in ARG1.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSCardRef.html#ListReaderGroups
	 * @param CkStringTable $readerGroups
	 * @return bool
	 */
	function ListReaderGroups($readerGroups) {
		return CkSCard_ListReaderGroups($this->_cPtr,$readerGroups);
	}

	/**
	 * Returns a list of currently available readers on the system.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSCardRef.html#ListReaders
	 * @param CkStringTable $st
	 * @return bool
	 */
	function ListReaders($st) {
		return CkSCard_ListReaders($this->_cPtr,$st);
	}

	/**
	 * Reestablishes a connection to a reader that was previously connected to using Connect().
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSCardRef.html#Reconnect
	 * @param ?string $shareMode
	 * @param ?string $preferredProtocol
	 * @param ?string $action
	 * @return bool
	 */
	function Reconnect($shareMode,$preferredProtocol,$action) {
		return CkSCard_Reconnect($this->_cPtr,$shareMode,$preferredProtocol,$action);
	}

	/**
	 * Destroys a communication context to the PC/SC Resource Manager. This must be the last function called in a PC/SC application.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSCardRef.html#ReleaseContext
	 * @return bool
	 */
	function ReleaseContext() {
		return CkSCard_ReleaseContext($this->_cPtr);
	}

	/**
	 * Sends a command directly to the IFD Handler (reader driver) to be processed by the reader.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSCardRef.html#SendControl
	 * @param int $controlCode
	 * @param CkBinData $bdSend
	 * @param CkBinData $bdRecv
	 * @return bool
	 */
	function SendControl($controlCode,$bdSend,$bdRecv) {
		return CkSCard_SendControl($this->_cPtr,$controlCode,$bdSend,$bdRecv);
	}

	/**
	 * Sends a command directly to the IFD Handler (reader driver) to be processed by the reader.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSCardRef.html#SendControlHex
	 * @param int $controlCode
	 * @param ?string $sendData
	 * @param CkBinData $bdRecv
	 * @return bool
	 */
	function SendControlHex($controlCode,$sendData,$bdRecv) {
		return CkSCard_SendControlHex($this->_cPtr,$controlCode,$sendData,$bdRecv);
	}

	/**
	 * Sends an APDU to the smart card contained in the currently connected reader.  The ARG1 can be T0, T1, or raw.  The APDU to be sent is contained in ARG2.  The response from the card is contained in ARG3.  The ARG4 is the maximum response size (in bytes) willing to be accepted.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSCardRef.html#Transmit
	 * @param ?string $protocol
	 * @param CkBinData $bdSend
	 * @param CkBinData $bdRecv
	 * @param int $maxRecvLen
	 * @return bool
	 */
	function Transmit($protocol,$bdSend,$bdRecv,$maxRecvLen) {
		return CkSCard_Transmit($this->_cPtr,$protocol,$bdSend,$bdRecv,$maxRecvLen);
	}

	/**
	 * Sends an APDU to the smart card contained in the currently connected reader.  The ARG1 can be T0, T1, or raw.  The APDU (in hexadecimal) to be sent is passed in ARG2.  The response from the card is contained in ARG3.  The ARG4 is the maximum response size (in bytes) willing to be accepted.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSCardRef.html#TransmitHex
	 * @param ?string $protocol
	 * @param ?string $apduHex
	 * @param CkBinData $bdRecv
	 * @param int $maxRecvLen
	 * @return bool
	 */
	function TransmitHex($protocol,$apduHex,$bdRecv,$maxRecvLen) {
		return CkSCard_TransmitHex($this->_cPtr,$protocol,$apduHex,$bdRecv,$maxRecvLen);
	}
}
