<?php

/* CkScp.php -- Chilkat PHP extension proxy class CkScp.
 * Generated by ChilkatApi/GenCkPhp.cs for Chilkat v11.6.1 -- do not edit.
 * Reference documentation: https://www.chilkatsoft.com/refdoc/ */

/**
 * Transfer files, text, and binary data over SCP using an existing SSH connection.
 *
 * Chilkat.Scp is the Chilkat class for SCP file transfer over an already-established Chilkat.Ssh connection. It supports local-file upload and download, in-memory binary transfer, encoded binary transfer, text transfer with explicit character sets, BinData transfer, directory-tree synchronization, sync filtering, remote UNIX permission overrides, environment variables, progress scaling, abort support, and asynchronous task integration.
 *
 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html
 */
class CkScp {
	public $_cPtr=null;
	protected $_pData=array();

	function __set($var,$value) {
		if ($var === 'thisown') return swig_chilkat_alter_newobject($this->_cPtr,$value);
		$this->_pData[$var] = $value;
	}

	function __get($var) {
		if ($var === 'thisown') return swig_chilkat_get_newobject($this->_cPtr);
		return $this->_pData[$var];
	}

	function __isset($var) {
		if ($var === 'thisown') return true;
		return array_key_exists($var, $this->_pData);
	}

	function __construct($res=null) {
		if (is_resource($res) && get_resource_type($res) === '_p_CkScp') {
			$this->_cPtr=$res;
			return;
		}
		$this->_cPtr=new_CkScp();
	}

	/**
	 * When true, strings passed to and returned from the object are UTF-8. When false (the default), they are ANSI (the locale's 8-bit character encoding).
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html
	 * @return bool
	 */
	function get_Utf8() {
		return CkScp_get_Utf8($this->_cPtr);
	}

	/**
	 * When true, strings passed to and returned from the object are UTF-8. When false (the default), they are ANSI (the locale's 8-bit character encoding).
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html
	 * @param bool $b
	 */
	function put_Utf8($b) {
		CkScp_put_Utf8($this->_cPtr,$b);
	}

	/**
	 * Sets the event callback object.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html
	 * @param ?CkBaseProgress $progress
	 */
	function put_EventCallbackObject($progress) {
		CkScp_put_EventCallbackObject($this->_cPtr,$progress);
	}

	/**
	 * Set to _TRUE_ to request cancellation of the method currently executing on this object. Long-running network and file-transfer operations check this property periodically; a method that completes quickly may finish before the request is observed.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#AbortCurrent
	 * @return bool
	 */
	function get_AbortCurrent() {
		return CkScp_get_AbortCurrent($this->_cPtr);
	}

	/**
	 * Set to _TRUE_ to request cancellation of the method currently executing on this object. Long-running network and file-transfer operations check this property periodically; a method that completes quickly may finish before the request is observed.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#AbortCurrent
	 * @param bool $newVal
	 */
	function put_AbortCurrent($newVal) {
		CkScp_put_AbortCurrent($this->_cPtr,$newVal);
	}

	/**
	 * If set to a file path, this property logs the LastErrorText of each Chilkat method or property call to the specified file. This logging helps identify the context and history of Chilkat calls leading up to any crash or hang, aiding in debugging.  Enabling the VerboseLogging property provides more detailed information.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#DebugLogFilePath
	 * @param CkString $str
	 */
	function get_DebugLogFilePath($str) {
		CkScp_get_DebugLogFilePath($this->_cPtr,$str);
	}

	/**
	 * If set to a file path, this property logs the LastErrorText of each Chilkat method or property call to the specified file. This logging helps identify the context and history of Chilkat calls leading up to any crash or hang, aiding in debugging.  Enabling the VerboseLogging property provides more detailed information.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#DebugLogFilePath
	 * @return ?string
	 */
	function debugLogFilePath() {
		return CkScp_debugLogFilePath($this->_cPtr);
	}

	/**
	 * If set to a file path, this property logs the LastErrorText of each Chilkat method or property call to the specified file. This logging helps identify the context and history of Chilkat calls leading up to any crash or hang, aiding in debugging.  Enabling the VerboseLogging property provides more detailed information.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#DebugLogFilePath
	 * @param ?string $newVal
	 */
	function put_DebugLogFilePath($newVal) {
		CkScp_put_DebugLogFilePath($this->_cPtr,$newVal);
	}

	/**
	 * Specifies the interval, in milliseconds, between AbortCheck event callbacks during supported long-running operations. The callback allows the application to report activity or request cancellation before the operation completes.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#HeartbeatMs
	 * @return int
	 */
	function get_HeartbeatMs() {
		return CkScp_get_HeartbeatMs($this->_cPtr);
	}

	/**
	 * Specifies the interval, in milliseconds, between AbortCheck event callbacks during supported long-running operations. The callback allows the application to report activity or request cancellation before the operation completes.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#HeartbeatMs
	 * @param int $newVal
	 */
	function put_HeartbeatMs($newVal) {
		CkScp_put_HeartbeatMs($this->_cPtr,$newVal);
	}

	/**
	 * Provides HTML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#LastErrorHtml
	 * @param CkString $str
	 */
	function get_LastErrorHtml($str) {
		CkScp_get_LastErrorHtml($this->_cPtr,$str);
	}

	/**
	 * Provides HTML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#LastErrorHtml
	 * @return ?string
	 */
	function lastErrorHtml() {
		return CkScp_lastErrorHtml($this->_cPtr);
	}

	/**
	 * Provides plain text information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#LastErrorText
	 * @param CkString $str
	 */
	function get_LastErrorText($str) {
		CkScp_get_LastErrorText($this->_cPtr,$str);
	}

	/**
	 * Provides plain text information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#LastErrorText
	 * @return ?string
	 */
	function lastErrorText() {
		return CkScp_lastErrorText($this->_cPtr);
	}

	/**
	 * Provides XML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#LastErrorXml
	 * @param CkString $str
	 */
	function get_LastErrorXml($str) {
		CkScp_get_LastErrorXml($this->_cPtr,$str);
	}

	/**
	 * Provides XML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#LastErrorXml
	 * @return ?string
	 */
	function lastErrorXml() {
		return CkScp_lastErrorXml($this->_cPtr);
	}

	/**
	 * Indicates the success or failure of the most recent method call: _TRUE_ means success, _FALSE_ means failure. This property remains unchanged by property setters or getters.  This method is present to address challenges in checking for null or Nothing returns in certain programming languages.  Note: This property does not apply to methods that return integer values or to boolean-returning methods where the boolean does not indicate success or failure.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#LastMethodSuccess
	 * @return bool
	 */
	function get_LastMethodSuccess() {
		return CkScp_get_LastMethodSuccess($this->_cPtr);
	}

	/**
	 * Indicates the success or failure of the most recent method call: _TRUE_ means success, _FALSE_ means failure. This property remains unchanged by property setters or getters.  This method is present to address challenges in checking for null or Nothing returns in certain programming languages.  Note: This property does not apply to methods that return integer values or to boolean-returning methods where the boolean does not indicate success or failure.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#LastMethodSuccess
	 * @param bool $newVal
	 */
	function put_LastMethodSuccess($newVal) {
		CkScp_put_LastMethodSuccess($this->_cPtr,$newVal);
	}

	/**
	 * Specifies the value that represents 100% completion in PercentDone event callbacks. The default is 100, which reports progress in whole-percent units. For example, when the scale is 1000, a callback value of 453 represents 45.3% completion.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#PercentDoneScale
	 * @return int
	 */
	function get_PercentDoneScale() {
		return CkScp_get_PercentDoneScale($this->_cPtr);
	}

	/**
	 * Specifies the value that represents 100% completion in PercentDone event callbacks. The default is 100, which reports progress in whole-percent units. For example, when the scale is 1000, a callback value of 453 represents 45.3% completion.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#PercentDoneScale
	 * @param int $newVal
	 */
	function put_PercentDoneScale($newVal) {
		CkScp_put_PercentDoneScale($this->_cPtr,$newVal);
	}

	/**
	 * Specifies environment variables to send for each SCP upload or download. Set the property to a JSON object whose member names are environment-variable names and whose values are strings.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#SendEnv
	 * @param CkString $str
	 */
	function get_SendEnv($str) {
		CkScp_get_SendEnv($this->_cPtr,$str);
	}

	/**
	 * Specifies environment variables to send for each SCP upload or download. Set the property to a JSON object whose member names are environment-variable names and whose values are strings.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#SendEnv
	 * @return ?string
	 */
	function sendEnv() {
		return CkScp_sendEnv($this->_cPtr);
	}

	/**
	 * Specifies environment variables to send for each SCP upload or download. Set the property to a JSON object whose member names are environment-variable names and whose values are strings.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#SendEnv
	 * @param ?string $newVal
	 */
	function put_SendEnv($newVal) {
		CkScp_put_SendEnv($this->_cPtr,$newVal);
	}

	/**
	 * Contains the local paths of the files transferred by the most recent call to SyncTreeUpload or SyncTreeDownload. Paths are listed one per line.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#SyncedFiles
	 * @param CkString $str
	 */
	function get_SyncedFiles($str) {
		CkScp_get_SyncedFiles($this->_cPtr,$str);
	}

	/**
	 * Contains the local paths of the files transferred by the most recent call to SyncTreeUpload or SyncTreeDownload. Paths are listed one per line.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#SyncedFiles
	 * @return ?string
	 */
	function syncedFiles() {
		return CkScp_syncedFiles($this->_cPtr);
	}

	/**
	 * Contains the local paths of the files transferred by the most recent call to SyncTreeUpload or SyncTreeDownload. Paths are listed one per line.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#SyncedFiles
	 * @param ?string $newVal
	 */
	function put_SyncedFiles($newVal) {
		CkScp_put_SyncedFiles($this->_cPtr,$newVal);
	}

	/**
	 * Specifies a semicolon-separated list of wildcard patterns for filenames that are eligible for transfer by SyncTreeUpload and SyncTreeDownload. A file is considered only when its filename matches at least one pattern.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#SyncMustMatch
	 * @param CkString $str
	 */
	function get_SyncMustMatch($str) {
		CkScp_get_SyncMustMatch($this->_cPtr,$str);
	}

	/**
	 * Specifies a semicolon-separated list of wildcard patterns for filenames that are eligible for transfer by SyncTreeUpload and SyncTreeDownload. A file is considered only when its filename matches at least one pattern.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#SyncMustMatch
	 * @return ?string
	 */
	function syncMustMatch() {
		return CkScp_syncMustMatch($this->_cPtr);
	}

	/**
	 * Specifies a semicolon-separated list of wildcard patterns for filenames that are eligible for transfer by SyncTreeUpload and SyncTreeDownload. A file is considered only when its filename matches at least one pattern.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#SyncMustMatch
	 * @param ?string $newVal
	 */
	function put_SyncMustMatch($newVal) {
		CkScp_put_SyncMustMatch($this->_cPtr,$newVal);
	}

	/**
	 * Specifies a semicolon-separated list of wildcard patterns for directory names that may be traversed by SyncTreeUpload and SyncTreeDownload. When this property is nonempty, synchronization descends only into directories whose names match at least one pattern.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#SyncMustMatchDir
	 * @param CkString $str
	 */
	function get_SyncMustMatchDir($str) {
		CkScp_get_SyncMustMatchDir($this->_cPtr,$str);
	}

	/**
	 * Specifies a semicolon-separated list of wildcard patterns for directory names that may be traversed by SyncTreeUpload and SyncTreeDownload. When this property is nonempty, synchronization descends only into directories whose names match at least one pattern.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#SyncMustMatchDir
	 * @return ?string
	 */
	function syncMustMatchDir() {
		return CkScp_syncMustMatchDir($this->_cPtr);
	}

	/**
	 * Specifies a semicolon-separated list of wildcard patterns for directory names that may be traversed by SyncTreeUpload and SyncTreeDownload. When this property is nonempty, synchronization descends only into directories whose names match at least one pattern.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#SyncMustMatchDir
	 * @param ?string $newVal
	 */
	function put_SyncMustMatchDir($newVal) {
		CkScp_put_SyncMustMatchDir($this->_cPtr,$newVal);
	}

	/**
	 * Specifies a semicolon-separated list of wildcard patterns for filenames that must be skipped by SyncTreeUpload and SyncTreeDownload.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#SyncMustNotMatch
	 * @param CkString $str
	 */
	function get_SyncMustNotMatch($str) {
		CkScp_get_SyncMustNotMatch($this->_cPtr,$str);
	}

	/**
	 * Specifies a semicolon-separated list of wildcard patterns for filenames that must be skipped by SyncTreeUpload and SyncTreeDownload.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#SyncMustNotMatch
	 * @return ?string
	 */
	function syncMustNotMatch() {
		return CkScp_syncMustNotMatch($this->_cPtr);
	}

	/**
	 * Specifies a semicolon-separated list of wildcard patterns for filenames that must be skipped by SyncTreeUpload and SyncTreeDownload.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#SyncMustNotMatch
	 * @param ?string $newVal
	 */
	function put_SyncMustNotMatch($newVal) {
		CkScp_put_SyncMustNotMatch($this->_cPtr,$newVal);
	}

	/**
	 * Specifies a semicolon-separated list of wildcard patterns for directory names that must not be traversed by SyncTreeUpload and SyncTreeDownload. A matching directory and everything below it are skipped.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#SyncMustNotMatchDir
	 * @param CkString $str
	 */
	function get_SyncMustNotMatchDir($str) {
		CkScp_get_SyncMustNotMatchDir($this->_cPtr,$str);
	}

	/**
	 * Specifies a semicolon-separated list of wildcard patterns for directory names that must not be traversed by SyncTreeUpload and SyncTreeDownload. A matching directory and everything below it are skipped.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#SyncMustNotMatchDir
	 * @return ?string
	 */
	function syncMustNotMatchDir() {
		return CkScp_syncMustNotMatchDir($this->_cPtr);
	}

	/**
	 * Specifies a semicolon-separated list of wildcard patterns for directory names that must not be traversed by SyncTreeUpload and SyncTreeDownload. A matching directory and everything below it are skipped.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#SyncMustNotMatchDir
	 * @param ?string $newVal
	 */
	function put_SyncMustNotMatchDir($newVal) {
		CkScp_put_SyncMustNotMatchDir($this->_cPtr,$newVal);
	}

	/**
	 * Provides a comma-separated list of specialized compatibility options. The default is the empty string, which is appropriate for normal SCP transfers.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#UncommonOptions
	 * @param CkString $str
	 */
	function get_UncommonOptions($str) {
		CkScp_get_UncommonOptions($this->_cPtr,$str);
	}

	/**
	 * Provides a comma-separated list of specialized compatibility options. The default is the empty string, which is appropriate for normal SCP transfers.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#UncommonOptions
	 * @return ?string
	 */
	function uncommonOptions() {
		return CkScp_uncommonOptions($this->_cPtr);
	}

	/**
	 * Provides a comma-separated list of specialized compatibility options. The default is the empty string, which is appropriate for normal SCP transfers.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#UncommonOptions
	 * @param ?string $newVal
	 */
	function put_UncommonOptions($newVal) {
		CkScp_put_UncommonOptions($this->_cPtr,$newVal);
	}

	/**
	 * Specifies an octal UNIX permission mode to apply to files uploaded by SCP, overriding the permissions derived from the local source file. For example, set this property to 0644 to grant read/write permission to the owner and read-only permission to the group and others.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#UnixPermOverride
	 * @param CkString $str
	 */
	function get_UnixPermOverride($str) {
		CkScp_get_UnixPermOverride($this->_cPtr,$str);
	}

	/**
	 * Specifies an octal UNIX permission mode to apply to files uploaded by SCP, overriding the permissions derived from the local source file. For example, set this property to 0644 to grant read/write permission to the owner and read-only permission to the group and others.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#UnixPermOverride
	 * @return ?string
	 */
	function unixPermOverride() {
		return CkScp_unixPermOverride($this->_cPtr);
	}

	/**
	 * Specifies an octal UNIX permission mode to apply to files uploaded by SCP, overriding the permissions derived from the local source file. For example, set this property to 0644 to grant read/write permission to the owner and read-only permission to the group and others.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#UnixPermOverride
	 * @param ?string $newVal
	 */
	function put_UnixPermOverride($newVal) {
		CkScp_put_UnixPermOverride($this->_cPtr,$newVal);
	}

	/**
	 * If set to _TRUE_, then the contents of LastErrorText (or LastErrorXml, or LastErrorHtml) may contain more verbose information. The default value is _FALSE_.  Verbose logging should only be used for debugging.  The potentially large quantity of logged information may adversely affect peformance.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#VerboseLogging
	 * @return bool
	 */
	function get_VerboseLogging() {
		return CkScp_get_VerboseLogging($this->_cPtr);
	}

	/**
	 * If set to _TRUE_, then the contents of LastErrorText (or LastErrorXml, or LastErrorHtml) may contain more verbose information. The default value is _FALSE_.  Verbose logging should only be used for debugging.  The potentially large quantity of logged information may adversely affect peformance.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#VerboseLogging
	 * @param bool $newVal
	 */
	function put_VerboseLogging($newVal) {
		CkScp_put_VerboseLogging($this->_cPtr,$newVal);
	}

	/**
	 * Version of the component/library, such as "10.1.0"
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#Version
	 * @param CkString $str
	 */
	function get_Version($str) {
		CkScp_get_Version($this->_cPtr,$str);
	}

	/**
	 * Version of the component/library, such as "10.1.0"
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#Version
	 * @return ?string
	 */
	function version() {
		return CkScp_version($this->_cPtr);
	}

	/**
	 * Downloads the file at ARG1 and appends its exact bytes to the existing contents of the BinData object in ARG2.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#DownloadBd
	 * @param ?string $remotePath
	 * @param CkBinData $bd
	 * @return bool
	 */
	function DownloadBd($remotePath,$bd) {
		return CkScp_DownloadBd($this->_cPtr,$remotePath,$bd);
	}

	/**
	 * Creates an asynchronous task to call the DownloadBd method with the arguments provided.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#DownloadBdAsync
	 * @param ?string $remotePath
	 * @param CkBinData $bd
	 * @return ?CkTask
	 */
	function DownloadBdAsync($remotePath,$bd) {
		return chilkat::_obj(CkScp_DownloadBdAsync($this->_cPtr,$remotePath,$bd),'CkTask');
	}

	/**
	 * Downloads the file at ARG1 from the SSH server and returns its exact bytes. No character decoding or text transformation is performed.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#DownloadBinary
	 * @param ?string $remotePath
	 * @param CkByteData $outBytes
	 * @return bool
	 */
	function DownloadBinary($remotePath,$outBytes) {
		return CkScp_DownloadBinary($this->_cPtr,$remotePath,$outBytes);
	}

	/**
	 * Creates an asynchronous task to call the DownloadBinary method with the arguments provided.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#DownloadBinaryAsync
	 * @param ?string $remotePath
	 * @return ?CkTask
	 */
	function DownloadBinaryAsync($remotePath) {
		return chilkat::_obj(CkScp_DownloadBinaryAsync($this->_cPtr,$remotePath),'CkTask');
	}

	/**
	 * Downloads the file at ARG1 and returns its bytes encoded as text using the binary encoding named by ARG2, such as base64 or hex.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#DownloadBinaryEncoded
	 * @param ?string $remotePath
	 * @param ?string $encoding
	 * @return ?string
	 */
	function downloadBinaryEncoded($remotePath,$encoding) {
		return CkScp_downloadBinaryEncoded($this->_cPtr,$remotePath,$encoding);
	}

	/**
	 * Creates an asynchronous task to call the DownloadBinaryEncoded method with the arguments provided.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#DownloadBinaryEncodedAsync
	 * @param ?string $remotePath
	 * @param ?string $encoding
	 * @return ?CkTask
	 */
	function DownloadBinaryEncodedAsync($remotePath,$encoding) {
		return chilkat::_obj(CkScp_DownloadBinaryEncodedAsync($this->_cPtr,$remotePath,$encoding),'CkTask');
	}

	/**
	 * Downloads the file at ARG1 from the SSH server and writes its bytes to the local filesystem path in ARG2.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#DownloadFile
	 * @param ?string $remotePath
	 * @param ?string $localPath
	 * @return bool
	 */
	function DownloadFile($remotePath,$localPath) {
		return CkScp_DownloadFile($this->_cPtr,$remotePath,$localPath);
	}

	/**
	 * Creates an asynchronous task to call the DownloadFile method with the arguments provided.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#DownloadFileAsync
	 * @param ?string $remotePath
	 * @param ?string $localPath
	 * @return ?CkTask
	 */
	function DownloadFileAsync($remotePath,$localPath) {
		return chilkat::_obj(CkScp_DownloadFileAsync($this->_cPtr,$remotePath,$localPath),'CkTask');
	}

	/**
	 * Downloads the file at ARG1, decodes its bytes using the character encoding named by ARG2, and returns the resulting text.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#DownloadString
	 * @param ?string $remotePath
	 * @param ?string $charset
	 * @return ?string
	 */
	function downloadString($remotePath,$charset) {
		return CkScp_downloadString($this->_cPtr,$remotePath,$charset);
	}

	/**
	 * Creates an asynchronous task to call the DownloadString method with the arguments provided.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#DownloadStringAsync
	 * @param ?string $remotePath
	 * @param ?string $charset
	 * @return ?CkTask
	 */
	function DownloadStringAsync($remotePath,$charset) {
		return chilkat::_obj(CkScp_DownloadStringAsync($this->_cPtr,$remotePath,$charset),'CkTask');
	}

	/**
	 * Loads the original caller object associated with the asynchronous Task in ARG1. ARG1 must be a task created by a compatible asynchronous method of this class.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#LoadTaskCaller
	 * @param CkTask $task
	 * @return bool
	 */
	function LoadTaskCaller($task) {
		return CkScp_LoadTaskCaller($this->_cPtr,$task);
	}

	/**
	 * Synchronizes files from the remote directory tree rooted at ARG1 to the local directory rooted at ARG2. ARG4 controls recursion: set it to _TRUE_ to descend into subdirectories, or _FALSE_ to process only files directly in the root directory.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#SyncTreeDownload
	 * @param ?string $remoteRoot
	 * @param ?string $localRoot
	 * @param int $mode
	 * @param bool $bRecurse
	 * @return bool
	 */
	function SyncTreeDownload($remoteRoot,$localRoot,$mode,$bRecurse) {
		return CkScp_SyncTreeDownload($this->_cPtr,$remoteRoot,$localRoot,$mode,$bRecurse);
	}

	/**
	 * Creates an asynchronous task to call the SyncTreeDownload method with the arguments provided.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#SyncTreeDownloadAsync
	 * @param ?string $remoteRoot
	 * @param ?string $localRoot
	 * @param int $mode
	 * @param bool $bRecurse
	 * @return ?CkTask
	 */
	function SyncTreeDownloadAsync($remoteRoot,$localRoot,$mode,$bRecurse) {
		return chilkat::_obj(CkScp_SyncTreeDownloadAsync($this->_cPtr,$remoteRoot,$localRoot,$mode,$bRecurse),'CkTask');
	}

	/**
	 * Synchronizes files from the local directory tree rooted at ARG1 to the remote directory rooted at ARG2. ARG4 controls recursion: set it to _TRUE_ to descend into subdirectories, or _FALSE_ to process only files directly in the local base directory.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#SyncTreeUpload
	 * @param ?string $localBaseDir
	 * @param ?string $remoteBaseDir
	 * @param int $mode
	 * @param bool $bRecurse
	 * @return bool
	 */
	function SyncTreeUpload($localBaseDir,$remoteBaseDir,$mode,$bRecurse) {
		return CkScp_SyncTreeUpload($this->_cPtr,$localBaseDir,$remoteBaseDir,$mode,$bRecurse);
	}

	/**
	 * Creates an asynchronous task to call the SyncTreeUpload method with the arguments provided.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#SyncTreeUploadAsync
	 * @param ?string $localBaseDir
	 * @param ?string $remoteBaseDir
	 * @param int $mode
	 * @param bool $bRecurse
	 * @return ?CkTask
	 */
	function SyncTreeUploadAsync($localBaseDir,$remoteBaseDir,$mode,$bRecurse) {
		return chilkat::_obj(CkScp_SyncTreeUploadAsync($this->_cPtr,$localBaseDir,$remoteBaseDir,$mode,$bRecurse),'CkTask');
	}

	/**
	 * Uploads all bytes currently contained in the BinData object in ARG2 to the remote file at ARG1. The data is transferred without character decoding or other transformation.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#UploadBd
	 * @param ?string $remotePath
	 * @param CkBinData $bd
	 * @return bool
	 */
	function UploadBd($remotePath,$bd) {
		return CkScp_UploadBd($this->_cPtr,$remotePath,$bd);
	}

	/**
	 * Creates an asynchronous task to call the UploadBd method with the arguments provided.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#UploadBdAsync
	 * @param ?string $remotePath
	 * @param CkBinData $bd
	 * @return ?CkTask
	 */
	function UploadBdAsync($remotePath,$bd) {
		return chilkat::_obj(CkScp_UploadBdAsync($this->_cPtr,$remotePath,$bd),'CkTask');
	}

	/**
	 * Uploads the exact bytes in ARG2 to the remote file at ARG1. No text encoding, newline conversion, or other data transformation is performed.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#UploadBinary
	 * @param ?string $remotePath
	 * @param CkByteData $binData
	 * @return bool
	 */
	function UploadBinary($remotePath,$binData) {
		return CkScp_UploadBinary($this->_cPtr,$remotePath,$binData);
	}

	/**
	 * Creates an asynchronous task to call the UploadBinary method with the arguments provided.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#UploadBinaryAsync
	 * @param ?string $remotePath
	 * @param CkByteData $binData
	 * @return ?CkTask
	 */
	function UploadBinaryAsync($remotePath,$binData) {
		return chilkat::_obj(CkScp_UploadBinaryAsync($this->_cPtr,$remotePath,$binData),'CkTask');
	}

	/**
	 * Decodes the text in ARG2 using the binary encoding named by ARG3, then uploads the resulting bytes to the remote file at ARG1. Typical encoding names include base64 and hex.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#UploadBinaryEncoded
	 * @param ?string $remotePath
	 * @param ?string $encodedData
	 * @param ?string $encoding
	 * @return bool
	 */
	function UploadBinaryEncoded($remotePath,$encodedData,$encoding) {
		return CkScp_UploadBinaryEncoded($this->_cPtr,$remotePath,$encodedData,$encoding);
	}

	/**
	 * Creates an asynchronous task to call the UploadBinaryEncoded method with the arguments provided.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#UploadBinaryEncodedAsync
	 * @param ?string $remotePath
	 * @param ?string $encodedData
	 * @param ?string $encoding
	 * @return ?CkTask
	 */
	function UploadBinaryEncodedAsync($remotePath,$encodedData,$encoding) {
		return chilkat::_obj(CkScp_UploadBinaryEncodedAsync($this->_cPtr,$remotePath,$encodedData,$encoding),'CkTask');
	}

	/**
	 * Uploads the local filesystem file at ARG1 to the remote path in ARG2. The file is transferred as raw bytes.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#UploadFile
	 * @param ?string $localPath
	 * @param ?string $remotePath
	 * @return bool
	 */
	function UploadFile($localPath,$remotePath) {
		return CkScp_UploadFile($this->_cPtr,$localPath,$remotePath);
	}

	/**
	 * Creates an asynchronous task to call the UploadFile method with the arguments provided.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#UploadFileAsync
	 * @param ?string $localPath
	 * @param ?string $remotePath
	 * @return ?CkTask
	 */
	function UploadFileAsync($localPath,$remotePath) {
		return chilkat::_obj(CkScp_UploadFileAsync($this->_cPtr,$localPath,$remotePath),'CkTask');
	}

	/**
	 * Encodes the text in ARG2 using the character encoding named by ARG3, then uploads the resulting bytes to the remote file at ARG1.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#UploadString
	 * @param ?string $remotePath
	 * @param ?string $textData
	 * @param ?string $charset
	 * @return bool
	 */
	function UploadString($remotePath,$textData,$charset) {
		return CkScp_UploadString($this->_cPtr,$remotePath,$textData,$charset);
	}

	/**
	 * Creates an asynchronous task to call the UploadString method with the arguments provided.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#UploadStringAsync
	 * @param ?string $remotePath
	 * @param ?string $textData
	 * @param ?string $charset
	 * @return ?CkTask
	 */
	function UploadStringAsync($remotePath,$textData,$charset) {
		return chilkat::_obj(CkScp_UploadStringAsync($this->_cPtr,$remotePath,$textData,$charset),'CkTask');
	}

	/**
	 * Associates this Scp object with the connected and authenticated Ssh object in ARG1. Subsequent SCP operations use that existing SSH session rather than opening a separate network connection.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkScpRef.html#UseSsh
	 * @param CkSsh $sshConnection
	 * @return bool
	 */
	function UseSsh($sshConnection) {
		return CkScp_UseSsh($this->_cPtr,$sshConnection);
	}
}
