<?php

/* CkSFtpFile.php -- Chilkat PHP extension proxy class CkSFtpFile.
 * Generated by ChilkatApi/GenCkPhp.cs for Chilkat v11.6.1 -- do not edit.
 * Reference documentation: https://www.chilkatsoft.com/refdoc/ */

/**
 * Inspect metadata for a file, directory, symlink, or special item in an SFTP listing.
 *
 * Chilkat.SFtpFile represents one entry returned from an SFTP directory listing. It exposes the entry name, file type, size, ownership, permissions, timestamps, and server-provided attribute flags such as hidden, read-only, archive, immutable, encrypted, compressed, sparse, append-only, system, and synchronization status. It is typically used together with Chilkat.SFtpDir when iterating a remote directory and deciding how each entry should be displayed, filtered, downloaded, skipped, or processed.
 *
 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpFileRef.html
 */
class CkSFtpFile {
	public $_cPtr=null;
	protected $_pData=array();

	function __set($var,$value) {
		if ($var === 'thisown') return swig_chilkat_alter_newobject($this->_cPtr,$value);
		$this->_pData[$var] = $value;
	}

	function __get($var) {
		if ($var === 'thisown') return swig_chilkat_get_newobject($this->_cPtr);
		return $this->_pData[$var];
	}

	function __isset($var) {
		if ($var === 'thisown') return true;
		return array_key_exists($var, $this->_pData);
	}

	function __construct($res=null) {
		if (is_resource($res) && get_resource_type($res) === '_p_CkSFtpFile') {
			$this->_cPtr=$res;
			return;
		}
		$this->_cPtr=new_CkSFtpFile();
	}

	/**
	 * When true, strings passed to and returned from the object are UTF-8. When false (the default), they are ANSI (the locale's 8-bit character encoding).
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpFileRef.html
	 * @return bool
	 */
	function get_Utf8() {
		return CkSFtpFile_get_Utf8($this->_cPtr);
	}

	/**
	 * When true, strings passed to and returned from the object are UTF-8. When false (the default), they are ANSI (the locale's 8-bit character encoding).
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpFileRef.html
	 * @param bool $b
	 */
	function put_Utf8($b) {
		CkSFtpFile_put_Utf8($this->_cPtr,$b);
	}

	/**
	 * Returns the file creation date and time as an RFC 822-formatted string, such as Fri, 21 Nov 1997 09:55:06 -0600.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpFileRef.html#CreateTimeStr
	 * @param CkString $str
	 */
	function get_CreateTimeStr($str) {
		CkSFtpFile_get_CreateTimeStr($this->_cPtr,$str);
	}

	/**
	 * Returns the file creation date and time as an RFC 822-formatted string, such as Fri, 21 Nov 1997 09:55:06 -0600.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpFileRef.html#CreateTimeStr
	 * @return ?string
	 */
	function createTimeStr() {
		return CkSFtpFile_createTimeStr($this->_cPtr);
	}

	/**
	 * If set to a file path, this property logs the LastErrorText of each Chilkat method or property call to the specified file. This logging helps identify the context and history of Chilkat calls leading up to any crash or hang, aiding in debugging.  Enabling the VerboseLogging property provides more detailed information.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpFileRef.html#DebugLogFilePath
	 * @param CkString $str
	 */
	function get_DebugLogFilePath($str) {
		CkSFtpFile_get_DebugLogFilePath($this->_cPtr,$str);
	}

	/**
	 * If set to a file path, this property logs the LastErrorText of each Chilkat method or property call to the specified file. This logging helps identify the context and history of Chilkat calls leading up to any crash or hang, aiding in debugging.  Enabling the VerboseLogging property provides more detailed information.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpFileRef.html#DebugLogFilePath
	 * @return ?string
	 */
	function debugLogFilePath() {
		return CkSFtpFile_debugLogFilePath($this->_cPtr);
	}

	/**
	 * If set to a file path, this property logs the LastErrorText of each Chilkat method or property call to the specified file. This logging helps identify the context and history of Chilkat calls leading up to any crash or hang, aiding in debugging.  Enabling the VerboseLogging property provides more detailed information.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpFileRef.html#DebugLogFilePath
	 * @param ?string $newVal
	 */
	function put_DebugLogFilePath($newVal) {
		CkSFtpFile_put_DebugLogFilePath($this->_cPtr,$newVal);
	}

	/**
	 * Returns the name of the directory entry. Depending on the entry type, this may be a regular filename, directory name, symbolic-link name, or the name of another special filesystem object.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpFileRef.html#Filename
	 * @param CkString $str
	 */
	function get_Filename($str) {
		CkSFtpFile_get_Filename($this->_cPtr,$str);
	}

	/**
	 * Returns the name of the directory entry. Depending on the entry type, this may be a regular filename, directory name, symbolic-link name, or the name of another special filesystem object.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpFileRef.html#Filename
	 * @return ?string
	 */
	function filename() {
		return CkSFtpFile_filename($this->_cPtr);
	}

	/**
	 * Identifies the type of directory entry. The returned value is one of the following:
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpFileRef.html#FileType
	 * @param CkString $str
	 */
	function get_FileType($str) {
		CkSFtpFile_get_FileType($this->_cPtr,$str);
	}

	/**
	 * Identifies the type of directory entry. The returned value is one of the following:
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpFileRef.html#FileType
	 * @return ?string
	 */
	function fileType() {
		return CkSFtpFile_fileType($this->_cPtr);
	}

	/**
	 * Returns the numeric group ID associated with the file.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpFileRef.html#Gid
	 * @return int
	 */
	function get_Gid() {
		return CkSFtpFile_get_Gid($this->_cPtr);
	}

	/**
	 * Returns the textual group name associated with the file.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpFileRef.html#Group
	 * @param CkString $str
	 */
	function get_Group($str) {
		CkSFtpFile_get_Group($this->_cPtr,$str);
	}

	/**
	 * Returns the textual group name associated with the file.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpFileRef.html#Group
	 * @return ?string
	 */
	function group() {
		return CkSFtpFile_group($this->_cPtr);
	}

	/**
	 * Returns _TRUE_ if the server marks the file as append-only. New data may be added only at the end of the file; existing data cannot be overwritten through normal file writes.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpFileRef.html#IsAppendOnly
	 * @return bool
	 */
	function get_IsAppendOnly() {
		return CkSFtpFile_get_IsAppendOnly($this->_cPtr);
	}

	/**
	 * Returns _TRUE_ if the server marks the file for inclusion in backup or archive operations.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpFileRef.html#IsArchive
	 * @return bool
	 */
	function get_IsArchive() {
		return CkSFtpFile_get_IsArchive($this->_cPtr);
	}

	/**
	 * Applies to directories. Returns _TRUE_ when names within the directory should be compared without regard to letter case.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpFileRef.html#IsCaseInsensitive
	 * @return bool
	 */
	function get_IsCaseInsensitive() {
		return CkSFtpFile_get_IsCaseInsensitive($this->_cPtr);
	}

	/**
	 * Returns _TRUE_ if the file is stored using transparent filesystem-level compression on the server.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpFileRef.html#IsCompressed
	 * @return bool
	 */
	function get_IsCompressed() {
		return CkSFtpFile_get_IsCompressed($this->_cPtr);
	}

	/**
	 * Returns _TRUE_ if the directory entry is a directory.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpFileRef.html#IsDirectory
	 * @return bool
	 */
	function get_IsDirectory() {
		return CkSFtpFile_get_IsDirectory($this->_cPtr);
	}

	/**
	 * Returns _TRUE_ if the file is stored using transparent filesystem-level encryption on the server.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpFileRef.html#IsEncrypted
	 * @return bool
	 */
	function get_IsEncrypted() {
		return CkSFtpFile_get_IsEncrypted($this->_cPtr);
	}

	/**
	 * Returns _TRUE_ if the server marks the entry as hidden. Hidden entries are normally omitted from user-facing displays unless the user specifically requests them.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpFileRef.html#IsHidden
	 * @return bool
	 */
	function get_IsHidden() {
		return CkSFtpFile_get_IsHidden($this->_cPtr);
	}

	/**
	 * Returns _TRUE_ if the server marks the file as immutable. An immutable file cannot normally be deleted, renamed, modified, or used as the target of a new hard link.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpFileRef.html#IsImmutable
	 * @return bool
	 */
	function get_IsImmutable() {
		return CkSFtpFile_get_IsImmutable($this->_cPtr);
	}

	/**
	 * Returns _TRUE_ if the server marks the file as read-only.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpFileRef.html#IsReadOnly
	 * @return bool
	 */
	function get_IsReadOnly() {
		return CkSFtpFile_get_IsReadOnly($this->_cPtr);
	}

	/**
	 * Returns _TRUE_ if the directory entry is a regular file rather than a directory, symbolic link, device, socket, FIFO, or other special type.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpFileRef.html#IsRegular
	 * @return bool
	 */
	function get_IsRegular() {
		return CkSFtpFile_get_IsRegular($this->_cPtr);
	}

	/**
	 * Returns _TRUE_ if the server identifies the file as sparse. A sparse file can contain unwritten regions, often called holes, that read as zero bytes without consuming equivalent physical disk space.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpFileRef.html#IsSparse
	 * @return bool
	 */
	function get_IsSparse() {
		return CkSFtpFile_get_IsSparse($this->_cPtr);
	}

	/**
	 * Returns _TRUE_ if the directory entry is a symbolic link.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpFileRef.html#IsSymLink
	 * @return bool
	 */
	function get_IsSymLink() {
		return CkSFtpFile_get_IsSymLink($this->_cPtr);
	}

	/**
	 * Returns _TRUE_ if modifications to the file are committed synchronously to server storage.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpFileRef.html#IsSync
	 * @return bool
	 */
	function get_IsSync() {
		return CkSFtpFile_get_IsSync($this->_cPtr);
	}

	/**
	 * Returns _TRUE_ if the server marks the file as part of the operating system.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpFileRef.html#IsSystem
	 * @return bool
	 */
	function get_IsSystem() {
		return CkSFtpFile_get_IsSystem($this->_cPtr);
	}

	/**
	 * Returns the file's last-access date and time as an RFC 822-formatted string, such as Fri, 21 Nov 1997 09:55:06 -0600.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpFileRef.html#LastAccessTimeStr
	 * @param CkString $str
	 */
	function get_LastAccessTimeStr($str) {
		CkSFtpFile_get_LastAccessTimeStr($this->_cPtr,$str);
	}

	/**
	 * Returns the file's last-access date and time as an RFC 822-formatted string, such as Fri, 21 Nov 1997 09:55:06 -0600.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpFileRef.html#LastAccessTimeStr
	 * @return ?string
	 */
	function lastAccessTimeStr() {
		return CkSFtpFile_lastAccessTimeStr($this->_cPtr);
	}

	/**
	 * Provides HTML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpFileRef.html#LastErrorHtml
	 * @param CkString $str
	 */
	function get_LastErrorHtml($str) {
		CkSFtpFile_get_LastErrorHtml($this->_cPtr,$str);
	}

	/**
	 * Provides HTML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpFileRef.html#LastErrorHtml
	 * @return ?string
	 */
	function lastErrorHtml() {
		return CkSFtpFile_lastErrorHtml($this->_cPtr);
	}

	/**
	 * Provides plain text information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpFileRef.html#LastErrorText
	 * @param CkString $str
	 */
	function get_LastErrorText($str) {
		CkSFtpFile_get_LastErrorText($this->_cPtr,$str);
	}

	/**
	 * Provides plain text information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpFileRef.html#LastErrorText
	 * @return ?string
	 */
	function lastErrorText() {
		return CkSFtpFile_lastErrorText($this->_cPtr);
	}

	/**
	 * Provides XML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpFileRef.html#LastErrorXml
	 * @param CkString $str
	 */
	function get_LastErrorXml($str) {
		CkSFtpFile_get_LastErrorXml($this->_cPtr,$str);
	}

	/**
	 * Provides XML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpFileRef.html#LastErrorXml
	 * @return ?string
	 */
	function lastErrorXml() {
		return CkSFtpFile_lastErrorXml($this->_cPtr);
	}

	/**
	 * Indicates the success or failure of the most recent method call: _TRUE_ means success, _FALSE_ means failure. This property remains unchanged by property setters or getters.  This method is present to address challenges in checking for null or Nothing returns in certain programming languages.  Note: This property does not apply to methods that return integer values or to boolean-returning methods where the boolean does not indicate success or failure.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpFileRef.html#LastMethodSuccess
	 * @return bool
	 */
	function get_LastMethodSuccess() {
		return CkSFtpFile_get_LastMethodSuccess($this->_cPtr);
	}

	/**
	 * Indicates the success or failure of the most recent method call: _TRUE_ means success, _FALSE_ means failure. This property remains unchanged by property setters or getters.  This method is present to address challenges in checking for null or Nothing returns in certain programming languages.  Note: This property does not apply to methods that return integer values or to boolean-returning methods where the boolean does not indicate success or failure.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpFileRef.html#LastMethodSuccess
	 * @param bool $newVal
	 */
	function put_LastMethodSuccess($newVal) {
		CkSFtpFile_put_LastMethodSuccess($this->_cPtr,$newVal);
	}

	/**
	 * Returns the file's last-modified date and time as an RFC 822-formatted string, such as Fri, 21 Nov 1997 09:55:06 -0600.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpFileRef.html#LastModifiedTimeStr
	 * @param CkString $str
	 */
	function get_LastModifiedTimeStr($str) {
		CkSFtpFile_get_LastModifiedTimeStr($this->_cPtr,$str);
	}

	/**
	 * Returns the file's last-modified date and time as an RFC 822-formatted string, such as Fri, 21 Nov 1997 09:55:06 -0600.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpFileRef.html#LastModifiedTimeStr
	 * @return ?string
	 */
	function lastModifiedTimeStr() {
		return CkSFtpFile_lastModifiedTimeStr($this->_cPtr);
	}

	/**
	 * Returns the textual owner name associated with the file.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpFileRef.html#Owner
	 * @param CkString $str
	 */
	function get_Owner($str) {
		CkSFtpFile_get_Owner($this->_cPtr,$str);
	}

	/**
	 * Returns the textual owner name associated with the file.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpFileRef.html#Owner
	 * @return ?string
	 */
	function owner() {
		return CkSFtpFile_owner($this->_cPtr);
	}

	/**
	 * Returns the POSIX-style file-permission bit mask. The values correspond to the permission and special-mode bits in the POSIX st_mode field.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpFileRef.html#Permissions
	 * @return int
	 */
	function get_Permissions() {
		return CkSFtpFile_get_Permissions($this->_cPtr);
	}

	/**
	 * Returns the file size in bytes as a 32-bit integer. Returns -1 when the size cannot be represented by a 32-bit integer. Use Size64 or SizeStr for larger values.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpFileRef.html#Size32
	 * @return int
	 */
	function get_Size32() {
		return CkSFtpFile_get_Size32($this->_cPtr);
	}

	/**
	 * Returns the file size in bytes as a 64-bit integer.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpFileRef.html#Size64
	 * @return int
	 */
	function get_Size64() {
		return CkSFtpFile_get_Size64($this->_cPtr);
	}

	/**
	 * Returns the file size in bytes as a base-10 string. This is the string representation of Size64 and is useful in environments where a 64-bit integer is inconvenient or unavailable.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpFileRef.html#SizeStr
	 * @param CkString $str
	 */
	function get_SizeStr($str) {
		CkSFtpFile_get_SizeStr($this->_cPtr,$str);
	}

	/**
	 * Returns the file size in bytes as a base-10 string. This is the string representation of Size64 and is useful in environments where a 64-bit integer is inconvenient or unavailable.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpFileRef.html#SizeStr
	 * @return ?string
	 */
	function sizeStr() {
		return CkSFtpFile_sizeStr($this->_cPtr);
	}

	/**
	 * Returns the numeric user ID associated with the file.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpFileRef.html#Uid
	 * @return int
	 */
	function get_Uid() {
		return CkSFtpFile_get_Uid($this->_cPtr);
	}

	/**
	 * If set to _TRUE_, then the contents of LastErrorText (or LastErrorXml, or LastErrorHtml) may contain more verbose information. The default value is _FALSE_.  Verbose logging should only be used for debugging.  The potentially large quantity of logged information may adversely affect peformance.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpFileRef.html#VerboseLogging
	 * @return bool
	 */
	function get_VerboseLogging() {
		return CkSFtpFile_get_VerboseLogging($this->_cPtr);
	}

	/**
	 * If set to _TRUE_, then the contents of LastErrorText (or LastErrorXml, or LastErrorHtml) may contain more verbose information. The default value is _FALSE_.  Verbose logging should only be used for debugging.  The potentially large quantity of logged information may adversely affect peformance.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpFileRef.html#VerboseLogging
	 * @param bool $newVal
	 */
	function put_VerboseLogging($newVal) {
		CkSFtpFile_put_VerboseLogging($this->_cPtr,$newVal);
	}

	/**
	 * Version of the component/library, such as "10.1.0"
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpFileRef.html#Version
	 * @param CkString $str
	 */
	function get_Version($str) {
		CkSFtpFile_get_Version($this->_cPtr,$str);
	}

	/**
	 * Version of the component/library, such as "10.1.0"
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpFileRef.html#Version
	 * @return ?string
	 */
	function version() {
		return CkSFtpFile_version($this->_cPtr);
	}

	/**
	 * Deprecated. Use the CreateTimeStr property instead.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpFileRef.html#GetCreateDt
	 * @return ?CkDateTime
	 * @deprecated
	 */
	function GetCreateDt() {
		return chilkat::_obj(CkSFtpFile_GetCreateDt($this->_cPtr),'CkDateTime');
	}

	/**
	 * Deprecated. Use the LastAccessTimeStr property instead.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpFileRef.html#GetLastAccessDt
	 * @return ?CkDateTime
	 * @deprecated
	 */
	function GetLastAccessDt() {
		return chilkat::_obj(CkSFtpFile_GetLastAccessDt($this->_cPtr),'CkDateTime');
	}

	/**
	 * Deprecated. Use the LastModifiedTimeStr property instead.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpFileRef.html#GetLastModifiedDt
	 * @return ?CkDateTime
	 * @deprecated
	 */
	function GetLastModifiedDt() {
		return chilkat::_obj(CkSFtpFile_GetLastModifiedDt($this->_cPtr),'CkDateTime');
	}
}
