<?php

/* CkSFtpDir.php -- Chilkat PHP extension proxy class CkSFtpDir.
 * Generated by ChilkatApi/GenCkPhp.cs for Chilkat v11.6.1 -- do not edit.
 * Reference documentation: https://www.chilkatsoft.com/refdoc/ */

/**
 * Inspect, sort, and iterate an SFTP directory listing.
 *
 * Chilkat.SFtpDir represents a directory listing returned by an SFTP operation. It provides the original path used to fetch the listing, the number of files and subdirectories found, methods for retrieving filenames or full SFtpFile entry details by index, sorting support, and a way to load a completed asynchronous directory-listing result.
 *
 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpDirRef.html
 */
class CkSFtpDir {
	public $_cPtr=null;
	protected $_pData=array();

	function __set($var,$value) {
		if ($var === 'thisown') return swig_chilkat_alter_newobject($this->_cPtr,$value);
		$this->_pData[$var] = $value;
	}

	function __get($var) {
		if ($var === 'thisown') return swig_chilkat_get_newobject($this->_cPtr);
		return $this->_pData[$var];
	}

	function __isset($var) {
		if ($var === 'thisown') return true;
		return array_key_exists($var, $this->_pData);
	}

	function __construct($res=null) {
		if (is_resource($res) && get_resource_type($res) === '_p_CkSFtpDir') {
			$this->_cPtr=$res;
			return;
		}
		$this->_cPtr=new_CkSFtpDir();
	}

	/**
	 * When true, strings passed to and returned from the object are UTF-8. When false (the default), they are ANSI (the locale's 8-bit character encoding).
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpDirRef.html
	 * @return bool
	 */
	function get_Utf8() {
		return CkSFtpDir_get_Utf8($this->_cPtr);
	}

	/**
	 * When true, strings passed to and returned from the object are UTF-8. When false (the default), they are ANSI (the locale's 8-bit character encoding).
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpDirRef.html
	 * @param bool $b
	 */
	function put_Utf8($b) {
		CkSFtpDir_put_Utf8($this->_cPtr,$b);
	}

	/**
	 * If set to a file path, this property logs the LastErrorText of each Chilkat method or property call to the specified file. This logging helps identify the context and history of Chilkat calls leading up to any crash or hang, aiding in debugging.  Enabling the VerboseLogging property provides more detailed information.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpDirRef.html#DebugLogFilePath
	 * @param CkString $str
	 */
	function get_DebugLogFilePath($str) {
		CkSFtpDir_get_DebugLogFilePath($this->_cPtr,$str);
	}

	/**
	 * If set to a file path, this property logs the LastErrorText of each Chilkat method or property call to the specified file. This logging helps identify the context and history of Chilkat calls leading up to any crash or hang, aiding in debugging.  Enabling the VerboseLogging property provides more detailed information.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpDirRef.html#DebugLogFilePath
	 * @return ?string
	 */
	function debugLogFilePath() {
		return CkSFtpDir_debugLogFilePath($this->_cPtr);
	}

	/**
	 * If set to a file path, this property logs the LastErrorText of each Chilkat method or property call to the specified file. This logging helps identify the context and history of Chilkat calls leading up to any crash or hang, aiding in debugging.  Enabling the VerboseLogging property provides more detailed information.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpDirRef.html#DebugLogFilePath
	 * @param ?string $newVal
	 */
	function put_DebugLogFilePath($newVal) {
		CkSFtpDir_put_DebugLogFilePath($this->_cPtr,$newVal);
	}

	/**
	 * Provides HTML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpDirRef.html#LastErrorHtml
	 * @param CkString $str
	 */
	function get_LastErrorHtml($str) {
		CkSFtpDir_get_LastErrorHtml($this->_cPtr,$str);
	}

	/**
	 * Provides HTML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpDirRef.html#LastErrorHtml
	 * @return ?string
	 */
	function lastErrorHtml() {
		return CkSFtpDir_lastErrorHtml($this->_cPtr);
	}

	/**
	 * Provides plain text information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpDirRef.html#LastErrorText
	 * @param CkString $str
	 */
	function get_LastErrorText($str) {
		CkSFtpDir_get_LastErrorText($this->_cPtr,$str);
	}

	/**
	 * Provides plain text information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpDirRef.html#LastErrorText
	 * @return ?string
	 */
	function lastErrorText() {
		return CkSFtpDir_lastErrorText($this->_cPtr);
	}

	/**
	 * Provides XML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpDirRef.html#LastErrorXml
	 * @param CkString $str
	 */
	function get_LastErrorXml($str) {
		CkSFtpDir_get_LastErrorXml($this->_cPtr,$str);
	}

	/**
	 * Provides XML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpDirRef.html#LastErrorXml
	 * @return ?string
	 */
	function lastErrorXml() {
		return CkSFtpDir_lastErrorXml($this->_cPtr);
	}

	/**
	 * Indicates the success or failure of the most recent method call: _TRUE_ means success, _FALSE_ means failure. This property remains unchanged by property setters or getters.  This method is present to address challenges in checking for null or Nothing returns in certain programming languages.  Note: This property does not apply to methods that return integer values or to boolean-returning methods where the boolean does not indicate success or failure.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpDirRef.html#LastMethodSuccess
	 * @return bool
	 */
	function get_LastMethodSuccess() {
		return CkSFtpDir_get_LastMethodSuccess($this->_cPtr);
	}

	/**
	 * Indicates the success or failure of the most recent method call: _TRUE_ means success, _FALSE_ means failure. This property remains unchanged by property setters or getters.  This method is present to address challenges in checking for null or Nothing returns in certain programming languages.  Note: This property does not apply to methods that return integer values or to boolean-returning methods where the boolean does not indicate success or failure.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpDirRef.html#LastMethodSuccess
	 * @param bool $newVal
	 */
	function put_LastMethodSuccess($newVal) {
		CkSFtpDir_put_LastMethodSuccess($this->_cPtr,$newVal);
	}

	/**
	 * Returns the number of entries in this directory listing.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpDirRef.html#NumFilesAndDirs
	 * @return int
	 */
	function get_NumFilesAndDirs() {
		return CkSFtpDir_get_NumFilesAndDirs($this->_cPtr);
	}

	/**
	 * Returns the original remote path used to create this directory listing.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpDirRef.html#OriginalPath
	 * @param CkString $str
	 */
	function get_OriginalPath($str) {
		CkSFtpDir_get_OriginalPath($this->_cPtr,$str);
	}

	/**
	 * Returns the original remote path used to create this directory listing.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpDirRef.html#OriginalPath
	 * @return ?string
	 */
	function originalPath() {
		return CkSFtpDir_originalPath($this->_cPtr);
	}

	/**
	 * If set to _TRUE_, then the contents of LastErrorText (or LastErrorXml, or LastErrorHtml) may contain more verbose information. The default value is _FALSE_.  Verbose logging should only be used for debugging.  The potentially large quantity of logged information may adversely affect peformance.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpDirRef.html#VerboseLogging
	 * @return bool
	 */
	function get_VerboseLogging() {
		return CkSFtpDir_get_VerboseLogging($this->_cPtr);
	}

	/**
	 * If set to _TRUE_, then the contents of LastErrorText (or LastErrorXml, or LastErrorHtml) may contain more verbose information. The default value is _FALSE_.  Verbose logging should only be used for debugging.  The potentially large quantity of logged information may adversely affect peformance.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpDirRef.html#VerboseLogging
	 * @param bool $newVal
	 */
	function put_VerboseLogging($newVal) {
		CkSFtpDir_put_VerboseLogging($this->_cPtr,$newVal);
	}

	/**
	 * Version of the component/library, such as "10.1.0"
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpDirRef.html#Version
	 * @param CkString $str
	 */
	function get_Version($str) {
		CkSFtpDir_get_Version($this->_cPtr,$str);
	}

	/**
	 * Version of the component/library, such as "10.1.0"
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpDirRef.html#Version
	 * @return ?string
	 */
	function version() {
		return CkSFtpDir_version($this->_cPtr);
	}

	/**
	 * Copies the metadata for the directory entry at the zero-based index into fileObj.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpDirRef.html#FileAt
	 * @param int $index
	 * @param CkSFtpFile $fileObj
	 * @return bool
	 */
	function FileAt($index,$fileObj) {
		return CkSFtpDir_FileAt($this->_cPtr,$index,$fileObj);
	}

	/**
	 * Returns the filename of the directory entry at the zero-based index.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpDirRef.html#GetFilename
	 * @param int $index
	 * @return ?string
	 */
	function getFilename($index) {
		return CkSFtpDir_getFilename($this->_cPtr,$index);
	}

	/**
	 * Returns the filename of the directory entry at the zero-based index.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpDirRef.html#GetFilename
	 * @param int $index
	 * @return ?string
	 */
	function filename($index) {
		return CkSFtpDir_filename($this->_cPtr,$index);
	}

	/**
	 * Deprecated: Use FileAt instead.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpDirRef.html#GetFileObject
	 * @param int $index
	 * @return ?CkSFtpFile
	 * @deprecated
	 */
	function GetFileObject($index) {
		return chilkat::_obj(CkSFtpDir_GetFileObject($this->_cPtr,$index),'CkSFtpFile');
	}

	/**
	 * Loads this SFtpDir object from the result of a completed asynchronous Task.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpDirRef.html#LoadTaskResult
	 * @param CkTask $task
	 * @return bool
	 */
	function LoadTaskResult($task) {
		return CkSFtpDir_LoadTaskResult($this->_cPtr,$task);
	}

	/**
	 * Reorders the files and subdirectories in this listing according to field.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpDirRef.html#Sort
	 * @param ?string $field
	 * @param bool $ascending
	 */
	function Sort($field,$ascending) {
		CkSFtpDir_Sort($this->_cPtr,$field,$ascending);
	}
}
