<?php

/* CkSFtpProgress.php -- Chilkat PHP extension proxy class CkSFtpProgress.
 * Generated by ChilkatApi/GenCkPhp.cs for Chilkat v11.6.1 -- do not edit.
 * Reference documentation: https://www.chilkatsoft.com/refdoc/ */

/**
 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpProgressRef.html
 */
class CkSFtpProgress extends CkBaseProgress {
	public $_cPtr=null;

	function __set($var,$value) {
		if ($var === 'thisown') return swig_chilkat_alter_newobject($this->_cPtr,$value);
		CkBaseProgress::__set($var,$value);
	}

	function __get($var) {
		if ($var === 'thisown') return swig_chilkat_get_newobject($this->_cPtr);
		return CkBaseProgress::__get($var);
	}

	function __isset($var) {
		if ($var === 'thisown') return true;
		return CkBaseProgress::__isset($var);
	}

	function __construct($res=null) {
		if (is_resource($res) && get_resource_type($res) === '_p_CkSFtpProgress') {
			$this->_cPtr=$res;
			return;
		}
		$this->_cPtr=new_CkSFtpProgress();
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpProgressRef.html
	 * @param int $byteCount
	 * @param int $bytesPerSec
	 */
	function UploadRate($byteCount,$bytesPerSec) {
		CkSFtpProgress_UploadRate($this->_cPtr,$byteCount,$bytesPerSec);
	}

	/**
	 * @see https://www.chilkatsoft.com/refdoc/phpCkSFtpProgressRef.html
	 * @param int $byteCount
	 * @param int $bytesPerSec
	 */
	function DownloadRate($byteCount,$bytesPerSec) {
		CkSFtpProgress_DownloadRate($this->_cPtr,$byteCount,$bytesPerSec);
	}
}
