<?php

/* CkTrustedRoots.php -- Chilkat PHP extension proxy class CkTrustedRoots.
 * Generated by ChilkatApi/GenCkPhp.cs for Chilkat v11.6.1 -- do not edit.
 * Reference documentation: https://www.chilkatsoft.com/refdoc/ */

/**
 * Configure the trusted root certificates used by Chilkat certificate validation.
 *
 * Chilkat.TrustedRoots manages a collection of trusted CA and self-signed root certificates used Chilkat-wide for PKCS7/CMS signature validation and SSL/TLS server certificate validation. It can add individual certificates, import trusted certificates from a Java keystore, load PEM CA bundles, activate or deactivate the trusted-root set, and control whether system CA roots and self-signed server certificates are trusted.
 *
 * @see https://www.chilkatsoft.com/refdoc/phpCkTrustedRootsRef.html
 */
class CkTrustedRoots {
	public $_cPtr=null;
	protected $_pData=array();

	function __set($var,$value) {
		if ($var === 'thisown') return swig_chilkat_alter_newobject($this->_cPtr,$value);
		$this->_pData[$var] = $value;
	}

	function __get($var) {
		if ($var === 'thisown') return swig_chilkat_get_newobject($this->_cPtr);
		return $this->_pData[$var];
	}

	function __isset($var) {
		if ($var === 'thisown') return true;
		return array_key_exists($var, $this->_pData);
	}

	function __construct($res=null) {
		if (is_resource($res) && get_resource_type($res) === '_p_CkTrustedRoots') {
			$this->_cPtr=$res;
			return;
		}
		$this->_cPtr=new_CkTrustedRoots();
	}

	/**
	 * When true, strings passed to and returned from the object are UTF-8. When false (the default), they are ANSI (the locale's 8-bit character encoding).
	 * @see https://www.chilkatsoft.com/refdoc/phpCkTrustedRootsRef.html
	 * @return bool
	 */
	function get_Utf8() {
		return CkTrustedRoots_get_Utf8($this->_cPtr);
	}

	/**
	 * When true, strings passed to and returned from the object are UTF-8. When false (the default), they are ANSI (the locale's 8-bit character encoding).
	 * @see https://www.chilkatsoft.com/refdoc/phpCkTrustedRootsRef.html
	 * @param bool $b
	 */
	function put_Utf8($b) {
		CkTrustedRoots_put_Utf8($this->_cPtr,$b);
	}

	/**
	 * Sets the event callback object.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkTrustedRootsRef.html
	 * @param ?CkBaseProgress $progress
	 */
	function put_EventCallbackObject($progress) {
		CkTrustedRoots_put_EventCallbackObject($this->_cPtr,$progress);
	}

	/**
	 * If set to a file path, this property logs the LastErrorText of each Chilkat method or property call to the specified file. This logging helps identify the context and history of Chilkat calls leading up to any crash or hang, aiding in debugging.  Enabling the VerboseLogging property provides more detailed information.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkTrustedRootsRef.html#DebugLogFilePath
	 * @param CkString $str
	 */
	function get_DebugLogFilePath($str) {
		CkTrustedRoots_get_DebugLogFilePath($this->_cPtr,$str);
	}

	/**
	 * If set to a file path, this property logs the LastErrorText of each Chilkat method or property call to the specified file. This logging helps identify the context and history of Chilkat calls leading up to any crash or hang, aiding in debugging.  Enabling the VerboseLogging property provides more detailed information.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkTrustedRootsRef.html#DebugLogFilePath
	 * @return ?string
	 */
	function debugLogFilePath() {
		return CkTrustedRoots_debugLogFilePath($this->_cPtr);
	}

	/**
	 * If set to a file path, this property logs the LastErrorText of each Chilkat method or property call to the specified file. This logging helps identify the context and history of Chilkat calls leading up to any crash or hang, aiding in debugging.  Enabling the VerboseLogging property provides more detailed information.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkTrustedRootsRef.html#DebugLogFilePath
	 * @param ?string $newVal
	 */
	function put_DebugLogFilePath($newVal) {
		CkTrustedRoots_put_DebugLogFilePath($this->_cPtr,$newVal);
	}

	/**
	 * Provides HTML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkTrustedRootsRef.html#LastErrorHtml
	 * @param CkString $str
	 */
	function get_LastErrorHtml($str) {
		CkTrustedRoots_get_LastErrorHtml($this->_cPtr,$str);
	}

	/**
	 * Provides HTML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkTrustedRootsRef.html#LastErrorHtml
	 * @return ?string
	 */
	function lastErrorHtml() {
		return CkTrustedRoots_lastErrorHtml($this->_cPtr);
	}

	/**
	 * Provides plain text information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkTrustedRootsRef.html#LastErrorText
	 * @param CkString $str
	 */
	function get_LastErrorText($str) {
		CkTrustedRoots_get_LastErrorText($this->_cPtr,$str);
	}

	/**
	 * Provides plain text information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkTrustedRootsRef.html#LastErrorText
	 * @return ?string
	 */
	function lastErrorText() {
		return CkTrustedRoots_lastErrorText($this->_cPtr);
	}

	/**
	 * Provides XML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkTrustedRootsRef.html#LastErrorXml
	 * @param CkString $str
	 */
	function get_LastErrorXml($str) {
		CkTrustedRoots_get_LastErrorXml($this->_cPtr,$str);
	}

	/**
	 * Provides XML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkTrustedRootsRef.html#LastErrorXml
	 * @return ?string
	 */
	function lastErrorXml() {
		return CkTrustedRoots_lastErrorXml($this->_cPtr);
	}

	/**
	 * Indicates the success or failure of the most recent method call: _TRUE_ means success, _FALSE_ means failure. This property remains unchanged by property setters or getters.  This method is present to address challenges in checking for null or Nothing returns in certain programming languages.  Note: This property does not apply to methods that return integer values or to boolean-returning methods where the boolean does not indicate success or failure.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkTrustedRootsRef.html#LastMethodSuccess
	 * @return bool
	 */
	function get_LastMethodSuccess() {
		return CkTrustedRoots_get_LastMethodSuccess($this->_cPtr);
	}

	/**
	 * Indicates the success or failure of the most recent method call: _TRUE_ means success, _FALSE_ means failure. This property remains unchanged by property setters or getters.  This method is present to address challenges in checking for null or Nothing returns in certain programming languages.  Note: This property does not apply to methods that return integer values or to boolean-returning methods where the boolean does not indicate success or failure.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkTrustedRootsRef.html#LastMethodSuccess
	 * @param bool $newVal
	 */
	function put_LastMethodSuccess($newVal) {
		CkTrustedRoots_put_LastMethodSuccess($this->_cPtr,$newVal);
	}

	/**
	 * The number of certificates explicitly contained in this object. The count includes certificates added by AddCert, AddJavaKeyStore, and LoadCaCertsPem. Use indexes from 0 through NumCerts - 1 with CertAt.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkTrustedRootsRef.html#NumCerts
	 * @return int
	 */
	function get_NumCerts() {
		return CkTrustedRoots_get_NumCerts($this->_cPtr);
	}

	/**
	 * Controls the special case in which an SSL/TLS server presents a certificate chain containing exactly one certificate and that certificate is self-signed. The default value is _FALSE_.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkTrustedRootsRef.html#RejectSelfSignedCerts
	 * @return bool
	 */
	function get_RejectSelfSignedCerts() {
		return CkTrustedRoots_get_RejectSelfSignedCerts($this->_cPtr);
	}

	/**
	 * Controls the special case in which an SSL/TLS server presents a certificate chain containing exactly one certificate and that certificate is self-signed. The default value is _FALSE_.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkTrustedRootsRef.html#RejectSelfSignedCerts
	 * @param bool $newVal
	 */
	function put_RejectSelfSignedCerts($newVal) {
		CkTrustedRoots_put_RejectSelfSignedCerts($this->_cPtr,$newVal);
	}

	/**
	 * Controls whether operating-system CA roots are included when this object's trust configuration is activated. The default value is _TRUE_.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkTrustedRootsRef.html#TrustSystemCaRoots
	 * @return bool
	 */
	function get_TrustSystemCaRoots() {
		return CkTrustedRoots_get_TrustSystemCaRoots($this->_cPtr);
	}

	/**
	 * Controls whether operating-system CA roots are included when this object's trust configuration is activated. The default value is _TRUE_.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkTrustedRootsRef.html#TrustSystemCaRoots
	 * @param bool $newVal
	 */
	function put_TrustSystemCaRoots($newVal) {
		CkTrustedRoots_put_TrustSystemCaRoots($this->_cPtr,$newVal);
	}

	/**
	 * If set to _TRUE_, then the contents of LastErrorText (or LastErrorXml, or LastErrorHtml) may contain more verbose information. The default value is _FALSE_.  Verbose logging should only be used for debugging.  The potentially large quantity of logged information may adversely affect peformance.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkTrustedRootsRef.html#VerboseLogging
	 * @return bool
	 */
	function get_VerboseLogging() {
		return CkTrustedRoots_get_VerboseLogging($this->_cPtr);
	}

	/**
	 * If set to _TRUE_, then the contents of LastErrorText (or LastErrorXml, or LastErrorHtml) may contain more verbose information. The default value is _FALSE_.  Verbose logging should only be used for debugging.  The potentially large quantity of logged information may adversely affect peformance.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkTrustedRootsRef.html#VerboseLogging
	 * @param bool $newVal
	 */
	function put_VerboseLogging($newVal) {
		CkTrustedRoots_put_VerboseLogging($this->_cPtr,$newVal);
	}

	/**
	 * Version of the component/library, such as "10.1.0"
	 * @see https://www.chilkatsoft.com/refdoc/phpCkTrustedRootsRef.html#Version
	 * @param CkString $str
	 */
	function get_Version($str) {
		CkTrustedRoots_get_Version($this->_cPtr,$str);
	}

	/**
	 * Version of the component/library, such as "10.1.0"
	 * @see https://www.chilkatsoft.com/refdoc/phpCkTrustedRootsRef.html#Version
	 * @return ?string
	 */
	function version() {
		return CkTrustedRoots_version($this->_cPtr);
	}

	/**
	 * Activates this object's trust configuration for Chilkat-wide certificate validation. The active configuration includes:
	 * @see https://www.chilkatsoft.com/refdoc/phpCkTrustedRootsRef.html#Activate
	 * @return bool
	 */
	function Activate() {
		return CkTrustedRoots_Activate($this->_cPtr);
	}

	/**
	 * Adds the certificate in ARG1 to this object's explicit trusted-certificate collection. The certificate is subsequently treated as a trust anchor when this configuration is activated. Returns _TRUE_ if the certificate was added successfully; otherwise returns _FALSE_.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkTrustedRootsRef.html#AddCert
	 * @param CkCert $cert
	 * @return bool
	 */
	function AddCert($cert) {
		return CkTrustedRoots_AddCert($this->_cPtr,$cert);
	}

	/**
	 * Adds the certificates designated as trusted entries in the ARG1 JavaKeyStore to this object's explicit trusted-certificate collection. Private keys and secret keys are not imported. Returns _TRUE_ if the trusted certificates were added successfully; otherwise returns _FALSE_.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkTrustedRootsRef.html#AddJavaKeyStore
	 * @param CkJavaKeyStore $keystore
	 * @return bool
	 */
	function AddJavaKeyStore($keystore) {
		return CkTrustedRoots_AddJavaKeyStore($this->_cPtr,$keystore);
	}

	/**
	 * Creates an asynchronous task to call the AddJavaKeyStore method with the arguments provided.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkTrustedRootsRef.html#AddJavaKeyStoreAsync
	 * @param CkJavaKeyStore $keystore
	 * @return ?CkTask
	 */
	function AddJavaKeyStoreAsync($keystore) {
		return chilkat::_obj(CkTrustedRoots_AddJavaKeyStoreAsync($this->_cPtr,$keystore),'CkTask');
	}

	/**
	 * Copies the certificate at zero-based ARG1 into the caller-supplied Cert object in ARG2. Valid indexes are from 0 through NumCerts - 1. Returns _TRUE_ if the certificate was retrieved successfully; otherwise returns _FALSE_, such as when the index is outside the valid range.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkTrustedRootsRef.html#CertAt
	 * @param int $index
	 * @param CkCert $cert
	 * @return bool
	 */
	function CertAt($index,$cert) {
		return CkTrustedRoots_CertAt($this->_cPtr,$index,$cert);
	}

	/**
	 * Deactivates the previously activated Chilkat-wide trusted-root configuration. After deactivation, roots and single-certificate self-signed certificates are implicitly trusted. Returns _TRUE_ if the active configuration was deactivated successfully; otherwise returns _FALSE_.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkTrustedRootsRef.html#Deactivate
	 * @return bool
	 */
	function Deactivate() {
		return CkTrustedRoots_Deactivate($this->_cPtr);
	}

	/**
	 * Returns the certificate at zero-based ARG1 in this object's explicitly added certificate collection. This method is deprecated. New applications should call CertAt, which returns an explicit success/failure result and stores the certificate in a caller-supplied Cert object.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkTrustedRootsRef.html#GetCert
	 * @param int $index
	 * @return ?CkCert
	 * @deprecated
	 */
	function GetCert($index) {
		return chilkat::_obj(CkTrustedRoots_GetCert($this->_cPtr,$index),'CkCert');
	}

	/**
	 * Loads one or more PEM-encoded certificates from the file at ARG1 and adds them to this object's explicit trusted-certificate collection. A CA bundle normally contains consecutive -----BEGIN CERTIFICATE----- / -----END CERTIFICATE----- blocks. This method can load a curated application bundle, a Mozilla-derived CA bundle, or a platform bundle such as /etc/ssl/certs/ca-certificates.crt when that file exists. Returns _TRUE_ if the bundle was loaded successfully; otherwise returns _FALSE_.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkTrustedRootsRef.html#LoadCaCertsPem
	 * @param ?string $path
	 * @return bool
	 */
	function LoadCaCertsPem($path) {
		return CkTrustedRoots_LoadCaCertsPem($this->_cPtr,$path);
	}

	/**
	 * Creates an asynchronous task to call the LoadCaCertsPem method with the arguments provided.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkTrustedRootsRef.html#LoadCaCertsPemAsync
	 * @param ?string $path
	 * @return ?CkTask
	 */
	function LoadCaCertsPemAsync($path) {
		return chilkat::_obj(CkTrustedRoots_LoadCaCertsPemAsync($this->_cPtr,$path),'CkTask');
	}

	/**
	 * Associates ARG1 with the object that initiated the task's asynchronous method call. This supports Chilkat's asynchronous task infrastructure and is not normally called directly by application code. Returns _TRUE_ if the task caller was loaded successfully; otherwise returns _FALSE_.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkTrustedRootsRef.html#LoadTaskCaller
	 * @param CkTask $task
	 * @return bool
	 */
	function LoadTaskCaller($task) {
		return CkTrustedRoots_LoadTaskCaller($this->_cPtr,$task);
	}
}
