<?php

/* CkXmlCertVault.php -- Chilkat PHP extension proxy class CkXmlCertVault.
 * Generated by ChilkatApi/GenCkPhp.cs for Chilkat v11.6.1 -- do not edit.
 * Reference documentation: https://www.chilkatsoft.com/refdoc/ */

/**
 * Collect certificates, certificate chains, PEM data, and PFX private keys in an XML vault.
 *
 * Chilkat.XmlCertVault stores certificates and private-key material in a portable XML-based certificate vault. It can add individual certificates, certificate chains, DER or encoded certificates, PEM files, certificate strings, and PFX/PKCS12 data from files, memory, encoded text, or existing Chilkat objects. The vault can then be exported as XML, loaded from XML, or saved to an XML file for later reuse by other Chilkat certificate and TLS workflows.
 *
 * @see https://www.chilkatsoft.com/refdoc/phpCkXmlCertVaultRef.html
 */
class CkXmlCertVault {
	public $_cPtr=null;
	protected $_pData=array();

	function __set($var,$value) {
		if ($var === 'thisown') return swig_chilkat_alter_newobject($this->_cPtr,$value);
		$this->_pData[$var] = $value;
	}

	function __get($var) {
		if ($var === 'thisown') return swig_chilkat_get_newobject($this->_cPtr);
		return $this->_pData[$var];
	}

	function __isset($var) {
		if ($var === 'thisown') return true;
		return array_key_exists($var, $this->_pData);
	}

	function __construct($res=null) {
		if (is_resource($res) && get_resource_type($res) === '_p_CkXmlCertVault') {
			$this->_cPtr=$res;
			return;
		}
		$this->_cPtr=new_CkXmlCertVault();
	}

	/**
	 * When true, strings passed to and returned from the object are UTF-8. When false (the default), they are ANSI (the locale's 8-bit character encoding).
	 * @see https://www.chilkatsoft.com/refdoc/phpCkXmlCertVaultRef.html
	 * @return bool
	 */
	function get_Utf8() {
		return CkXmlCertVault_get_Utf8($this->_cPtr);
	}

	/**
	 * When true, strings passed to and returned from the object are UTF-8. When false (the default), they are ANSI (the locale's 8-bit character encoding).
	 * @see https://www.chilkatsoft.com/refdoc/phpCkXmlCertVaultRef.html
	 * @param bool $b
	 */
	function put_Utf8($b) {
		CkXmlCertVault_put_Utf8($this->_cPtr,$b);
	}

	/**
	 * If set to a file path, this property logs the LastErrorText of each Chilkat method or property call to the specified file. This logging helps identify the context and history of Chilkat calls leading up to any crash or hang, aiding in debugging.  Enabling the VerboseLogging property provides more detailed information.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkXmlCertVaultRef.html#DebugLogFilePath
	 * @param CkString $str
	 */
	function get_DebugLogFilePath($str) {
		CkXmlCertVault_get_DebugLogFilePath($this->_cPtr,$str);
	}

	/**
	 * If set to a file path, this property logs the LastErrorText of each Chilkat method or property call to the specified file. This logging helps identify the context and history of Chilkat calls leading up to any crash or hang, aiding in debugging.  Enabling the VerboseLogging property provides more detailed information.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkXmlCertVaultRef.html#DebugLogFilePath
	 * @return ?string
	 */
	function debugLogFilePath() {
		return CkXmlCertVault_debugLogFilePath($this->_cPtr);
	}

	/**
	 * If set to a file path, this property logs the LastErrorText of each Chilkat method or property call to the specified file. This logging helps identify the context and history of Chilkat calls leading up to any crash or hang, aiding in debugging.  Enabling the VerboseLogging property provides more detailed information.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkXmlCertVaultRef.html#DebugLogFilePath
	 * @param ?string $newVal
	 */
	function put_DebugLogFilePath($newVal) {
		CkXmlCertVault_put_DebugLogFilePath($this->_cPtr,$newVal);
	}

	/**
	 * Provides HTML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkXmlCertVaultRef.html#LastErrorHtml
	 * @param CkString $str
	 */
	function get_LastErrorHtml($str) {
		CkXmlCertVault_get_LastErrorHtml($this->_cPtr,$str);
	}

	/**
	 * Provides HTML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkXmlCertVaultRef.html#LastErrorHtml
	 * @return ?string
	 */
	function lastErrorHtml() {
		return CkXmlCertVault_lastErrorHtml($this->_cPtr);
	}

	/**
	 * Provides plain text information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkXmlCertVaultRef.html#LastErrorText
	 * @param CkString $str
	 */
	function get_LastErrorText($str) {
		CkXmlCertVault_get_LastErrorText($this->_cPtr,$str);
	}

	/**
	 * Provides plain text information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkXmlCertVaultRef.html#LastErrorText
	 * @return ?string
	 */
	function lastErrorText() {
		return CkXmlCertVault_lastErrorText($this->_cPtr);
	}

	/**
	 * Provides XML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkXmlCertVaultRef.html#LastErrorXml
	 * @param CkString $str
	 */
	function get_LastErrorXml($str) {
		CkXmlCertVault_get_LastErrorXml($this->_cPtr,$str);
	}

	/**
	 * Provides XML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkXmlCertVaultRef.html#LastErrorXml
	 * @return ?string
	 */
	function lastErrorXml() {
		return CkXmlCertVault_lastErrorXml($this->_cPtr);
	}

	/**
	 * Indicates the success or failure of the most recent method call: _TRUE_ means success, _FALSE_ means failure. This property remains unchanged by property setters or getters.  This method is present to address challenges in checking for null or Nothing returns in certain programming languages.  Note: This property does not apply to methods that return integer values or to boolean-returning methods where the boolean does not indicate success or failure.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkXmlCertVaultRef.html#LastMethodSuccess
	 * @return bool
	 */
	function get_LastMethodSuccess() {
		return CkXmlCertVault_get_LastMethodSuccess($this->_cPtr);
	}

	/**
	 * Indicates the success or failure of the most recent method call: _TRUE_ means success, _FALSE_ means failure. This property remains unchanged by property setters or getters.  This method is present to address challenges in checking for null or Nothing returns in certain programming languages.  Note: This property does not apply to methods that return integer values or to boolean-returning methods where the boolean does not indicate success or failure.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkXmlCertVaultRef.html#LastMethodSuccess
	 * @param bool $newVal
	 */
	function put_LastMethodSuccess($newVal) {
		CkXmlCertVault_put_LastMethodSuccess($this->_cPtr,$newVal);
	}

	/**
	 * The master password for the vault.  Certificates are stored unencrypted, but private keys are stored 256-bit AES encrypted using the individual PFX passwords.  The PFX passwords are stored 256-bit AES encrypted using the master password.   The master password is required to acces any of the private keys stored within the XML vault.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkXmlCertVaultRef.html#MasterPassword
	 * @param CkString $str
	 */
	function get_MasterPassword($str) {
		CkXmlCertVault_get_MasterPassword($this->_cPtr,$str);
	}

	/**
	 * The master password for the vault.  Certificates are stored unencrypted, but private keys are stored 256-bit AES encrypted using the individual PFX passwords.  The PFX passwords are stored 256-bit AES encrypted using the master password.   The master password is required to acces any of the private keys stored within the XML vault.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkXmlCertVaultRef.html#MasterPassword
	 * @return ?string
	 */
	function masterPassword() {
		return CkXmlCertVault_masterPassword($this->_cPtr);
	}

	/**
	 * The master password for the vault.  Certificates are stored unencrypted, but private keys are stored 256-bit AES encrypted using the individual PFX passwords.  The PFX passwords are stored 256-bit AES encrypted using the master password.   The master password is required to acces any of the private keys stored within the XML vault.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkXmlCertVaultRef.html#MasterPassword
	 * @param ?string $newVal
	 */
	function put_MasterPassword($newVal) {
		CkXmlCertVault_put_MasterPassword($this->_cPtr,$newVal);
	}

	/**
	 * If set to _TRUE_, then the contents of LastErrorText (or LastErrorXml, or LastErrorHtml) may contain more verbose information. The default value is _FALSE_.  Verbose logging should only be used for debugging.  The potentially large quantity of logged information may adversely affect peformance.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkXmlCertVaultRef.html#VerboseLogging
	 * @return bool
	 */
	function get_VerboseLogging() {
		return CkXmlCertVault_get_VerboseLogging($this->_cPtr);
	}

	/**
	 * If set to _TRUE_, then the contents of LastErrorText (or LastErrorXml, or LastErrorHtml) may contain more verbose information. The default value is _FALSE_.  Verbose logging should only be used for debugging.  The potentially large quantity of logged information may adversely affect peformance.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkXmlCertVaultRef.html#VerboseLogging
	 * @param bool $newVal
	 */
	function put_VerboseLogging($newVal) {
		CkXmlCertVault_put_VerboseLogging($this->_cPtr,$newVal);
	}

	/**
	 * Version of the component/library, such as "10.1.0"
	 * @see https://www.chilkatsoft.com/refdoc/phpCkXmlCertVaultRef.html#Version
	 * @param CkString $str
	 */
	function get_Version($str) {
		CkXmlCertVault_get_Version($this->_cPtr,$str);
	}

	/**
	 * Version of the component/library, such as "10.1.0"
	 * @see https://www.chilkatsoft.com/refdoc/phpCkXmlCertVaultRef.html#Version
	 * @return ?string
	 */
	function version() {
		return CkXmlCertVault_version($this->_cPtr);
	}

	/**
	 * Adds a certificate to the XML vault.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkXmlCertVaultRef.html#AddCert
	 * @param CkCert $cert
	 * @return bool
	 */
	function AddCert($cert) {
		return CkXmlCertVault_AddCert($this->_cPtr,$cert);
	}

	/**
	 * Adds a certificate to the XML vault from any binary format, such as DER.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkXmlCertVaultRef.html#AddCertBinary
	 * @param CkByteData $certBytes
	 * @return bool
	 */
	function AddCertBinary($certBytes) {
		return CkXmlCertVault_AddCertBinary($this->_cPtr,$certBytes);
	}

	/**
	 * Adds a chain of certificates  to the XML vault.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkXmlCertVaultRef.html#AddCertChain
	 * @param CkCertChain $certChain
	 * @return bool
	 */
	function AddCertChain($certChain) {
		return CkXmlCertVault_AddCertChain($this->_cPtr,$certChain);
	}

	/**
	 * Adds a certificate  to the XML vault where certificate is passed directly from encoded bytes (such as Base64, Hex, etc.).  The encoding is indicated by ARG2.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkXmlCertVaultRef.html#AddCertEncoded
	 * @param ?string $encodedBytes
	 * @param ?string $encoding
	 * @return bool
	 */
	function AddCertEncoded($encodedBytes,$encoding) {
		return CkXmlCertVault_AddCertEncoded($this->_cPtr,$encodedBytes,$encoding);
	}

	/**
	 * Adds a certificate to the XML vault.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkXmlCertVaultRef.html#AddCertFile
	 * @param ?string $path
	 * @return bool
	 */
	function AddCertFile($path) {
		return CkXmlCertVault_AddCertFile($this->_cPtr,$path);
	}

	/**
	 * Adds a certificate from any string representation format such as PEM.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkXmlCertVaultRef.html#AddCertString
	 * @param ?string $certData
	 * @return bool
	 */
	function AddCertString($certData) {
		return CkXmlCertVault_AddCertString($this->_cPtr,$certData);
	}

	/**
	 * Adds the contents of a PEM file to the XML vault.  The PEM file may be encrypted, and it may contain one or more certificates and/or private keys.   The password is optional and only required if the PEM file contains encrypted content that requires a password.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkXmlCertVaultRef.html#AddPemFile
	 * @param ?string $path
	 * @param ?string $password
	 * @return bool
	 */
	function AddPemFile($path,$password) {
		return CkXmlCertVault_AddPemFile($this->_cPtr,$path,$password);
	}

	/**
	 * Adds a PFX (PKCS12)  to the XML vault.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkXmlCertVaultRef.html#AddPfx
	 * @param CkPfx $pfx
	 * @return bool
	 */
	function AddPfx($pfx) {
		return CkXmlCertVault_AddPfx($this->_cPtr,$pfx);
	}

	/**
	 * Adds a PFX  to the XML vault where PFX is passed directly from in-memory binary bytes.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkXmlCertVaultRef.html#AddPfxBinary
	 * @param CkByteData $pfxBytes
	 * @param ?string $password
	 * @return bool
	 */
	function AddPfxBinary($pfxBytes,$password) {
		return CkXmlCertVault_AddPfxBinary($this->_cPtr,$pfxBytes,$password);
	}

	/**
	 * Adds a PFX  to the XML vault where PFX is passed directly from encoded bytes (such as Base64, Hex, etc.).  The encoding is indicated by ARG2.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkXmlCertVaultRef.html#AddPfxEncoded
	 * @param ?string $encodedBytes
	 * @param ?string $encoding
	 * @param ?string $password
	 * @return bool
	 */
	function AddPfxEncoded($encodedBytes,$encoding,$password) {
		return CkXmlCertVault_AddPfxEncoded($this->_cPtr,$encodedBytes,$encoding,$password);
	}

	/**
	 * Adds a PFX file to the XML vault.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkXmlCertVaultRef.html#AddPfxFile
	 * @param ?string $path
	 * @param ?string $password
	 * @return bool
	 */
	function AddPfxFile($path,$password) {
		return CkXmlCertVault_AddPfxFile($this->_cPtr,$path,$password);
	}

	/**
	 * Returns the contents of the cert vault as an XML string.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkXmlCertVaultRef.html#GetXml
	 * @return ?string
	 */
	function getXml() {
		return CkXmlCertVault_getXml($this->_cPtr);
	}

	/**
	 * Returns the contents of the cert vault as an XML string.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkXmlCertVaultRef.html#GetXml
	 * @return ?string
	 */
	function xml() {
		return CkXmlCertVault_xml($this->_cPtr);
	}

	/**
	 * Loads from an XML string.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkXmlCertVaultRef.html#LoadXml
	 * @param ?string $xml
	 * @return bool
	 */
	function LoadXml($xml) {
		return CkXmlCertVault_LoadXml($this->_cPtr,$xml);
	}

	/**
	 * Loads from an XML file.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkXmlCertVaultRef.html#LoadXmlFile
	 * @param ?string $path
	 * @return bool
	 */
	function LoadXmlFile($path) {
		return CkXmlCertVault_LoadXmlFile($this->_cPtr,$path);
	}

	/**
	 * Saves the contents to an XML file.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkXmlCertVaultRef.html#SaveXml
	 * @param ?string $path
	 * @return bool
	 */
	function SaveXml($path) {
		return CkXmlCertVault_SaveXml($this->_cPtr,$path);
	}
}
