<?php

/* CkZipEntry.php -- Chilkat PHP extension proxy class CkZipEntry.
 * Generated by ChilkatApi/GenCkPhp.cs for Chilkat v11.6.1 -- do not edit.
 * Reference documentation: https://www.chilkatsoft.com/refdoc/ */

/**
 * Inspect, extract, update, and iterate individual entries inside a ZIP archive.
 *
 * Chilkat.ZipEntry represents a single item associated with a Chilkat.Zip archive. An entry may be a file already stored in an opened ZIP, a referenced filesystem file waiting to be compressed, an in-memory text or binary entry, or a directory entry. It provides access to entry-level metadata, compressed and uncompressed data, timestamps, attributes, CRC values, encryption information, and extraction or replacement operations for that specific ZIP item.
 *
 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html
 */
class CkZipEntry {
	public $_cPtr=null;
	protected $_pData=array();

	function __set($var,$value) {
		if ($var === 'thisown') return swig_chilkat_alter_newobject($this->_cPtr,$value);
		$this->_pData[$var] = $value;
	}

	function __get($var) {
		if ($var === 'thisown') return swig_chilkat_get_newobject($this->_cPtr);
		return $this->_pData[$var];
	}

	function __isset($var) {
		if ($var === 'thisown') return true;
		return array_key_exists($var, $this->_pData);
	}

	function __construct($res=null) {
		if (is_resource($res) && get_resource_type($res) === '_p_CkZipEntry') {
			$this->_cPtr=$res;
			return;
		}
		$this->_cPtr=new_CkZipEntry();
	}

	/**
	 * When true, strings passed to and returned from the object are UTF-8. When false (the default), they are ANSI (the locale's 8-bit character encoding).
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html
	 * @return bool
	 */
	function get_Utf8() {
		return CkZipEntry_get_Utf8($this->_cPtr);
	}

	/**
	 * When true, strings passed to and returned from the object are UTF-8. When false (the default), they are ANSI (the locale's 8-bit character encoding).
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html
	 * @param bool $b
	 */
	function put_Utf8($b) {
		CkZipEntry_put_Utf8($this->_cPtr,$b);
	}

	/**
	 * Sets the event callback object.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html
	 * @param ?CkBaseProgress $progress
	 */
	function put_EventCallbackObject($progress) {
		CkZipEntry_put_EventCallbackObject($this->_cPtr,$progress);
	}

	/**
	 * Gets or sets the comment stored in the ZIP archive for this entry.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#Comment
	 * @param CkString $str
	 */
	function get_Comment($str) {
		CkZipEntry_get_Comment($this->_cPtr,$str);
	}

	/**
	 * Gets or sets the comment stored in the ZIP archive for this entry.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#Comment
	 * @return ?string
	 */
	function comment() {
		return CkZipEntry_comment($this->_cPtr);
	}

	/**
	 * Gets or sets the comment stored in the ZIP archive for this entry.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#Comment
	 * @param ?string $newVal
	 */
	function put_Comment($newVal) {
		CkZipEntry_put_Comment($this->_cPtr,$newVal);
	}

	/**
	 * The compressed size of this entry, in bytes.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#CompressedLength
	 * @return int
	 */
	function get_CompressedLength() {
		return CkZipEntry_get_CompressedLength($this->_cPtr);
	}

	/**
	 * The compressed size of this entry, in bytes, as a 64-bit integer.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#CompressedLength64
	 * @return int
	 */
	function get_CompressedLength64() {
		return CkZipEntry_get_CompressedLength64($this->_cPtr);
	}

	/**
	 * The compressed size of this entry as a decimal string.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#CompressedLengthStr
	 * @param CkString $str
	 */
	function get_CompressedLengthStr($str) {
		CkZipEntry_get_CompressedLengthStr($this->_cPtr,$str);
	}

	/**
	 * The compressed size of this entry as a decimal string.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#CompressedLengthStr
	 * @return ?string
	 */
	function compressedLengthStr() {
		return CkZipEntry_compressedLengthStr($this->_cPtr);
	}

	/**
	 * Gets or sets the compression level for this entry.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#CompressionLevel
	 * @return int
	 */
	function get_CompressionLevel() {
		return CkZipEntry_get_CompressionLevel($this->_cPtr);
	}

	/**
	 * Gets or sets the compression level for this entry.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#CompressionLevel
	 * @param int $newVal
	 */
	function put_CompressionLevel($newVal) {
		CkZipEntry_put_CompressionLevel($this->_cPtr,$newVal);
	}

	/**
	 * Gets or sets the compression method used for this entry.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#CompressionMethod
	 * @return int
	 */
	function get_CompressionMethod() {
		return CkZipEntry_get_CompressionMethod($this->_cPtr);
	}

	/**
	 * Gets or sets the compression method used for this entry.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#CompressionMethod
	 * @param int $newVal
	 */
	function put_CompressionMethod($newVal) {
		CkZipEntry_put_CompressionMethod($this->_cPtr,$newVal);
	}

	/**
	 * The CRC value for this ZIP entry.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#Crc
	 * @return int
	 */
	function get_Crc() {
		return CkZipEntry_get_Crc($this->_cPtr);
	}

	/**
	 * If set to a file path, this property logs the LastErrorText of each Chilkat method or property call to the specified file. This logging helps identify the context and history of Chilkat calls leading up to any crash or hang, aiding in debugging.  Enabling the VerboseLogging property provides more detailed information.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#DebugLogFilePath
	 * @param CkString $str
	 */
	function get_DebugLogFilePath($str) {
		CkZipEntry_get_DebugLogFilePath($this->_cPtr,$str);
	}

	/**
	 * If set to a file path, this property logs the LastErrorText of each Chilkat method or property call to the specified file. This logging helps identify the context and history of Chilkat calls leading up to any crash or hang, aiding in debugging.  Enabling the VerboseLogging property provides more detailed information.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#DebugLogFilePath
	 * @return ?string
	 */
	function debugLogFilePath() {
		return CkZipEntry_debugLogFilePath($this->_cPtr);
	}

	/**
	 * If set to a file path, this property logs the LastErrorText of each Chilkat method or property call to the specified file. This logging helps identify the context and history of Chilkat calls leading up to any crash or hang, aiding in debugging.  Enabling the VerboseLogging property provides more detailed information.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#DebugLogFilePath
	 * @param ?string $newVal
	 */
	function put_DebugLogFilePath($newVal) {
		CkZipEntry_put_DebugLogFilePath($this->_cPtr,$newVal);
	}

	/**
	 * The AES encryption key length for this entry.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#EncryptionKeyLen
	 * @return int
	 */
	function get_EncryptionKeyLen() {
		return CkZipEntry_get_EncryptionKeyLen($this->_cPtr);
	}

	/**
	 * A unique identifier assigned to this entry while the ZIP object is     instantiated in memory.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#EntryID
	 * @return int
	 */
	function get_EntryID() {
		return CkZipEntry_get_EntryID($this->_cPtr);
	}

	/**
	 * Indicates the origin and current state of this ZIP entry.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#EntryType
	 * @return int
	 */
	function get_EntryType() {
		return CkZipEntry_get_EntryType($this->_cPtr);
	}

	/**
	 * Gets or sets the local last-modified date/time for this ZIP entry     in RFC 822 string format.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#FileDateTimeStr
	 * @param CkString $str
	 */
	function get_FileDateTimeStr($str) {
		CkZipEntry_get_FileDateTimeStr($this->_cPtr,$str);
	}

	/**
	 * Gets or sets the local last-modified date/time for this ZIP entry     in RFC 822 string format.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#FileDateTimeStr
	 * @return ?string
	 */
	function fileDateTimeStr() {
		return CkZipEntry_fileDateTimeStr($this->_cPtr);
	}

	/**
	 * Gets or sets the local last-modified date/time for this ZIP entry     in RFC 822 string format.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#FileDateTimeStr
	 * @param ?string $newVal
	 */
	function put_FileDateTimeStr($newVal) {
		CkZipEntry_put_FileDateTimeStr($this->_cPtr,$newVal);
	}

	/**
	 * Gets or sets the filename, including any relative path, stored for     this entry inside the ZIP archive.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#FileName
	 * @param CkString $str
	 */
	function get_FileName($str) {
		CkZipEntry_get_FileName($this->_cPtr,$str);
	}

	/**
	 * Gets or sets the filename, including any relative path, stored for     this entry inside the ZIP archive.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#FileName
	 * @return ?string
	 */
	function fileName() {
		return CkZipEntry_fileName($this->_cPtr);
	}

	/**
	 * Gets or sets the filename, including any relative path, stored for     this entry inside the ZIP archive.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#FileName
	 * @param ?string $newVal
	 */
	function put_FileName($newVal) {
		CkZipEntry_put_FileName($this->_cPtr,$newVal);
	}

	/**
	 * Returns the raw filename bytes found in the ZIP entry, encoded as a     hexadecimal string.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#FileNameHex
	 * @param CkString $str
	 */
	function get_FileNameHex($str) {
		CkZipEntry_get_FileNameHex($this->_cPtr,$str);
	}

	/**
	 * Returns the raw filename bytes found in the ZIP entry, encoded as a     hexadecimal string.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#FileNameHex
	 * @return ?string
	 */
	function fileNameHex() {
		return CkZipEntry_fileNameHex($this->_cPtr);
	}

	/**
	 * The interval in milliseconds between each AbortCheck event callback, which enables an application to abort certain method calls before they complete. By default, HeartbeatMs is set to 0, meaning no AbortCheck event callbacks will trigger.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#HeartbeatMs
	 * @return int
	 */
	function get_HeartbeatMs() {
		return CkZipEntry_get_HeartbeatMs($this->_cPtr);
	}

	/**
	 * The interval in milliseconds between each AbortCheck event callback, which enables an application to abort certain method calls before they complete. By default, HeartbeatMs is set to 0, meaning no AbortCheck event callbacks will trigger.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#HeartbeatMs
	 * @param int $newVal
	 */
	function put_HeartbeatMs($newVal) {
		CkZipEntry_put_HeartbeatMs($this->_cPtr,$newVal);
	}

	/**
	 * Indicates whether this ZIP entry is AES encrypted.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#IsAesEncrypted
	 * @return bool
	 */
	function get_IsAesEncrypted() {
		return CkZipEntry_get_IsAesEncrypted($this->_cPtr);
	}

	/**
	 * Indicates whether this ZIP entry is a directory entry.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#IsDirectory
	 * @return bool
	 */
	function get_IsDirectory() {
		return CkZipEntry_get_IsDirectory($this->_cPtr);
	}

	/**
	 * Provides HTML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#LastErrorHtml
	 * @param CkString $str
	 */
	function get_LastErrorHtml($str) {
		CkZipEntry_get_LastErrorHtml($this->_cPtr,$str);
	}

	/**
	 * Provides HTML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#LastErrorHtml
	 * @return ?string
	 */
	function lastErrorHtml() {
		return CkZipEntry_lastErrorHtml($this->_cPtr);
	}

	/**
	 * Provides plain text information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#LastErrorText
	 * @param CkString $str
	 */
	function get_LastErrorText($str) {
		CkZipEntry_get_LastErrorText($this->_cPtr,$str);
	}

	/**
	 * Provides plain text information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#LastErrorText
	 * @return ?string
	 */
	function lastErrorText() {
		return CkZipEntry_lastErrorText($this->_cPtr);
	}

	/**
	 * Provides XML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#LastErrorXml
	 * @param CkString $str
	 */
	function get_LastErrorXml($str) {
		CkZipEntry_get_LastErrorXml($this->_cPtr,$str);
	}

	/**
	 * Provides XML-formatted information about the last called method or property. If a method call fails or behaves unexpectedly, check this property for details. Note that information is available regardless of the method call's success.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#LastErrorXml
	 * @return ?string
	 */
	function lastErrorXml() {
		return CkZipEntry_lastErrorXml($this->_cPtr);
	}

	/**
	 * Indicates the success or failure of the most recent method call: _TRUE_ means success, _FALSE_ means failure. This property remains unchanged by property setters or getters.  This method is present to address challenges in checking for null or Nothing returns in certain programming languages.  Note: This property does not apply to methods that return integer values or to boolean-returning methods where the boolean does not indicate success or failure.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#LastMethodSuccess
	 * @return bool
	 */
	function get_LastMethodSuccess() {
		return CkZipEntry_get_LastMethodSuccess($this->_cPtr);
	}

	/**
	 * Indicates the success or failure of the most recent method call: _TRUE_ means success, _FALSE_ means failure. This property remains unchanged by property setters or getters.  This method is present to address challenges in checking for null or Nothing returns in certain programming languages.  Note: This property does not apply to methods that return integer values or to boolean-returning methods where the boolean does not indicate success or failure.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#LastMethodSuccess
	 * @param bool $newVal
	 */
	function put_LastMethodSuccess($newVal) {
		CkZipEntry_put_LastMethodSuccess($this->_cPtr,$newVal);
	}

	/**
	 * Gets or sets the text flag in the internal file attributes for this     ZIP entry.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#TextFlag
	 * @return bool
	 */
	function get_TextFlag() {
		return CkZipEntry_get_TextFlag($this->_cPtr);
	}

	/**
	 * Gets or sets the text flag in the internal file attributes for this     ZIP entry.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#TextFlag
	 * @param bool $newVal
	 */
	function put_TextFlag($newVal) {
		CkZipEntry_put_TextFlag($this->_cPtr,$newVal);
	}

	/**
	 * The uncompressed size of this entry, in bytes.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#UncompressedLength
	 * @return int
	 */
	function get_UncompressedLength() {
		return CkZipEntry_get_UncompressedLength($this->_cPtr);
	}

	/**
	 * The uncompressed size of this entry, in bytes, as a 64-bit integer.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#UncompressedLength64
	 * @return int
	 */
	function get_UncompressedLength64() {
		return CkZipEntry_get_UncompressedLength64($this->_cPtr);
	}

	/**
	 * The uncompressed size of this ZIP entry as a decimal string.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#UncompressedLengthStr
	 * @param CkString $str
	 */
	function get_UncompressedLengthStr($str) {
		CkZipEntry_get_UncompressedLengthStr($this->_cPtr,$str);
	}

	/**
	 * The uncompressed size of this ZIP entry as a decimal string.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#UncompressedLengthStr
	 * @return ?string
	 */
	function uncompressedLengthStr() {
		return CkZipEntry_uncompressedLengthStr($this->_cPtr);
	}

	/**
	 * If set to _TRUE_, then the contents of LastErrorText (or LastErrorXml, or LastErrorHtml) may contain more verbose information. The default value is _FALSE_.  Verbose logging should only be used for debugging.  The potentially large quantity of logged information may adversely affect peformance.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#VerboseLogging
	 * @return bool
	 */
	function get_VerboseLogging() {
		return CkZipEntry_get_VerboseLogging($this->_cPtr);
	}

	/**
	 * If set to _TRUE_, then the contents of LastErrorText (or LastErrorXml, or LastErrorHtml) may contain more verbose information. The default value is _FALSE_.  Verbose logging should only be used for debugging.  The potentially large quantity of logged information may adversely affect peformance.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#VerboseLogging
	 * @param bool $newVal
	 */
	function put_VerboseLogging($newVal) {
		CkZipEntry_put_VerboseLogging($this->_cPtr,$newVal);
	}

	/**
	 * Version of the component/library, such as "10.1.0"
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#Version
	 * @param CkString $str
	 */
	function get_Version($str) {
		CkZipEntry_get_Version($this->_cPtr,$str);
	}

	/**
	 * Version of the component/library, such as "10.1.0"
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#Version
	 * @return ?string
	 */
	function version() {
		return CkZipEntry_version($this->_cPtr);
	}

	/**
	 * Appends binary data to this ZIP entry's file contents.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#AppendData
	 * @param CkByteData $inData
	 * @return bool
	 */
	function AppendData($inData) {
		return CkZipEntry_AppendData($this->_cPtr,$inData);
	}

	/**
	 * Creates an asynchronous task to call the AppendData method with the arguments provided.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#AppendDataAsync
	 * @param CkByteData $inData
	 * @return ?CkTask
	 */
	function AppendDataAsync($inData) {
		return chilkat::_obj(CkZipEntry_AppendDataAsync($this->_cPtr,$inData),'CkTask');
	}

	/**
	 * Appends text data to this ZIP entry's file contents.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#AppendString
	 * @param ?string $strContent
	 * @param ?string $charset
	 * @return bool
	 */
	function AppendString($strContent,$charset) {
		return CkZipEntry_AppendString($this->_cPtr,$strContent,$charset);
	}

	/**
	 * Creates an asynchronous task to call the AppendString method with the arguments provided.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#AppendStringAsync
	 * @param ?string $strContent
	 * @param ?string $charset
	 * @return ?CkTask
	 */
	function AppendStringAsync($strContent,$charset) {
		return chilkat::_obj(CkZipEntry_AppendStringAsync($this->_cPtr,$strContent,$charset),'CkTask');
	}

	/**
	 * Returns the compressed data for this ZIP entry as a byte array.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#Copy
	 * @param CkByteData $outData
	 * @return bool
	 */
	function Copy($outData) {
		return CkZipEntry_Copy($this->_cPtr,$outData);
	}

	/**
	 * Returns the compressed data for this ZIP entry as a Base64-encoded     string.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#CopyToBase64
	 * @return ?string
	 */
	function copyToBase64() {
		return CkZipEntry_copyToBase64($this->_cPtr);
	}

	/**
	 * Returns the compressed data for this ZIP entry as a hexadecimal     encoded string.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#CopyToHex
	 * @return ?string
	 */
	function copyToHex() {
		return CkZipEntry_copyToHex($this->_cPtr);
	}

	/**
	 * Extracts this ZIP entry beneath the specified base directory.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#Extract
	 * @param ?string $dirPath
	 * @return bool
	 */
	function Extract($dirPath) {
		return CkZipEntry_Extract($this->_cPtr,$dirPath);
	}

	/**
	 * Creates an asynchronous task to call the Extract method with the arguments provided.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#ExtractAsync
	 * @param ?string $dirPath
	 * @return ?CkTask
	 */
	function ExtractAsync($dirPath) {
		return chilkat::_obj(CkZipEntry_ExtractAsync($this->_cPtr,$dirPath),'CkTask');
	}

	/**
	 * Extracts this entry directly into the specified directory, ignoring     any path information stored in the ZIP entry.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#ExtractInto
	 * @param ?string $dirPath
	 * @return bool
	 */
	function ExtractInto($dirPath) {
		return CkZipEntry_ExtractInto($this->_cPtr,$dirPath);
	}

	/**
	 * Creates an asynchronous task to call the ExtractInto method with the arguments provided.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#ExtractIntoAsync
	 * @param ?string $dirPath
	 * @return ?CkTask
	 */
	function ExtractIntoAsync($dirPath) {
		return chilkat::_obj(CkZipEntry_ExtractIntoAsync($this->_cPtr,$dirPath),'CkTask');
	}

	/**
	 * This method is deprecated and will be removed in a future version.  Use the FileDateTimeStr property instead. Returns the last-modified date/time of this zip entry.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#GetDt
	 * @return ?CkDateTime
	 * @deprecated
	 */
	function GetDt() {
		return chilkat::_obj(CkZipEntry_GetDt($this->_cPtr),'CkDateTime');
	}

	/**
	 * Updates this ZipEntry object so that it represents the     next entry in the same ZIP archive.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#GetNext
	 * @return bool
	 */
	function GetNext() {
		return CkZipEntry_GetNext($this->_cPtr);
	}

	/**
	 * Updates this ZipEntry object so that it represents the     next entry in the ZIP archive matching the specified wildcard pattern.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#GetNextMatch
	 * @param ?string $pattern
	 * @return bool
	 */
	function GetNextMatch($pattern) {
		return CkZipEntry_GetNextMatch($this->_cPtr,$pattern);
	}

	/**
	 * Inflates this ZIP entry directly into memory and returns the     uncompressed data as a byte array.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#Inflate
	 * @param CkByteData $outData
	 * @return bool
	 */
	function Inflate($outData) {
		return CkZipEntry_Inflate($this->_cPtr,$outData);
	}

	/**
	 * Creates an asynchronous task to call the Inflate method with the arguments provided.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#InflateAsync
	 * @return ?CkTask
	 */
	function InflateAsync() {
		return chilkat::_obj(CkZipEntry_InflateAsync($this->_cPtr),'CkTask');
	}

	/**
	 * Loads the caller of the task's async method.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#LoadTaskCaller
	 * @param CkTask $task
	 * @return bool
	 */
	function LoadTaskCaller($task) {
		return CkZipEntry_LoadTaskCaller($this->_cPtr,$task);
	}

	/**
	 * This method is deprecated.  Applications should instead call GetNext. Return the next entry (file or directory) within the Zip
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#NextEntry
	 * @return ?CkZipEntry
	 * @deprecated
	 */
	function NextEntry() {
		return chilkat::_obj(CkZipEntry_NextEntry($this->_cPtr),'CkZipEntry');
	}

	/**
	 * This method is deprecated.  Applications should instead call GetNextMatch. Returns the next entry having a filename matching a pattern.  The * characters matches 0 or more of any character.  The full filename, including path, is used when matching against the pattern. A NULL is returned if nothing matches.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#NextMatchingEntry
	 * @param ?string $matchStr
	 * @return ?CkZipEntry
	 * @deprecated
	 */
	function NextMatchingEntry($matchStr) {
		return chilkat::_obj(CkZipEntry_NextMatchingEntry($this->_cPtr,$matchStr),'CkZipEntry');
	}

	/**
	 * Replaces this ZIP entry's existing contents with new binary data.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#ReplaceData
	 * @param CkByteData $inData
	 * @return bool
	 */
	function ReplaceData($inData) {
		return CkZipEntry_ReplaceData($this->_cPtr,$inData);
	}

	/**
	 * Replaces this ZIP entry's existing contents with new text data.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#ReplaceString
	 * @param ?string $strContent
	 * @param ?string $charset
	 * @return bool
	 */
	function ReplaceString($strContent,$charset) {
		return CkZipEntry_ReplaceString($this->_cPtr,$strContent,$charset);
	}

	/**
	 * Sets the last-modified date/time for this ZIP entry.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#SetDt
	 * @param CkDateTime $dt
	 */
	function SetDt($dt) {
		CkZipEntry_SetDt($this->_cPtr,$dt);
	}

	/**
	 * Unzips this entry directly into a BinData object.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#UnzipToBd
	 * @param CkBinData $binData
	 * @return bool
	 */
	function UnzipToBd($binData) {
		return CkZipEntry_UnzipToBd($this->_cPtr,$binData);
	}

	/**
	 * Creates an asynchronous task to call the UnzipToBd method with the arguments provided.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#UnzipToBdAsync
	 * @param CkBinData $binData
	 * @return ?CkTask
	 */
	function UnzipToBdAsync($binData) {
		return chilkat::_obj(CkZipEntry_UnzipToBdAsync($this->_cPtr,$binData),'CkTask');
	}

	/**
	 * Unzips this entry as text and appends the result to a     StringBuilder.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#UnzipToSb
	 * @param int $lineEndingBehavior
	 * @param ?string $srcCharset
	 * @param CkStringBuilder $sb
	 * @return bool
	 */
	function UnzipToSb($lineEndingBehavior,$srcCharset,$sb) {
		return CkZipEntry_UnzipToSb($this->_cPtr,$lineEndingBehavior,$srcCharset,$sb);
	}

	/**
	 * Creates an asynchronous task to call the UnzipToSb method with the arguments provided.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#UnzipToSbAsync
	 * @param int $lineEndingBehavior
	 * @param ?string $srcCharset
	 * @param CkStringBuilder $sb
	 * @return ?CkTask
	 */
	function UnzipToSbAsync($lineEndingBehavior,$srcCharset,$sb) {
		return chilkat::_obj(CkZipEntry_UnzipToSbAsync($this->_cPtr,$lineEndingBehavior,$srcCharset,$sb),'CkTask');
	}

	/**
	 * Unzips this entry to a stream.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#UnzipToStream
	 * @param CkStream $toStream
	 * @return bool
	 */
	function UnzipToStream($toStream) {
		return CkZipEntry_UnzipToStream($this->_cPtr,$toStream);
	}

	/**
	 * Creates an asynchronous task to call the UnzipToStream method with the arguments provided.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#UnzipToStreamAsync
	 * @param CkStream $toStream
	 * @return ?CkTask
	 */
	function UnzipToStreamAsync($toStream) {
		return chilkat::_obj(CkZipEntry_UnzipToStreamAsync($this->_cPtr,$toStream),'CkTask');
	}

	/**
	 * Inflates this entry and returns the uncompressed data as a string.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#UnzipToString
	 * @param int $lineEndingBehavior
	 * @param ?string $srcCharset
	 * @return ?string
	 */
	function unzipToString($lineEndingBehavior,$srcCharset) {
		return CkZipEntry_unzipToString($this->_cPtr,$lineEndingBehavior,$srcCharset);
	}

	/**
	 * Creates an asynchronous task to call the UnzipToString method with the arguments provided.
	 * @see https://www.chilkatsoft.com/refdoc/phpCkZipEntryRef.html#UnzipToStringAsync
	 * @param int $lineEndingBehavior
	 * @param ?string $srcCharset
	 * @return ?CkTask
	 */
	function UnzipToStringAsync($lineEndingBehavior,$srcCharset) {
		return chilkat::_obj(CkZipEntry_UnzipToStringAsync($this->_cPtr,$lineEndingBehavior,$srcCharset),'CkTask');
	}
}
